### ISSUE TITLE
Toast and Messages do not close, after the default delay, all messages on multiple messages[]

### ISSUE THREAD

**Issue by myset** [primefaces/primereact#3991] opened 2023-01-27 11:16 UTC
### Describe the bug

 Toast and Messages do not close, after the default delay, all messages on multiple messages[]

My environment is the following:  
    "primeflex": "^3.3.0",
    "primeicons": "^6.0.1",
    "primereact": "^8.7.3",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",

The sample page used to reproduce is

```
import React, {useRef} from 'react';

// Primereact
import {Messages} from 'primereact/messages';
import {Toast} from 'primereact/toast';
import {Button} from 'primereact/button';


export const TestMessages = () => {

    // Messages
    const messagesRef = useRef(null);
    const toastRef = useRef(null);

    function showMessages(){
        messagesRef.current.show(
            [
                {severity: 'info', summary: 'Message 1', detail: 'Message detail 1'},
                {severity: 'success', summary: 'Message 2', detail: 'Message detail 2'},
                {severity: 'warn', summary: 'Message 3', detail: 'Message detail 3'},
                {severity: 'error', summary: 'Message 4', detail: 'Message detail 4'}
            ]
        );
        toastRef.current.show(
            [
                {severity: 'info', summary: 'Message 1', detail: 'Message detail 1'},
                {severity: 'success', summary: 'Message 2', detail: 'Message detail 2'},
                {severity: 'warn', summary: 'Message 3', detail: 'Message detail 3'},
                {severity: 'error', summary: 'Message 4', detail: 'Message detail 4'}
            ]
        );
    }

    function clearMessages(){
        messagesRef.current.clear()
        toastRef.current.clear();
    }

    //---------------------------------
    //             Return
    //---------------------------------
    return (
        <div>
            <Messages ref={messagesRef}/>
            <Toast ref={toastRef}/>
            <p>
                <Button label='Messages'
                        onClick={showMessages}
                        className="p-button-sm p-button-rounded"
                        style={{'marginRight': '4px'}}/>
                <Button label='Clear'
                        onClick={clearMessages}
                        className="p-button-sm p-button-rounded"
                        style={{'marginRight': '4px'}}/>
            </p>
        </div>
    )
}

```` 

After button Messages button press messages appear in Toast and Messages but after default delay of 3000 close only last message of each (Toast or Messages) ... only Message 4 of each

P.S.
If I use fixed delay < 1000 for each message everything works fine ?!?!?!?

### PrimeReact version

8.7.3

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Browser(s)

All

### Steps to reproduce the behavior

1. Click on Messages and wait 3 seconds

### Expected behavior

Close all messages

**Comment by melloware** [comment] 2023-01-27 12:12
Duplicate of https://github.com/primefaces/primereact/issues/3367 see that ticket for the reason and the workaround.

**Comment by melloware** [comment] 2023-01-27 12:43
You can see it in Action in the Showcase if you click the "Multiple" button: https://primereact.org/toast/

**Comment by myset** [comment] 2023-01-27 17:36
Right. I'm wondering why this behavior is ?!?!? 
Maybe the webpack does something specific on my Ubuntu 20.04 x64 Linux machine

**Comment by melloware** [comment] 2023-01-27 18:26
Its a timing issue.  SO it may depend on the speed of CPU or rendering I noticed it happens less on Next.JS than CRA.  But because each is in a `setTimeout` JS call if all 4 fire exactly at the same time you see the behavior.  If some of them are slightly delayed because of CPU business or whatever your will see them close.  So the workaround trick basically always makes them fire staggered.

**Comment by myset** [comment] 2023-01-27 22:40
If the "life" attribute is delayed for every message (5000,4000,3000,2000), all messages close well

**Comment by melloware** [comment] 2023-01-27 23:07
You can give it a really small difference like 3050 3100 3150 3200 and it should work too

**Comment by myset** [comment] 2023-01-28 08:36
Thank you, [melloware](https://github.com/melloware) 
Keep up the good work 😊 🧑‍💻 🍀

**Closed** 2023-01-28 12:40 UTC
Labels: Resolution: Workaround
