### ISSUE TITLE
DOCS:  Use of deprecated Calendar - CalendarChangeEvent interface in docs

### ISSUE THREAD

**Issue by qwadrox** [primefaces/primereact#7218] opened 2024-09-19 05:23 UTC
### Describe the bug

`onChange={(e: CalendarChangeEvent)`

https://github.com/primefaces/primereact/blob/e49e82457f6c2e3d6617b85f75fd1a65248e2cf5/components/doc/datatable/samples/customersdoc.js#L619

### System Information

```Shell
-
```

**Comment by qwadrox** [comment] 2024-09-19 05:26
Also on Advanced filtering: https://primereact.org/datatable/

**Comment by sja-cslab** [comment] 2024-09-19 05:56
Duplicate of #7208 which is fixed already

**Comment by qwadrox** [comment] 2024-09-19 06:20
@sja-cslab This is a different file not the table filtering: [primereact/components/doc/datatable/samples/customersdoc.js](https://github.com/primefaces/primereact/blob/e49e82457f6c2e3d6617b85f75fd1a65248e2cf5/components/doc/datatable/samples/customersdoc.js#L619)

But yes, the advanced filtering part has been fixed, but the current deployed version of the docs still not reflect the fix.

**Comment by melloware** [comment] 2024-09-19 11:11
Yep it will be fixed on next deployment.  I will look for all instances of CalendarChangeevent and remove them

**Closed** 2024-09-19 13:30 UTC
Labels: Component: Documentation
