### ISSUE TITLE
Component:  Dialog - Maximizable

### ISSUE THREAD

**Issue by FaranMustafa** [primefaces/primereact#3339] opened 2022-09-19 11:32 UTC
### Describe the bug

Okay so whenever we open the dialog and maximize it and then close it then there is no scroll on the website 

### PrimeReact version

8.5.0

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Browser(s)

chrome

### Steps to reproduce the behavior

1. Go to Dialog component
2. Go to  Maximizable Dialog 
3. Them maximize it
4. then close it 
5. then you have the scroll

**Comment by melloware** [comment] 2022-09-19 11:36
Duplicate of https://github.com/primefaces/primereact/issues/3331   see that ticket for workaround.

**Closed by melloware** 2022-09-19 11:36 UTC
Labels: Status: Needs Triage
