### ISSUE TITLE
Datatable context menu and selection blend

### ISSUE THREAD

**Issue by flash4174** [primefaces/primereact#5146] opened 2023-10-24 09:08 UTC
### Describe the bug

Hi There,

My problem is that I’m using Datatable with the checkbox selection function and with contextmenu too, but when I select multiple lines with the checkbox the contextmenu selection state is populated with the row selection content.

My aim is to be able to select multiple rows with left click, but when on righ click the context menu shows an ‘open’ menu item an on click it opens up a modal with the single row details that is click with the right mouse button.

It work fine until I select multiple lines with left click and then right click on a line, because the state contain all the selected rows.

i use different state (react usestate) for the selection and onContectMenuSelection props

### PrimeReact version

10.0.4

### React version

18.x

### Language

ES6

### Build / Runtime

Next.js

### Browser(s)

Chrome

**Comment by melloware** [comment] 2023-10-24 11:52
@flash but can't you just use `onContextMenuSelectionChange={(e) => setSelectedProduct(e.value)}` and set your selection to the already selected values?

**Comment by flash4174** [comment] 2023-10-24 12:19
No, because that way it’s just add to the selection like with left click and sends no data. My latest attempt like:
`selection={selectedProducts}`
`onSelectionChange={(e) => setSelectedProducts(e.value)}`
`contextMenuSelection={selectedContext}`
`onContextMenuSelectionChange={(e) => setSelectedContext(e.value)}`

**Comment by melloware** [comment] 2023-10-24 12:29
Can you create a StackBlitz reproducer so I can try it?

**Comment by flash4174** [comment] 2023-10-24 13:40
[codesandbox](http://codesandbox.io/embed/primereact-demo-forked-xzck43)

**Comment by melloware** [comment] 2023-10-24 13:42
OK it looks like its working?  I CTRL+LEFTCLICK 3 items then I right click and the ContextMenu is displayed and the 3 items remain selected?

**Comment by melloware** [comment] 2023-10-24 14:06
Its fixed: https://codesandbox.io/s/primereact-demo-forked-67nzvk?file=/src/App.js

Your ViewProduct was viewing an Array but thinking it was 1 item so `product.name` is always blank.

**Comment by flash4174** [comment] 2023-10-24 14:14
Well, I would like to fully separate the left and right click.

For example the first 3 rows selected with left click and when I right click on the forth row the toast should only show the fourth product name and the left click selection must keep

**Comment by rafalwojdowski** [comment] 2023-11-07 14:03
Datatable version 9.6.2 worked as described by @flash417. Unfortunately, as of version 10 this has stopped working.
Users are used to the context menu and selection blend, which is definitely more convenient.
I would appreciate the implementation of this issue in version 10.0.10 or next.

**Comment by xryanwilson** [comment] 2023-11-07 21:15
@melloware - I believe this should be a Bug, not an Enhancement. The behavior of the `onContextMenuSelectionChange` callbox is inconsistent, and a breaking change relative to v9.6.2.

Using the sandbox you provided (https://codesandbox.io/s/primereact-demo-forked-67nzvk?file=/src/App.js), I see the following issues:

1. If no records are selected in the grid, right-click any record and click View. This results in an exception because `ViewProduct` expects `products` to be an array, but in this case it is a object.
2. Select one or more records in the grid. Right-click a different record (one that was not previously selected), and click View. In this case, `ViewProduct` does get the `products` as an array as it expects. However, the toast displays the previously selected record(s), and not the record that was right-clicked.

In v9.6.2, right-clicking a record always passed the right-clicked record data with the `onContextMenuSelectionChange` event. As of v10.0.2, the right-clicked record data is not available on the event unless it was already selected in the grid prior to triggering the context menu.

**Comment by melloware** [comment] 2023-11-07 21:28
Switched to bug.

**Comment by rayman-de** [comment] 2023-11-23 12:45
As far as I can see, the bug was introduced in [this commit](https://github.com/primefaces/primereact/pull/5037/commits/0c91e8997b40470ba9e7118066f9c3d1b871809c).
Before, at least when multiSelection was enabled, the original event data was passed to onContextMenuSelectionChange

**Comment by rayman-de** [comment] 2023-11-23 13:40
The bug seems to come from `onRowRightClick` in TableBody.js. Why is that callback not exposed to the user? What is the point of having `contextMenuSelection` at the moment? It does not seem to be used for anything but styling? How can a dev properly change the `contextMenuSelection` if they cannot access the row that has been right-clicked?

**Comment by rayman-de** [comment] 2023-11-23 14:32
For those looking for a work-around until this is fixed/changed:
You can keep the row that is hovered over with the mouse in a state by using `onRowMouseEnter` (and also `onRowMouseExit` if you want) and then using *that* row in `onContextMenuSelectionChange` instead of the actual argument passed to it.

**Comment by melloware** [comment] 2024-04-17 12:18
Fixed with https://github.com/primefaces/primereact/pull/6403

**Closed by melloware** 2024-04-17 12:18 UTC
Labels: Type: Bug
