### ISSUE TITLE
DataTable: dynamic columns issue

### ISSUE THREAD

**Issue by meysamzi** [primefaces/primereact#4479] opened 2023-06-02 06:26 UTC
### Describe the bug

Describe the bug
when i use prime data table for react js, it adds columns horizontally but when it comes to the tbody of prime it adds data passed to the value of datatable vertically .

          <DataTable stripedRows value={monthsHeaders} scrollable>
            {monthsHeaders?.map((data) => (
              <Column
                header={data?.Month}
                body={(rowData) => rowData?.MonthKeyId}
                style={{ minWidth: "700px" }}
                frozen={data?.Index === 2}
                className="font-bold"
              ></Column>
            ))}
          </DataTable>

### PrimeReact version

9.4.0

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Expected behavior

i want tbody to fill the data horizontally not vertically

**Comment by melloware** [comment] 2023-06-02 10:52
@meysamzi can you update my reproducer to show what you mean? https://stackblitz.com/edit/react-skatua?file=src%2FApp.js

I don't understand what the issue is.

**Comment by melloware** [comment] 2023-06-25 15:13
Closing until issue can be reproduced.

**Closed by melloware** 2023-06-25 15:13 UTC
Labels: Status: Needs Reproducer
