### ISSUE TITLE
DataTable: Wrong button color on sorting in safari

### ISSUE THREAD

**Issue by baireutherjonas** [primefaces/primereact#2799] opened 2022-04-25 15:13 UTC
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
We have a datatable with different customized culomns. In the one column we have rounded outlined buttons with different Icons and colors. If we sort the table the color of the buttons are not displayed correct. You can see the current behaviour in the Screenshot. If we move with the mouse over the buttons, the color is applied correctly. The problem isn't in Chrome and Firefox, its only in Safari.

**Expected behavior**
Correct Colors after sorting the table.

* **React version:**
17.0.2 

* **PrimeReact version:**
7.2.1

* **Browser:** [Safari Version 15.4 (17613.1.17.1.13) ]

 <img width="244" alt="image" src="https://user-images.githubusercontent.com/16540603/165117937-de993c74-7ce9-46a2-91d1-35d3652f6dd7.png">

**Comment by melloware** [comment] 2022-04-25 15:25
You didn't mention what Theme you are using?

**Comment by baireutherjonas** [comment] 2022-04-25 16:24
We use Diamond React 7.0.0 - Green Light

**Comment by melloware** [comment] 2022-04-25 16:44
OK can you do me a favor an inspect the CSS in the DOM for broken Safari button vs working Chrome button.  I have a feeling some CSS is of course being applied differently.

**Comment by baireutherjonas** [comment] 2022-04-25 16:59
chrome 
<img width="636" alt="image" src="https://user-images.githubusercontent.com/16540603/165137257-94d7df0b-760d-4438-91c4-376a4daa672c.png">

safari
<img width="530" alt="image" src="https://user-images.githubusercontent.com/16540603/165137472-15fbc081-e4f3-4495-a06e-e0f055dc7fc8.png">

**Comment by melloware** [comment] 2023-05-10 13:44
Going to close this for now as I can't reproduce this on 9.3.1

**Closed by melloware** 2023-05-10 13:44 UTC
Labels: Status: Pending Review, Browser: Safari, Component: Theme
