### ISSUE TITLE
Datatable do not export csv

### ISSUE THREAD

**Issue by RFormigao** [primefaces/primereact#2530] opened 2021-12-15 19:33 UTC
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/naughty-easley-wmkt4?file=/src/demo/DataTableExportDemo.js

**Current behavior**
When I click to export the data in CSV nothing happens

**Expected behavior**
The table is expected to export the files.

* **React version:**
17.0.2

* **PrimeReact version:**
7.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
[all]

**Comment by melloware** [comment] 2021-12-16 14:09
Interesting in my 7.1.0 project my export is working OK.  I wonder if its a Code Sandbox problem or are you having this issue in your real app as well?

**Comment by RFormigao** [comment] 2021-12-16 20:24
It doesn't work in my application either.

**Comment by melloware** [comment] 2021-12-19 12:46
I know why its not working in Sandbox open the F12 console and you will see this error:

![image](https://user-images.githubusercontent.com/4399574/146675314-9641a9f3-5c86-4dbe-8058-4dc8b501251d.png)

Check if your project has a similar issue blocking iFrames.

**Comment by melloware** [comment] 2022-01-04 15:05
@RFormigao any update on this?   I can't reproduce in any of my projects.

**Comment by RFormigao** [comment] 2022-01-05 14:12
Hello, sorry the delay was on vacation.

I looked here and the problem is in a component of ours that calls the export function, I removed this component (Dropdown) and used a simple button and the export worked.

I'm going to debug my dropdown component, but I believe the issue can be closed.

**Comment by melloware** [comment] 2022-01-05 14:21
OK you can close it please :)

**Closed** 2022-01-05 16:46 UTC
