### ISSUE TITLE
TabPanel closable prop does not work as intended

### ISSUE THREAD

**Issue by waqarmalyk** [primefaces/primereact#5778] opened 2024-01-16 12:57 UTC
### Describe the bug

I have this snippet of code below which seems to not work as intended. What the bug is that if you have more than 1 TabPanel and if you close the tab it does not goes back to the last index but rather goes to unexpected screen.  Here is the implementation of the tabs. And also the evt.StopPropogation does not work quite well. I have pencil icon to rename the tab but it does not work properly.

![tabs'](https://github.com/primefaces/primereact/assets/54630600/615fd5af-573d-4942-8553-fa5fb00f88d0)

### Reproducer

https://codesandbox.io/p/sandbox/primereact-test-forked-zctjhm?file=%2Fsrc%2FQueries%2FQueryActionMenu.jsx%3A12%2C37

### PrimeReact version

10.0.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome 120

**Comment by melloware** [comment] 2024-01-16 13:22
working fine here in 10.3.1: https://primereact.org/tabview/#closable

Please provide a reproducer showing your issue.

**Comment by waqarmalyk** [comment] 2024-01-16 13:42
Here is the link for code 
https://codesandbox.io/p/sandbox/primereact-test-forked-zctjhm?file=%2Fsrc%2FQueries%2FQueryActionMenu.jsx%3A12%2C37

**Comment by melloware** [comment] 2024-01-16 13:58
OK so the closable works on the `key` of your TabPanel to know which one to close like in the Showcase. It looks like when you click Close its re-rendering your tabPanels and `{queries.map(` is returning a NULL tabPanel so its generating a blank tab which then gets focus as the Close event tries to focus the next available tab.

**Comment by waqarmalyk** [comment] 2024-01-16 14:11
The code does not explicitly return null. Each iteration of the map function over the queries array is returning a TabPanel component, which should not result in a blank tab under normal circumstances.

**Comment by melloware** [comment] 2024-01-16 14:12
Yeah but you have to debug its creating a TabPanel because your `map` function is telling it to create a TabPanel.

**Comment by melloware** [comment] 2024-01-16 14:15
Start simple with this and work backwards trying to reproduce: https://stackblitz.com/edit/wazjse?file=src%2FApp.jsx

**Comment by melloware** [comment] 2024-01-16 14:21
When I console.log your queries after I click the CLOSE button the array is still showing 2 items.

![image](https://github.com/primefaces/primereact/assets/4399574/1a7e3e32-6d69-4483-9eaf-fa0719c08a39)

**Comment by waqarmalyk** [comment] 2024-01-16 14:26
Seems like I have to have my own custom close handler since closable prop is from PrimeReact I do not have control over that and it causing the unexpected behaviour. 
But thankyou for your valuable comments and time :)

**Closed** 2024-01-16 14:28 UTC
Labels: Resolution: By Design

**Comment by waqarmalyk** [comment] 2024-01-16 14:50
> working fine here in 10.3.1: https://primereact.org/tabview/#closable
> 
> Please provide a reproducer showing your issue.

Btw does not work same for me, have a look at recording here!

https://github.com/primefaces/primereact/assets/54630600/aeaffc62-cc35-47c9-ac59-df68445ef479

**Comment by melloware** [comment] 2024-01-16 14:56
Yeah I see if i click Tab3 close it doesn't focus another tab but it does close and render properly. Yours is creating a blank tab: https://stackblitz.com/edit/wazjse?file=src%2FApp.jsx

**Comment by waqarmalyk** [comment] 2024-01-16 15:51
Ah, I sent you recording from official PrimeReact page it is not mine and also it does matter if its 3rd of 2nd it goes to blank.
