### ISSUE TITLE
TypeScript: Improve definitions on all components

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primereact#2734] opened 2022-04-10 12:35 UTC
Ref; https://github.com/primefaces/primevue/blob/master/src/components/accordion/Accordion.d.ts

Notes:
- https://github.com/primefaces/primereact/issues/2732
- https://github.com/primefaces/primereact/issues/2721

_A general study can be made on this subject and help users read the codes better._

**Comment by Named-export** [comment] 2022-04-15 13:20
How are the typescript definitions generated? By hand?

**Comment by melloware** [comment] 2022-04-15 14:07
> How are the typescript definitions generated? By hand?

Yes currently by hand when we make changes in the components we update the TS definition.

**Comment by kalinkrustev** [comment] 2022-04-15 14:57
> [mertsincan](https://github.com/mertsincan) added this to the [9.0.0](https://github.com/primefaces/primereact/milestone/92) milestone [5 days ago](https://github.com/primefaces/primereact/issues/2734#event-6403839336) 

Does this mean version 9 will be based on TypeScript? Sounds cool !!!

**Comment by melloware** [comment] 2022-04-15 14:58
I am not sure is going to be written in TypeScript just that the definitions get an overhaul and documented similar to how PrimeVue is doing it.

**Comment by gordolio** [comment] 2022-11-29 21:15
Honestly, most of the issues that I experience with primereact are related to the type definitions being missing or incorrect. This happens most often with events. I often need to place a breakpoint in an event just to see what arguments are passed in.

IMHO, the lasting fix for this would be to have a typescript-first approach. Change the extensions of all the `js` source files to be `ts`, add the `noImplicitAny: true` option, and let the typescript compiler show what needs to be fixed.

Then future improvements will have a much reduced chance of regression in missing/incorrect type definitions.

**Comment by gordolio** [comment] 2022-11-29 21:29
Additional improvements could be made by making`options` on various components into generics.. `options: T[]`, then definitions like this could be used: `optionLabel?: keyof T, optionValue?: keyof T, ` etc.

**Comment by melloware** [comment] 2022-11-29 21:33
@gordolio its easier said than done if you look at this attempt at a PR which worked but we had to roll it back because it was too burdensome: https://github.com/primefaces/primereact/pull/3199/files

**Closed** 2023-01-22 17:11 UTC
Labels: Type: Enhancement, Type: Breaking Change, Typescript
