### ISSUE TITLE
ConfirmDialog: is not loading inside a Shadow DOM

### ISSUE THREAD

**Issue by kartheekgadduru** [primefaces/primereact#4096] opened 2023-02-24 11:26 UTC
### Describe the bug

I have the code as below with file name testView.tsx
`import * as React from "react";
import * as ReactDOM from "react-dom";

import "./theme/resourceapp/theme.css";
import "primereact/resources/primereact.min.css";
import "primeicons/primeicons.css";
import {TuningBucket} from "./components/tuning/TuningBucket";
import {TestView} from "./components/TestView";

const root = document.getElementById("test-view") as HTMLElement;
const shadowRoot = root.attachShadow({ mode: "open" });

const reactRoot = document.createElement("div");
shadowRoot.appendChild(reactRoot);

const event = new Event("react-ready");
document.dispatchEvent(event);

ReactDOM.render(<TestView/>, reactRoot);`

And TestView.tsx file code 
`import * as React from "react";
import {useState} from "react";
import {Button} from "primereact/button";
import {ConfirmDialog} from "primereact/confirmdialog";

export const TestView = () => {
    const [visible, setVisible] = useState<boolean>(false);
    const reject = () => {
        console.log("reject ");
    };
    const accept = () => {
        console.log("accept ");
    };
    return (
        <div>
            <Button
                label={"Update"}
                onClick={() => setVisible(true)}
            ></Button>
            <ConfirmDialog visible={visible} onHide={() => setVisible(false)}
                           message="Are you sure you want to proceed?"
                           header="Confirmation" icon="pi pi-exclamation-triangle" accept={accept} reject={reject}/>
        </div>
    );
}`
ConfirmDialog code is loading outside of Shadow Dom (shadow-root) when I inspect from developer tools because of that stylings of primereact is not applying to ConfirmaDialog component. can be seen with below image.

- From the image the one which is rounded with black is the output for the ConfirmDialog component 
- Rounded with Green is the Shadow Dom code which includes all the Primereact stylings 
- And Rounded with Red is the code of ConfirmDialog at run time loading out side of ShadowDom

![confirmDialogIssue](https://user-images.githubusercontent.com/18613111/221167599-9bf2ecf3-b4ea-4b74-9883-2be1388a140c.png)

### PrimeReact version

^8.1.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by kartheekgadduru** [comment] 2023-02-24 11:28
Need you guys help to fix such that ConfirmDialog code should come inside of Shadow dom code
So that the styling of the ConfirmDialog code applied correctly.

**Comment by kartheekgadduru** [comment] 2023-02-25 02:21
![confirmDialog](https://user-images.githubusercontent.com/18613111/221331186-ae75014e-336b-47ab-bf96-d5e2d8ecab64.JPG)

**Comment by melloware** [comment] 2023-02-25 03:37
Screenshots don't help. a Code Sanbox reproducer would help.

**Comment by mertsincan** [comment] 2023-03-09 11:58
Hi,

Unfortunately, I couldn't replicate this issue. Please try;
https://codesandbox.io/s/primereact-test-forked-uxr48m?file=/src/index.js

If the problem persists, please reopen this issue. For now, closed. Thanks a lot for your understanding!

Best Regards,

**Comment by rogiermulders** [comment] 2023-03-09 13:25
@mertsincan Your codesandbox example does exactly what @kartheekgadduru describes :)
Look at your confirm an delete buttons. The are **not** styled because the are in the shadow dom.
Now your Dialog is placed outside the shadow DOM (in the normal DOM tree) so it **is** styled.

But this is how I solved my normal Dialog in the Shadow Dom `<Dialog appendTo={context.shadowRoot} />`

Where my context knows about the shadowRoot **and** the entire App waits until it is available.

**Comment by rogiermulders** [comment] 2023-03-10 08:49
I tried this `<ConfirmDialog appendTo={context.shadowRoot}/>` but that does indeed not work.

The Dialog component works though. See both in action here https://codesandbox.io/s/5wou0t

At this moment I do not know how to get all the primereact css in the Shadow DOM of codesandbox so just one classname, but you should get the point

**Comment by kartheekgadduru** [comment] 2023-03-10 10:21
HI @melloware and @rogiermulders 
Please find my codesandbox url for the code in my project in which I am testing the ConfirmDialog should render inside the shadowRoot and should apply all the styles of prime react for the ConfirmDialog component 
```
 import 'primeicons/primeicons.css';
import 'primereact/resources/themes/lara-light-indigo/theme.css';
import 'primereact/resources/primereact.css';

```
but in my code I supposed to have anchored tag similar to after login button from codesandbox url
```
 <a href="./testView.do">
        testView
    </a>
```
Whatever the code which have provided from the codesandbox url is working in my local.
I think this info is helpful to address my issue related to ConfrimDialog primereact component

**Comment by melloware** [comment] 2024-01-05 22:10
Fixed with: https://github.com/primefaces/primereact/pull/5566

**Closed by melloware** 2024-01-05 22:10 UTC
Labels: Type: Bug
