### ISSUE TITLE
Horizontal Scroller in the Data Table with selection/checkbox resets to initial position on clicking anywhere in the Data Table Row

### ISSUE THREAD

**Issue by indra-sen-morrisonsplc** [primefaces/primereact#3158] opened 2022-08-13 18:23 UTC
### Describe the bug

Dealing with large numbers of columns in a Data Table, the Data Column can have a horizontal scroller along with a checkbox. While clicking anywhere in the DataTable component with a checkbox/selection, the horizontal scroller automatically resets to it's initial position when clicked anywhere on the row item. Ideally the click should not reset the scroller position.

CodePen Example :  https://codesandbox.io/s/serene-nightingale-j3s1iy?file=/src/demo/DataTableSelectionDemo.js

### Reproducer

https://codesandbox.io/s/serene-nightingale-j3s1iy?file=/src/demo/DataTableSelectionDemo.js

### PrimeReact version

6.6.0

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Import a DataTable component with selection/checkbox. 
2. Make sure that it has enough columns to have a horizontal scroller
3.Drag the horizontal scroller towards complete right to shift the initial content a little bit.
4.Now click anywhere on the row, the horizontal scroller will automatically reset to initial position.

### Expected behavior

The scroller should not reset it's position as the user might be willing to edit a certain cell. The scroller must stay at it's position.

**Comment by melloware** [comment] 2022-08-13 18:38
Duplicate of https://github.com/primefaces/primereact/issues/3155

**Closed by melloware** 2022-08-13 18:38 UTC
Labels: duplicate
