### ISSUE TITLE
[TieredMenu] Can't open submenu on hover without a hack, was possible in previous version

### ISSUE THREAD

**Issue by petarcaspio** [primefaces/primereact#6180] opened 2024-03-19 20:55 UTC
### Describe the bug

Only way for me to handle opening submenu via hover is like this:
```
useEffect(() => {
			const switchAccountItem = document.querySelectorAll('li[aria-haspopup="menu"]')[0];
			const submenu = document.querySelector('.p-submenu-list');

			if (switchAccountItem) {
				switchAccountItem.addEventListener('mouseover', () => {
					submenu?.setAttribute('style', 'display: block; top: 0px;');
					switchAccountItem.setAttribute('style', 'background: #f0f5f9');
				});
				switchAccountItem.addEventListener('mouseout', () => {
					submenu?.setAttribute('style', 'display: none;');
					switchAccountItem.setAttribute('style', 'background: none');
				});
			}
});
````

And in some of the previous versions worked out of the box.

### PrimeReact version

10.3.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Expected behavior

Well a control for this behavior should be available at least.

**Comment by melloware** [comment] 2024-03-19 22:05
Duplicate of https://github.com/primefaces/primereact/issues/5975

**Closed** 2024-03-19 22:06 UTC
Labels: Resolution: Duplicate
