### ISSUE TITLE
MultiSelect close button type not defined - Can lead to preventing a <form> from submitting

### ISSUE THREAD

**Issue by manstir** [primefaces/primereact#1136] opened 2020-01-06 10:30 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
given a regular html form with a MultiSelect component from prime:
```
<form onSubmit={this.handleSubmit}>
  <MultiSelect value={...} options={...} />
  <input type="text" name="regularInput" value={...} onChange={...} />
  <button type="submit">submit</button>
</form>
```

if the cursor is in the "regularInput" field, the "Enter" Key does not submit the form. "handleSubmit" won't be called. 

Issue: the MultiSelect-Header contains a close button: <button... />
https://github.com/primefaces/primereact/blob/3bc8ce8ab53238515483e9b1e38ac5209fda5b13/src/components/multiselect/MultiSelectHeader.js#L72
but because the type="button" <button type="button"... is missing, it will be type=submit by default. 

the form will use the first "submit" button onEnter. hence, the submitbutton at the end of the for wont be executed.

if prime does not relay on the close button in the MultiSelect beeing "type=submit". is sggest you add "type=button" 

* **Browser:** 
Chrome 79

* **Language:**
ES6

**Comment by mertsincan** [comment] 2020-01-17 08:28
Duplicate of  #1155

**Closed by mertsincan** 2020-01-17 08:28 UTC
