### ISSUE TITLE
DataTable does not scroll with Row Grouping

### ISSUE THREAD

**Issue by stfabian** [primefaces/primereact#779] opened 2019-02-20 07:23 UTC
Was asked to move the issue from the forum to Github.
https://forum.primefaces.org/viewtopic.php?f=57&t=58053

x-axes scrolling does not work with row grouping:
https://codesandbox.io/s/l4v1kz4omq

(Maybe same problem as https://github.com/primefaces/primereact/issues/635)

Version: 3.0.0

**Comment by mertsincan** [comment] 2019-03-11 20:08
Duplicate of #635

**Closed by mertsincan** 2019-03-11 20:08 UTC
