### ISSUE TITLE
DataTable: rowData and newRowData are equals in onCellEditComplete 

### ISSUE THREAD

**Issue by ws-ksda** [primefaces/primereact#4308] opened 2023-04-28 19:20 UTC
### Describe the bug

I needed compare rowData and newRowData values to call another function, mas they are ever equals.

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-l4ve9c?file=/src/App.js

### PrimeReact version

9.3.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment] 2023-04-28 19:42
Possible duplicate of: https://github.com/primefaces/primereact/issues/2424 ???

**Comment by thejus557** [comment] 2023-08-08 15:50
@melloware  you can close this issue because its resolved by another issue i.e #4648

**Comment by melloware** [comment] 2023-08-08 16:17
Awesome I assigned you, linked the PR, and closing this ticket.

**Closed by melloware** 2023-08-08 16:17 UTC
Labels: Type: Bug
