### ISSUE TITLE
Tree DragDrop doesn't allow drag and drop between nodes

### ISSUE THREAD

**Issue by michalmova** [primefaces/primereact#7087] opened 2024-08-26 13:14 UTC
### Describe the bug

PrimeReact - latest version 10.8.2 - Tree DragDrop doesn't allow drag and drop between nodes.

working version (7.1.0) sandbox: https://codesandbox.io/p/sandbox/amazing-gould-qy4m6r?from-embed=&workspaceId=4aecfb1c-06ef-4a24-a86f-2cc9c686780e

NOT working version sandbox (10.8.2): https://codesandbox.io/p/sandbox/ecstatic-heyrovsky-5ntj5z?from-embed=&workspaceId=4aecfb1c-06ef-4a24-a86f-2cc9c686780e

### System Information

    "primereact": "^10.8.2",
    "react": "18.2.0",

**Comment by melloware** [comment] 2024-08-26 13:19
Duplicate of https://github.com/primefaces/primereact/issues/7058

**Closed** 2024-09-13 17:30 UTC
Labels: Resolution: Duplicate
