### ISSUE TITLE
Calendar Component Requires Two Clicks for Date Selection in PrimeReact v9.6.0

### ISSUE THREAD

**Issue by bizwms** [primefaces/primereact#4734] opened 2023-08-04 07:29 UTC
### Describe the bug

There seems to be a noticeable change in the behavior of the Calendar component while selecting values from primereact version 8.7.0 to 9.6.0. In primereact version 8.7.0, it was possible to select a value with a single click, however, in primereact version 9.6.0, it requires two clicks to select a value. This behavior is also observed on the official demo site.

### Reproducer

https://primereact.org/calendar/

### PrimeReact version

9.6.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Browser(s)

Chrome 115.0.5790.171（Official Build）（64 bit）

### Steps to reproduce the behavior

Visit the official demo site at https://primereact.org/calendar/
Click on the Calendar component to open the date picker.
Try to select any date with a single click.

This should reproduce the issue where it requires two clicks to select a date.

### Expected behavior

Upon clicking on any date in the Calendar component, the date should be selected immediately with just one click, similar to the behavior observed in primereact version 8.7.0.

**Comment by melloware** [comment] 2023-08-04 13:32
Duplicate of https://github.com/primefaces/primereact/issues/4568 already fixed for 10.0.0

**Closed by melloware** 2023-08-04 13:32 UTC
Labels: Resolution: Duplicate
