### ISSUE TITLE
Calender: Have to double click to select a date

### ISSUE THREAD

**Issue by CharlRitterCompany** [primefaces/primereact#4747] opened 2023-08-08 12:57 UTC
### Describe the bug

When using the calendar, the date needs to be clicked twice to be selected. It seems to be the current behaviour on all the calendar components on the documentation for PrimeReact.

### PrimeReact version

^9.6.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Go to the page with the Calender component (Documentation is good)
2. Click on the calendar.
3. Click on a date.
4. The date won't be set and will need to be clicked again.

### Expected behavior

Choosing a date on the Calendar component should be set on the first click.

**Comment by melloware** [comment] 2023-08-08 12:58
Duplicate of https://github.com/primefaces/primereact/issues/4568 already fixed for 10.0.0

**Closed** 2023-08-08 12:58 UTC
Labels: Resolution: Duplicate
