### ISSUE TITLE
DataTable: onValueChange fires if the selection if updated

### ISSUE THREAD

**Issue by JaredHammond** [primefaces/primereact#5281] opened 2023-11-10 14:52 UTC
### Describe the bug

 Since 10.0.x, onValueChange callback runs when the selected rows changes. Within my application, this is causing an infinite loop issue. According to DataTable api docs, onValueChange is "Callback to invoke after filtering and sorting to pass the rendered value."

### Reproducer

https://codesandbox.io/p/sandbox/onvaluechange-infiniteloop-forked-7p94pj

### PrimeReact version

10.0.x

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA) and Next.js 13.2.1 using pages router.

### Steps to reproduce the behavior

1. Go to reproducer codesandbox.
2. Open console
3. Select row, see that onValueChange callback fires.
4. Bonus: Uncomment line 117 and cause inifinte loop.

### Expected behavior

I expect onValueChange to only run if sorting or filtering happens. This behaves as expected in v9.6.0. 

Same codesandbox as the reproducer, but with primereact@9.6.0.

[https://codesandbox.io/p/sandbox/onvaluechange-noinfiniteloop-gqq683](url)

**Comment by melloware** [comment] 2023-11-10 15:18
Duplicate of https://github.com/primefaces/primereact/issues/5160 ???

**Closed** 2023-11-10 15:25 UTC
Labels: Resolution: Duplicate

**Comment by JaredHammond** [comment] 2023-11-10 15:29
Thanks! I thought it was likely a dupe, but hoped the reproducer might be helpful.
