### ISSUE TITLE
DataTable: Advanced Column Filter 'Match Mode' Dropdowns Are Broken in 10.6.4

### ISSUE THREAD

**Issue by SolidAnonDev** [primefaces/primereact#6550] opened 2024-05-02 12:32 UTC
### Describe the bug

The 'advanced' column filter dropdowns that generally holding match modes like "Contains" or "Starts With" cause a break in 10.6.4. You can actually just find this in the documentation itself, as the example linked below has the same issue my application had when 10.6.4 was installed.

### Reproducer

https://primereact.org/datatable/#advanced_filter

### PrimeReact version

10.6.4

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Steps to reproduce the behavior

1. Access the link and if you aren't already there, you will find the issue directly in the 'Advanced Filtering' section of the documentation
2. Open a column filter as designated by the filter icon, where one  contains match modes, I recommend **Name, Country, Date, or Balance**
3. Attempt to open the dropdowns for the match mode and you will see an unrecoverable client side error is thrown.

### Expected behavior

You can open the column filter and select a match mode from the dropdown menu.

You will also notice they do not display a the currently selected value.

**Comment by melloware** [comment] 2024-05-02 12:52
Duplicate of https://github.com/primefaces/primereact/issues/6531

**Comment by Rekl0w** [comment] 2024-05-02 13:09
PR submitted, it should work now.

**Closed** 2024-05-02 13:30 UTC
Labels: Type: Bug

**Comment by melloware** [comment] 2024-05-03 13:59
Please try 10.6.5
