### ISSUE TITLE
Column: PT not getting applied for headerCheckbox

### ISSUE THREAD

**Issue by skj-skj** [primefaces/primereact#7050] opened 2024-08-14 18:20 UTC
### Describe the bug

according to the docs for Column PT
https://primereact.org/datatable/#pt.column.options

headerCheckbox is available to pass props to Checkbox component but props are not getting applied.

I saw there was similar issue which was fixed #6978 but the file change were in DataTable which doesn't have headerCheckbox pt as per [docs](https://primereact.org/datatable/#pt.datatable.options)

### Reproducer

[Stackblitz Project with headerCheckbox issue](https://stackblitz.com/edit/vitejs-vite-b6bup9)

### System Information

PrimeReact: 10.8.2
React: 18.3.1
Vite: 5.4.0

### Expected behavior

props should passed to the checkbox component of headerCheckbox

**Comment by melloware** [comment] 2024-08-14 18:33
cc @peconomou929 since we just fixed this can you help out @skj-skj ?

**Comment by skj-skj** [comment] 2024-08-15 01:29
Hi @melloware,

I created a [Stackblitz project for this issue](https://stackblitz.com/edit/vitejs-vite-b6bup9). In this project, I updated the style of the checkboxes using PrimeFlex classes.

In the `CheckboxTablePT` component, the `rowCheckbox` PT works fine as the styles are applied correctly. but the `headerCheckbox` PT is not working as expected, and the styles are not being applied.

**Comment by melloware** [comment] 2024-08-15 01:42
Thanks I will take a look.

**Comment by peconomou929** [comment] 2024-08-15 09:09
I agree that this is a bug, and what you demonstrate is indeed unexpected behaviour. 

However, another way to achieve what you want is to use the ["column" entry](https://primereact.org/datatable/#api.DataTable.DataTablePassThroughOptions.column) in the DataTablePassThroughOptions, instead of setting the ColumnPassThroughOptions on the Column itself. That usage is precisely what got fixed in #6979 and #6939.

**Comment by melloware** [comment] 2024-08-15 11:24
Oh i see there is a `headerCheckbox` on the DT and one on the `Column`.  You are right that is confusing.

**Comment by skj-skj** [comment] 2024-08-15 11:43
@peconomou929 Thanks that workaround works.
I have updated the [Stackblitz reproducer project](https://stackblitz.com/edit/vitejs-vite-b6bup9) and added the workaround.

this pattern makes sense as in most cases a DataTable will have only one column as checkbox. so instead of pt individual column for `headerCheckbox` and `rowCheckbox` it make sense to pt only DataTable.

**Comment by melloware** [comment] 2024-08-15 11:57
yeah now i am wondering if headerCheckbox should be removed from the `Column` definition.

**Comment by melloware** [comment] 2024-08-15 12:07
OK PR submitted

**Closed** 2024-08-15 12:10 UTC
Labels: Component: Unstyled

**Comment by skj-skj** [comment] 2024-08-15 14:16
@melloware thanks for taking care of this issue.
