### ISSUE TITLE
Calendar: page scroll behaviour

### ISSUE THREAD

**Issue by kusyka911** [primefaces/primereact#3218] opened 2022-08-31 17:30 UTC
### Describe the bug

Calendar panel may be displayed over the other elements on the page after page scroll.

### Reproducer

https://codesandbox.io/s/primereact-calendar-bug-demo-hjryot

### PrimeReact version

8.4.0

### React version

17.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome latest

### Steps to reproduce the behavior

Conditions:
page has fixed element with `z-index: 1` (or higher but less then Calendar panel)
page can be scrolled in a proper way (see Reproducer demo)
1. Open Calendar
2. Scroll the page
3. Pay attention to the result.

### Expected behavior

Calendar is closed after scroll event occur. Or this behaviour can be enabled with prop `closeOnScroll` set to `true`.

**Comment by melloware** [comment] 2022-08-31 17:35
Duplicate of: https://github.com/primefaces/primereact/pull/2757

**Comment by kusyka911** [comment] 2022-08-31 17:40
> Duplicate of: #2757

As far as I can see PR #2757 will not fix issue with Calendar component. Because hook `useOverlayScrollListener` is not used in the Calendar component.

**Comment by melloware** [comment] 2023-11-20 16:45
Can't reproduce in 10.1.0: https://codesandbox.io/s/primereact-calendar-bug-demo-forked-g52mql?file=/src/demo/index.js

**Closed by melloware** 2023-11-20 16:45 UTC
Labels: Type: Enhancement
