### ISSUE TITLE
TabView: TabPanels have now tabindex="-1" if they are not selected

### ISSUE THREAD

**Issue by gabrielhpugliese-nextmatter** [primefaces/primereact#6136] opened 2024-03-12 12:08 UTC
### Describe the bug

If you try to use the Tab key in the keyboard to cycle through all tabs in a TabView it's not possible. You can see it in the Stackblitz project that is shared in the docs: https://primereact.org/tabview/#basic

### Reproducer

https://stackblitz.com/edit/kphcex?file=src%2FApp.jsx

### PrimeReact version

10.5.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 122

### Steps to reproduce the behavior

1. Go to https://stackblitz.com/edit/kphcex?file=src%2FApp.jsx
2. Open the preview in a new tab
3. Click in a tab
4. Press "Tab" in the keyboard

### Expected behavior

After pressing "Tab" in the keyboard it should cycle to the next tab. If you change the tabindex to 0 in all tabs then it works again.

**Comment by KirilCycle** [comment] 2024-04-19 14:13
@gabrielhpugliese-nextmatter Hello! 'TabView' functions well, on tab pressing it should  not  move focus to next tab element, use arrow keys instead to move between tabs. 
Check this out  - [https://www.w3.org/WAI/ARIA/apg/patterns/tabs/examples/tabs-automatic/](url)

**Comment by melloware** [comment] 2024-04-19 14:24
Agreed with @KirilCycle closing as By Design

**Closed by melloware** 2024-04-19 14:24 UTC
Labels: Resolution: By Design
