### ISSUE TITLE
Component: Datatable - Skeleton

### ISSUE THREAD

**Issue by francmarin98** [primefaces/primereact#3718] opened 2022-11-29 13:18 UTC
### Describe the feature you would like to see added

Hi, how are you? I've come this far because I want to know how difficult it would be to enable the loading prop to behave like this in the datatable?

![image](https://user-images.githubusercontent.com/50973629/204538465-28a76275-3ceb-4b25-a971-c9f0b65fc540.png)

That is to say, a template is shown instead of activating the black cover

**Comment by melloware** [comment] 2022-11-29 13:44
Duplicate of https://github.com/primefaces/primereact/issues/3435

**Closed by melloware** 2022-11-29 13:44 UTC
Labels: Type: New Feature, Status: Discussion, Status: Needs Triage
