### ISSUE TITLE
Calendar: Automatic Date Format Issue in Textbox

### ISSUE THREAD

**Issue by bizwms** [primefaces/primereact#4735] opened 2023-08-04 07:47 UTC
### Describe the bug

There is an issue with the automatic date formatting in the textbox of the Calendar component in PrimeReact v9.6.0. When attempting to manually enter the date into the textbox, the date gets incorrectly formatted. For instance, when trying to enter '08/31/2023', it gets automatically converted to '08/03/2023'. This behavior is also observed on the official demo site.

### Reproducer

https://primereact.org/calendar/

### PrimeReact version

9.6.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Browser(s)

Chrome 115.0.5790.171（Official Build）（64 bit）

### Steps to reproduce the behavior

1. Visit the official demo site at https://primereact.org/calendar/
2. Click on the Calendar component to open the date picker.
3. In the textbox, attempt to manually enter the date '08/31/2023'.

The date is incorrectly formatted to '08/03/2023', reproducing the issue.

### Expected behavior

The Calendar component's textbox should correctly format the manually entered date. When a user tries to input '08/31/2023', it should remain as '08/31/2023' and not be incorrectly changed.

**Comment by melloware** [comment] 2023-08-04 13:33
@bizwms isn't this a duplicate of this issue: https://github.com/primefaces/primereact/issues/4134  ??

**Comment by bizwms** [comment] 2023-08-07 00:16
@melloware  
Is it unsupported to enter dates manually in the calendar component?
#4134 is written as a new feature.
I think it's a bug that I can't enter even though there is a text box.

**Comment by melloware** [comment] 2023-08-07 00:19
I switched it to a bug the user who entered that ticket entered it as a feature which is why it was automatically assigned as a New Feature.

**Closed** 2023-08-07 00:24 UTC
Labels: Resolution: Duplicate

**Comment by bizwms** [comment] 2023-08-07 00:27
Now close my ticket.Due to duplication, my ticket will be closed.
