### ISSUE TITLE
DataTable: reorderIcons don't show

### ISSUE THREAD

**Issue by B-Schmitz** [primefaces/primereact#4538] opened 2023-06-22 14:22 UTC
### Describe the bug

 I want to use custom icons to show ordering, i used these two props, but the icons don't change,
```ts
reorderIndicatorDownIcon={"fa fa-arrow-down-a-z"}
reorderIndicatorUpIcon={"fa fa-arrow-up-a-z"}

```
when i use sortIcon it uses the same icon for asc, desc and without sorting

### PrimeReact version

9.5.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Expected behavior

change the icons

**Comment by melloware** [comment] 2023-06-22 14:29
Duplicate of https://github.com/primefaces/primereact/issues/4347

See the answer there.

**Closed by melloware** 2023-06-22 14:29 UTC
Labels: Status: Needs Triage
