### ISSUE TITLE
DataTable: Horizontal Virtual Scroll in DataTable Displays Unexpected Behavior

### ISSUE THREAD

**Issue by minnnn7716** [primefaces/primereact#7524] opened 2024-12-23 06:29 UTC
### Describe the bug

When using the 'horizontal' or 'both' virtual scroll options in the DataTable component, the display does not behave as expected. The virtual scroll works normally when using only the 'vertical' option, but issues arise when enabling 'horizontal' or 'both'. The problems include one or both of the following scenarios:
```
virtualScrollerOptions={{
  itemSize: [46, 100],
  orientation: 'both',
  scrollWidth: 'auto',
}}
```

Details are described in the Steps to reproduce the behavior section below.
Could you please investigate this issue or provide guidance on how to resolve it? Thank you!

### Reproducer

1. Missing part of the data:  [Stackblitz demo](https://stackblitz.com/edit/fx9c7c3p-brkt7tfe?file=src%2FApp.jsx)
2. Column misalignment: [Stackblitz demo](https://stackblitz.com/edit/fx9c7c3p-uzghdc5f?file=src%2FApp.jsx)

### System Information

```Shell
primereact: 10.8.5
react: 18.3.1
```

### Steps to reproduce the behavior

**1. Missing part of the data:** Some data rows or columns are not displayed.
To simulate a large number of columns, I duplicated the dataset five times with columns: Vin, Year, Brand, and Color. Below is an example of the structure

In the problematic scenario, when scrolling horizontally to the end, some columns are missing while others are displayed. For example, it may only show the second set of columns, while parts of the other sets are missing.Here's a [Stackblitz demo](https://stackblitz.com/edit/fx9c7c3p-brkt7tfe?file=src%2FApp.jsx) demonstrating the issue. Note that this problem's behavior varies based on the window size and may sometimes result in the Column misalignment issue described below.

![Missing data](https://github.com/user-attachments/assets/0f241382-8276-49c6-a553-3339e0271e8b)

---

**2. Column misalignment**: Columns become dislocated or misaligned.
I adjusted all columns and cells to a uniform width of 100px using CSS. While this fixed the issue of missing data, it resulted in column misalignment instead. You can see this behavior in another [Stackblitz demo](https://stackblitz.com/edit/fx9c7c3p-uzghdc5f?file=src%2FApp.jsx).

![Column misalignment](https://github.com/user-attachments/assets/960d13b9-bb24-40a8-861b-366a66bab135)

### Expected behavior

Ｗhen scrolling, all data should be displayed, and the column positions should remain correct.

**Comment by sja-cslab** [comment] 2024-12-23 07:00
In Your first reproducer, just change your property to `virtualScrollerOptions={{ itemSize: 46 }}`.
The reason your columns are missing is because of your itemSize you set. You're to make sure, that set itemSize always fits your items in width and height. For me thhe same applies to the second StackBlitz the itemsSizes aren't those you give to the virtualScroller.

**Comment by minnnn7716** [comment] 2024-12-23 07:35
Hi, sja-cslab

Thank you for your response, and I appreciate your suggestion. Apologies for not adjusting the itemSize parameter to fit the height of my cells earlier. Initially, I only had a single row with a height smaller than 46, and the issue still occurred. Later, I added a "round #" to help identify the column groups, which caused the height of the items to exceed 46.

I have now adjusted the itemSize to 65. However, if I set virtualScrollerOptions={{ itemSize: 65 }} instead of virtualScrollerOptions={{ itemSize: [65, 100] }}, the virtual scrolling only works in the vertical direction. I need it to work in both directions (horizontal and vertical).

**Comment by sja-cslab** [comment] 2024-12-23 07:43
Did you remove orientation and scrollWidth? works fine for me then:

![image](https://github.com/user-attachments/assets/b3a0cf42-a9bc-493e-82bd-7d2371dd5e61)

**Comment by minnnn7716** [comment] 2024-12-23 08:15
Thank you for following up. Yes, I've tried removing both the orientation and scrollWidth parameters. While this does resolve the display issues (showing full data without misalignment), it only enables vertical virtualization.

I verified this using DevTools - the component now correctly virtualizes vertically by rendering only about 15 rows at a time (out of 10,000 total rows), but horizontally it still renders all 29 columns at once. The horizontal virtualization should work similarly to the vertical one, only rendering the visible columns rather than the entire set. This is why I need to maintain the orientation: 'both' setting to achieve virtualization in both directions.

**Comment by sja-cslab** [comment] 2024-12-23 09:53
I see your point my friend but did you notice the following in the docs?

<img width="539" alt="image" src="https://github.com/user-attachments/assets/5e30da63-b972-4632-a85e-83ef3b060edb" />

**Comment by melloware** [comment] 2024-12-23 12:27
Thanks @sja-cslab closing as "By Design"

**Closed by melloware** 2024-12-23 12:27 UTC
Labels: Resolution: By Design

**Comment by minnnn7716** [comment] 2024-12-24 00:57
Hi, sja-cslab,

Thank you for pointing that out, and I sincerely apologize for not noticing that line in the documentation. I saw that the `VirtualScrollerProps` interface allows passing the parameter, so I mistakenly assumed it was supported.

I truly appreciate your response and assistance. I'm sorry for wasting your time due to my oversight. Thank you again for your help!
