### ISSUE TITLE
Dialog: Scroll disappear

### ISSUE THREAD

**Issue by wolnynick** [primefaces/primereact#3465] opened 2022-10-11 08:10 UTC
### Describe the bug

After checking the docs, I found the bug with dialog:

1. Go to: https://www.primefaces.org/primereact/dialog/

2. Open 'Maximizable' Modal

![image](https://user-images.githubusercontent.com/40297940/195029036-5c614b94-ce14-4f12-889d-9089521a583e.png)

3. Click this button: 

![image](https://user-images.githubusercontent.com/40297940/195029426-dd24373a-9cd1-4af9-9f62-949b7cf4a3dc.png)

4. Click one of these:

![image](https://user-images.githubusercontent.com/40297940/195029730-d1bb5f70-4050-478e-a59f-6626edba36aa.png)

5. And where is the main scrollbar?

![image](https://user-images.githubusercontent.com/40297940/195034961-638cc543-c0af-4a91-a0f7-77f1100a5755.png)

### PrimeReact version

8.6.1

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment] 2022-10-11 11:34
Duplicate of https://github.com/primefaces/primereact/issues/3432

Already fixed!

**Closed** 2022-10-11 11:34 UTC
Labels: Resolution: Duplicate
