### ISSUE TITLE
Datatable: Typescript support by using generic types

### ISSUE THREAD

**Issue by diamanthaxhimusa** [primefaces/primereact#3318] opened 2022-09-13 22:47 UTC
### Describe the feature you would like to see added

Typescript support feels limited on Datatable. There are many `any` types which can be eliminated by using generic types.
The problem I have is that I have to specify the type of the data I am passing to the `value` prop on Datatable. I eliminated this problem as shown below.

```
export interface DataTableProps<T> extends Omit<React.DetailedHTMLProps<React.InputHTMLAttributes<HTMLDivElement>, HTMLDivElement>, 'size' | 'onContextMenu' | 'ref'> {
    id?: string;
    value?: T[];
    ....
    rowClassName?(data: T, options: DataTableRowClassNameOptions): object | string;
    ....
}
```

and then I used it as

```
type User = {
  id: number;
  name: string;
}
<DataTable<User>
  values={users}
  rowClassName={(row) => row.id+'-'+row.name}
/>
```

**Comment by melloware** [comment] 2022-09-13 22:58
Duplicate of #2523 please subscribe to that issue

**Closed** 2022-09-13 23:00 UTC
Labels: Resolution: Duplicate, TypeScript
