### ISSUE TITLE
MultiSelect - breaking when options is empty array

### ISSUE THREAD

**Issue by yamshrishi** [primefaces/primereact#2496] opened 2021-12-06 12:23 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
I have a MultiSelect component being generated depending on a switch case. The options values are being generated programmatically in useEffect. 
However, the Multiselect is breaking for the generated options. It works fine if I provide a hardcoded value. The same generated values are working when given to a Dropdown component.

Error message: TypeError: Cannot read properties of null (reading 'length')
    at MultiSelect.isAllSelected

**Expected behavior**
Expecting Multiselect to *not* break for programmatically generated options set.

Help...

* **React version:**
17.0.2

* **PrimeReact version:**
6.5.1

**Comment by melloware** [comment] 2021-12-06 12:26
Please provide a Code Sandbox reproducer so we can debug.

**Comment by yamshrishi** [comment] 2021-12-06 13:03
I'm unable to reproduce it in the code sandbox... any heads up on how I can debug this on my side..

**Comment by melloware** [comment] 2021-12-06 13:35
OK two things.

1. Since you can't reproduce with Code Sandbox please close this ticket.

2. What I normally do is start stripping one thing out at a time until I narrow down the problem with my code on what is causing the issue.

**Comment by yamshrishi** [comment] 2021-12-06 16:31
Closing because I'm unable to reproduce the issue in sandbox.

**Comment by yamshrishi** [comment] 2021-12-06 16:56
Reopening this issue. Able to reproduce the issue in sandbox : https://codesandbox.io/s/primereact-test-forked-0rbtt?file=/src/index.js

Choosing the first option will show the error and choosing the second option will show how it should look like but with multiselect instead of dropdown.

**Comment by melloware** [comment] 2021-12-07 00:04
Thanks for the reproducer. Let me take a look!

**Closed** 2021-12-10 07:23 UTC
