### ISSUE TITLE
ContextMenu trigger on IOS touch events

### ISSUE THREAD

**Issue by chiralsystems** [primefaces/primereact#2056] opened 2021-05-20 17:57 UTC
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

Request for ContextMenu triggering on IOS / Mobile touch events so that DataTable rows can be used to access context menu as per mouse right click.

**Comment by melloware** [comment] 2021-11-08 23:58
Duplicate of https://github.com/primefaces/primereact/issues/2029 please close this ticket

**Closed** 2021-12-09 14:28 UTC
