### ISSUE TITLE
Autocomplete - List Key

### ISSUE THREAD

**Issue by Nandovga** [primefaces/primereact#6426] opened 2024-04-19 13:19 UTC
### Describe the bug

When adding a component to its basic autocomplete form, the console is returning a unique key error.

`Warning: Each child in a list should have a unique "key" prop.`

Exemplo: 

```
<AutoComplete completeMethod={() => setData([
    { id: 1, label: "Teste" },
    { id: 2, label: "Teste2" },
])}
              field="label"
              id="id"
              suggestions={data}
              value={value}
              onChange={(e) => setValue(e.value)}/>
```

### Reproducer

10.6.3

### PrimeReact version

10.6.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by melloware** [comment] 2024-04-19 13:45
Already fixed with this PR: https://github.com/primefaces/primereact/pull/6365

Duplicate of #6277 and #6317

**Closed by melloware** 2024-04-19 13:45 UTC
Labels: Status: Needs Triage

**Comment by ManuelCarrascal** [comment] 2024-04-21 17:26
I need help, I don't know what's wrong, I get the same problem with the password.
![image](https://github.com/primefaces/primereact/assets/54221416/63df373a-31c1-424d-83a8-cf7ad61e0046)
![image](https://github.com/primefaces/primereact/assets/54221416/d9c96917-2403-4265-8834-8a5ea45770c7)
I don't usually use primereact and I wanted to try it and it is giving that problem in the autocomplete

**Comment by melloware** [comment] 2024-04-21 17:44
@ManuelCarrascal this is fixed for next release. You will have to wait for the fix.

**Comment by ManuelCarrascal** [comment] 2024-04-21 17:46
Ok brother @melloware how often are you releasing a new release?

**Comment by melloware** [comment] 2024-04-21 17:49
PrimeTek tries to release about every 2 weeks.

**Comment by ManuelCarrascal** [comment] 2024-04-21 17:53
I understand brother, thank you very much, you can close this now.
