### ISSUE TITLE
Dropdown: element loses focus if option is selected with keyboard

### ISSUE THREAD

**Issue by manuel-bitcraft** [primefaces/primereact#7390] opened 2024-11-05 01:26 UTC
### Describe the bug

If you select a dropdown option with the mouse: the element get assigned the class "p-inputwrapper-focus" and the attibute "data-p-focus" is true.

If you select a dropdown option with the keyboard and press enter: the element drop the class "p-inputwrapper-focus" and the attibute "data-p-focus" is false

### Reproducer

https://stackblitz.com/run?file=src%2FApp.jsx

### System Information

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 13th Gen Intel(R) Core(TM) i7-1355U
    Memory: 39.19 GB / 63.64 GB
  Binaries:
    Node: 18.20.4 - C:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (128.0.2739.67)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    primereact: ^10.8.4 => 10.8.4
    react: ^18 => 18.2.0
    tailwindcss: ^3.3.0 => 3.4.1
```

**Comment by melloware** [comment] 2024-11-05 12:34
Duplicate of : https://github.com/primefaces/primereact/issues/6873

**Closed** 2024-11-25 13:18 UTC
Labels: Resolution: Duplicate

**Comment by edo-trotta** [comment] 2025-04-29 10:07
This is still an issue on 10.9.2, plus, the Select component doesn't have this bug.
