### ISSUE TITLE
DataTable with VirtualScroller: multi selection bug

### ISSUE THREAD

**Issue by mtsh1000** [primefaces/primereact#3860] opened 2023-01-01 16:34 UTC
### Describe the bug

When DataTable is set with VirtualScroller rows selection is buggy i.e. using checkbox selection, select all (header) selects only rendered rows. Selecting large range of rows with shift key and scrolling back up will cause js errors.

### PrimeReact version

8.7.3

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment] 2023-01-02 20:07
Duplicate of https://github.com/primefaces/primereact/issues/3053

**Closed by melloware** 2023-01-02 20:07 UTC
Labels: Resolution: Duplicate

**Comment by melloware** [comment] 2023-01-02 20:10
Can you check https://github.com/primefaces/primereact/issues/3804 and see if it is the same issue if not please provide a runnable Reproducer.

**Comment by mtsh1000** [comment] 2023-01-04 15:31
> Can you check #3804 and see if it is the same issue if not please provide a runnable Reproducer.

Well the actual bugs reported are slightly different but i assume the source of them is the same - not rendered rows are not getting selected properly. Bugs that I mentioned can be reproduced in #3804 reproducer: 
https://codesandbox.io/s/prime-react-datatable-virtualscroll-row-selection-error-oxi4vw?file=/src/App.tsx

'select all' not selecting all: 
![chrome-capture-2023-0-4](https://user-images.githubusercontent.com/32628738/210589897-037551c3-55fe-454b-bb90-2f9eeea9afb2.gif)

selecting with shift errors:
![chrome-capture-2023-0-4 (1)](https://user-images.githubusercontent.com/32628738/210590422-c66862a7-166c-44ab-95d3-85fab8fb8575.gif)

**Comment by melloware** [comment] 2023-01-04 15:42
OK once 8.7.4 is released we will have you try again and we can re-open this ticket if its still an issue!  Just let me know once 8.7.4 is out there.

**Comment by mtsh1000** [comment] 2023-03-02 05:51
The bug is still present in 9.2.0
