### ISSUE TITLE
DataTable: Warning thrown when loading is true

### ISSUE THREAD

**Issue by VytautasLozickas** [primefaces/primereact#6863] opened 2024-07-10 10:53 UTC
### Describe the bug

Setting prop `loading={true}` on the **DataTable** component throws a warning:
```
Warning: Received `false` for a non-boolean attribute `unstyled`.

If you want to write it to the DOM, pass a string instead: unstyled="false" or unstyled={value.toString()}.

If you used to conditionally omit it with unstyled={condition && value}, pass unstyled={condition ? value : undefined} instead.
```

Investigating the call stack it looks like the warning originates from `SpinnerIcon` component.

### Reproducer

https://stackblitz.com/edit/vitejs-vite-okgbsb?file=src%2FApp.tsx

### PrimeReact version

10.7.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Tested on Safari, Chrome - probably irrelevant

### Steps to reproduce the behavior

1. Add `<DataTable/>` component in your app;
2. Set `loading` prop of the `DataTable` component to `true`;
3. Observe the console for warnings.

### Expected behavior

No warning is expected when using `loading={true}` on the `DataTable` component.

**Comment by melloware** [comment] 2024-07-10 11:29
Duplicate of https://github.com/primefaces/primereact/issues/6823 fixed for 10.7.1

**Closed** 2024-07-10 11:29 UTC
Labels: Resolution: Duplicate
