### ISSUE TITLE
Component: ConfirmationDialog

### ISSUE THREAD

**Issue by raf1hh** [primefaces/primereact#4420] opened 2023-05-19 01:32 UTC
### Describe the bug

Header property does not work anymore in 9.4.0. Works fine in 9.2.3.

Issue is present on the official CustomDialog page:
[primereact](https://primereact.org/confirmdialog/)

### PrimeReact version

9.4.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by rafalwojdowski** [comment] 2023-05-19 05:50
It's a duplicate of https://github.com/primefaces/primereact/issues/4397.

**Comment by melloware** [comment] 2023-05-19 11:41
Closing as duplicate.

**Closed** 2023-05-19 11:41 UTC
Labels: Resolution: Duplicate
