### ISSUE TITLE
virtual scrolling with row expand flickering issue

### ISSUE THREAD

**Issue by tewabet** [primefaces/primereact#4709] opened 2023-08-01 00:49 UTC
### Describe the bug

When using virtual scrolling with row expand, the entire grid starts flickering.
when expanding the last row, the data is hidden below the visible area. To view the expandable area, one needs to scroll down to bring in to view. Using manually scrolling to see the text, then the entire grid starts flickering.

### PrimeReact version

9.6.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment] 2023-08-01 00:56
Duplicate of #2584

**Closed** 2023-08-01 00:58 UTC
Labels: Resolution: Duplicate
