### ISSUE TITLE
Calendar - Doesn't work on single click 

### ISSUE THREAD

**Issue by vishalv26** [primefaces/primereact#4699] opened 2023-07-29 07:48 UTC
### Describe the bug

HI,

Going through this link
https://primereact.org/calendar/

It doesn't select date on the first click. It selects on 2nd click. This was not the issue with v8 (https://www.primefaces.org/primereact-v8/calendar/)

### Reproducer

https://primereact.org/calendar/

### PrimeReact version

Latest

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome Latest

### Steps to reproduce the behavior

Just click on the component and it doesn't work at first

### Expected behavior

It should select the date and close the calendar

**Comment by melloware** [comment] 2023-07-29 11:22
Duplicate of https://github.com/primefaces/primereact/issues/4568

**Closed** 2023-07-29 11:23 UTC
Labels: Resolution: Duplicate
