### ISSUE TITLE
Virtual scrolling with row expandable flickering issue

### ISSUE THREAD

**Issue by tewabet** [primefaces/primereact#4729] opened 2023-08-03 01:47 UTC
### Describe the bug

Virtual scrolling with row expand not working properly. In dataGrid detail template when expanding the last row, the data is hidden below the visible area. To view the expandable area, one needs to scroll down to bring in to view. Using manually scrolling to see the text, then the entire grid starts flickering.

### PrimeReact version

9.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment] 2023-08-03 10:03
Duplicate of #2854

**Comment by melloware** [comment] 2023-08-03 11:59
@tewabet why do you keep opening this issue?  I keep closing it as a duplicate please subscribe to ticket #2854 ???

**Closed** 2023-09-11 18:53 UTC
Labels: Resolution: Duplicate
