### ISSUE TITLE
Datatable OnValueChange

### ISSUE THREAD

**Issue by bits1309** [primefaces/primereact#3324] opened 2022-09-15 06:49 UTC
### Describe the bug

The onValueChange doesnt get called when we are filtering data using the global search box. 
The same works fine if we filter individual columns. 
Ideally, onValueChange should be called on all instances where filtering is happening because then we are not able to implement a few functionalities which rely on filtered data.

### PrimeReact version

8.5.0

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Add the below property to your <Datatable> component.
onValueChange={filteredData => {console.log('filter changed', filteredData)}} 

2. try filtering the data from the individual filter. It properly logs the filtered data.
3. Try filtering via global search box. It doesn't log the filtered data properly.

**Comment by melloware** [comment] 2022-09-15 11:21
Duplicate of #1396

**Closed by melloware** 2022-09-15 11:21 UTC
Labels: Resolution: Duplicate
