### ISSUE TITLE
TabPanel: properties typings are wrong

### ISSUE THREAD

**Issue by kazamov** [primefaces/primereact#4279] opened 2023-04-24 11:33 UTC
### Describe the bug

The typings for the TabPanel component properties are wrong: although the "prevButton", "nextButton" and "closeIcon" can be "undefined" they are required. So, I need to explicitly set those properties to "undefined" in the existing code. It would help if you made those properties optional like all others.

### PrimeReact version

9.3.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Create a TS project.
2. Use TabView and nest the TabPanel component.
3. TabPanel component will require the "prevButton", "nextButton" and "closeIcon" properties.

### Expected behavior

The "prevButton", "nextButton" and "closeIcon" should be optional.

**Comment by melloware** [comment] 2023-04-24 11:53
Duplicate of https://github.com/primefaces/primereact/issues/4261

**Closed by melloware** 2023-04-24 11:53 UTC
Labels: Resolution: Duplicate
