### ISSUE TITLE
Slider error on mobile (touch) devices

### ISSUE THREAD

**Issue by enrilos** [primefaces/primereact#4951] opened 2023-09-24 16:43 UTC
### Describe the bug

When using the Slider component on mobile devices, the end of the dragging itself on a handle causes an error to be thrown.

- On Chrome - `Cannot read properties of undefined (reading 'pageX')`
- On Firefox - `event.touches[0] is undefined`

The bug is also present in the docs - https://primereact.org/slider/

Despite the fact that a relevant issue is closed - #4906, the problem still persists.

### Reproducer

Can be reproduced by switching to mobile/responsive view in the DevTools

### PrimeReact version

9.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Have tested on Chrome 117.0.5938.92 and Firefox 117.0.5938.92

**Comment by melloware** [comment] 2023-09-24 17:13
Duplicate of #4906 already fixed

**Closed** 2023-09-24 17:13 UTC
Labels: Resolution: Duplicate

**Comment by enrilos** [comment] 2023-09-24 17:54
Did you reproduce it?
I am aware that this issue is a duplicate and have pointed it out.
However, **the problem still persists**.

**Comment by melloware** [comment] 2023-09-24 19:15
It has not been released yet. Always check the milestone tag on the right of the ticket to see the version it's fixed in. If you run the showcase in master you will see it's already fixed
