### ISSUE TITLE
DATA TABLE WITH COMBINING  FEATURE (VIRTUAL SCROLL , COL RESIZING AND FROZEN COLUMN ) NOT WORKING PROPERLY 

### ISSUE THREAD

**Issue by monishanagarjun** [primefaces/primereact#3704] opened 2022-11-25 06:41 UTC
### Describe the bug

I face a issue when we have frozen column given to virtual scroll lazy loading loading data table .. attached screenshot of the error for your reference.. please help us resolve it
![tableIssue](https://user-images.githubusercontent.com/34094368/203914104-960fd8a1-17c8-46b3-bad7-315d474cc94c.PNG)
![tableIssue](https://user-images.githubusercontent.com/34094368/203915935-6fdab6e4-3a91-4a32-966a-32eea0cf911a.PNG)

### Reproducer

https://codesandbox.io/s/happy-microservice-lf0pe0?file=/src/demo/DataTableVirtualScrollDemo.tsx

### PrimeReact version

8.0.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Next.js

### Browser(s)

Chrome

### Steps to reproduce the behavior

 <DataTable
          value={virtualCars}
          resizableColumns
          showGridlines
          removableSort
          responsiveLayout="scroll"
          columnResizeMode="fit"
          scrollable
          scrollHeight="400px"
          virtualScrollerOptions={{
            lazy: true,
            onLazyLoad: loadCarsLazy,
            itemSize: 46,
            delay: 200,
            showLoader: true,
            loading: lazyLoading,
            loadingTemplate
          }}
        >
          <Column
            frozen
            sortable
            field="id"
            header="Id"
            style={{ minWidth: "200px" }}
          ></Column>
</Datatable>

https://codesandbox.io/s/happy-microservice-lf0pe0?file=/src/demo/DataTableVirtualScrollDemo.tsx:2089-2757
![tableIssue](https://user-images.githubusercontent.com/34094368/203916386-06d797f4-ec1a-44a5-b1c8-efc7428f5252.PNG)

### Expected behavior

https://www.primefaces.org/primereact/datatable/virtualscroll/ -- Lazy Loading from a Remote Datasource 

Overview – Main Table requires these functionality 
•	Dynamic Column Width /Column Resizing
•	Lazy Loading Virtual scroll on Vertical scroll- [Lazy Loading from a Remote Data source]
•	Sorting – removal default sort
•	Check box and Asset , Status Frozen Column
•	Responsive to accommodate in mobile view 
•	Horizontal scroll to dynamic table height
•	Column to set auto width to occupy whole table for less columns
•	Check box Multi selection 
•	Row Expansion
•	Striped rows
•	State Column to handle varies status of Asset
•	Crud operation to edit , copy & delete

expected like Frozen Columns with skeleton loading in columns

**Comment by melloware** [comment] 2022-11-25 12:53
Your code sandbox will not run for me: 

![image](https://user-images.githubusercontent.com/4399574/203989988-f964b74d-f1fc-4553-979e-952ac6315187.png)

**Comment by melloware** [comment] 2022-11-25 13:18
Duplicate of: https://github.com/primefaces/primereact/issues/3415

**Closed by melloware** 2022-11-25 13:18 UTC
Labels: Resolution: Needs More Information

**Comment by monishanagarjun** [comment] 2022-11-26 13:45
Hi ,
Please let me know your right available time to have a lively connect and
resolve my issue ..
My datatable doesn't work when I have frozen column with virtual scroll
skeleton lazy combined.
Your assistance to me is highly appreciated that you could help me complete
my critical pending development..

**Comment by melloware** [comment] 2022-11-26 17:06
@monishanagarjun I am an open source volunteer so you won't get that kind of support from me.  If you need pro support I suggest you read this: https://primefaces.org/primereact/support/

**Comment by monishanagarjun** [comment] 2022-11-27 09:53
https://www.primefaces.org/primereact/datatable/virtualscroll/ -- Lazy Loading from a Remote Datasource gets error when we have a frozen column . How to resolve the error , Please help ? 
![tableIssue](https://user-images.githubusercontent.com/34094368/204129062-dab1f377-1050-40de-819d-bc483a1e7d79.PNG)

```
  <DataTable value={virtualCars} scrollable scrollHeight="400px" virtualScrollerOptions={{ lazy: true, onLazyLoad: loadCarsLazy, itemSize: 46, delay: 200, showLoader: true, loading: lazyLoading, loadingTemplate }}>
                            <Column key="multi-selector" frozen selectionMode="multiple"  />
                             <Column frozen field="code" header="Code"></Column>
                          </DataTable>
```
