### ISSUE TITLE
ToolTip Component: The issue is that the Tooltip is not getting killed

### ISSUE THREAD

**Issue by Ishaan28malik** [primefaces/primereact#4736] opened 2023-08-04 08:01 UTC
### Describe the bug

# When we are hovering out of the component still the `ToolTip` label exists.

## Here's an [Example](https://codesandbox.io/s/5puskp?file=/src/App.js)

* For any position it's the same I checked it for `Bottom` and `Right`

![Screenshot from 2023-08-04 13-25-45](https://github.com/primefaces/primereact/assets/27343592/ef5f002c-1d18-4fbe-baee-a186c1e41c27)

![Screenshot from 2023-08-04 13-24-04](https://github.com/primefaces/primereact/assets/27343592/9c75872e-8ea4-4af6-b0b9-c77ffa74ed2e)

### PrimeReact version

9.6.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome , Safari , Firefox , Brave

### Steps to reproduce the behavior

Go to the link below. You can replicate this as I mentioned in the screenshot.
https://codesandbox.io/s/5puskp?file=/src/App.js

##  Tooltip should get removed when we exit the mouse from the component .

**Comment by Ishaan28malik** [comment] 2023-08-04 08:04
Anyone ?
@habubey @rburgst @cagataycivici @ulasturann

**Comment by habubey** [comment] 2023-08-04 08:06
Thanks for reporting, we will check and get back to you! @Ishaan28malik

**Comment by melloware** [comment] 2023-08-04 13:30
Duplicate of https://github.com/primefaces/primereact/issues/4604 already fixed for 10.0.0

**Closed by melloware** 2023-08-04 13:30 UTC
Labels: Resolution: Duplicate
