### ISSUE TITLE
Component: Calendar

### ISSUE THREAD

**Issue by leonelgoncalves** [primefaces/primereact#4690] opened 2023-07-27 09:06 UTC
### Describe the bug

All calendars require double click to select a date. This goes against all UX principles, on the previous version it was not like that.

### PrimeReact version

9.6.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Use a calendar
2. Select a date
3. you need to click twice

### Expected behavior

You are able to select a date with a single click

**Comment by EmirBoyaci** [comment] 2023-07-27 10:55
Already fixed but not yet released. Dupe of https://github.com/primefaces/primereact/issues/4568

**Comment by melloware** [comment] 2023-07-27 11:03
Duplicate of https://github.com/primefaces/primereact/issues/4568

**Closed by melloware** 2023-07-27 11:03 UTC
Labels: Resolution: Duplicate
