### ISSUE TITLE
Draggable functionality on popover

### ISSUE THREAD

**Issue by hdolas** [primefaces/primereact#2325] opened 2021-09-27 07:18 UTC
Hello,

Can you please provide draggable functionality on popover? the same way we have for modal.
after opening a popover on a button, user should be able to drag it all over the screen.

Thanks in advance

**Comment by mertsincan** [comment] 2021-11-06 18:19
Hello,

Which components do you want? I'll work on a new draggable API. I can try it on some components according to your feedback.

**Comment by melloware** [comment] 2022-04-22 14:09
Duplicate of: https://github.com/primefaces/primereact/issues/1361

**Closed by melloware** 2022-04-22 14:09 UTC
Labels: new feature, incomplete
