### ISSUE TITLE
DataTable: Cell editing with Dropdown doesn't work

### ISSUE THREAD

**Issue by igo** [primefaces/primereact#3079] opened 2022-07-18 17:35 UTC
### Describe the bug

Using Dropdown and DataTable with cell editing seems to be not working properly. Changing value in Dropdown doesn't change the value, however changing value using InputText works properly. 

### Reproducer

https://codesandbox.io/s/beautiful-boyd-y1tiji

### PrimeReact version

8.3.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment] 2022-07-18 18:04
Duplicate of https://github.com/primefaces/primereact/issues/2666

**Closed by melloware** 2022-07-18 18:04 UTC
Labels: defect, :bangbang: needs-triage
