### ISSUE TITLE
DataTable filter row is not shown if headerColumnGroup prop is provided

### ISSUE THREAD

**Issue by mvarakin** [primefaces/primereact#4411] opened 2023-05-17 07:45 UTC
### Describe the bug

Seems that combination of filterDisplay='row' and headerColumnGroup={myColumnGroup} is not working

If filterDisplay set to 'menu' filter buttons are rendered 

### Reproducer

https://stackblitz.com/edit/react-szwyss-osqzwu

### PrimeReact version

9.2.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment] 2023-05-17 11:27
@mvarakin can you edit my Stack Blitz to show the issue please?

https://stackblitz.com/edit/react-szwyss

**Comment by mvarakin** [comment] 2023-05-17 12:26
> @mvarakin can you edit my Stack Blitz to show the issue please?
> 
> https://stackblitz.com/edit/react-szwyss

Sure, here it is https://react-szwyss-unedvd.stackblitz.io

**Comment by melloware** [comment] 2023-05-17 12:42
your stackblitz is not starting for me and also it looks like that is the runnable version can you please send a link with code like mine?

**Comment by mvarakin** [comment] 2023-05-17 12:54
> unedvd.stackblitz.io

here it is https://stackblitz.com/edit/react-szwyss-unedvd

**Comment by melloware** [comment] 2023-05-17 13:37
Thanks!

**Comment by melloware** [comment] 2023-05-17 13:38
I am not seeing it work with filterDisplay Menu or Row?  Doesn't look like it works at all in 9.4.0?

**Comment by melloware** [comment] 2023-05-17 13:49
well it displays the filter icon but when i click on it its blank and blows up with..

![image](https://github.com/primefaces/primereact/assets/4399574/d59635e1-41dc-4750-aab3-5515a92066b8)

**Comment by melloware** [comment] 2023-05-28 13:24
I think this is a duplicate of: https://github.com/primefaces/primereact/issues/2482

**Closed** 2023-05-28 13:25 UTC
Labels: Type: Enhancement
