### ISSUE TITLE
TreeSelect: Filtering does not select the nodes correctly

### ISSUE THREAD

**Issue by gkolev-blubito** [primefaces/primereact#3762] opened 2022-12-08 16:09 UTC
### Describe the bug

Hi,

During my work with TreeFilter + Checkbox selection + filtering of the tree I landed on a bug.

It all works fine until I try to filter the tree for a very specific (unique) value and select it.
Instead of partially selecting all the parents, all the tree nodes are completely selected, that makes the filtering unusable.
When clearing up the filter menu the tree selection gets broken - not just the selected node is displayed as "checked", but all the parents, that have to be actually only "partialChecked".

Expected: to have only one option fully selected.
Actual: the filtered tree nodes are fully selected.

Normal behavior when the filter menu is not being used:

![Screen Shot 2022-12-08 at 17 52 14 PM](https://user-images.githubusercontent.com/75522376/206498366-1009ba89-115c-4037-b517-06c83cfcb6e4.png)

Behavior when the filter menu is being used (broken selection):

![Screen Shot 2022-12-08 at 17 52 24 PM](https://user-images.githubusercontent.com/75522376/206498503-ae8d5c0c-7ba2-4d80-9118-27669dd237a8.png)
![Screen Shot 2022-12-08 at 17 52 33 PM](https://user-images.githubusercontent.com/75522376/206498509-579452c7-d8f1-4c89-9a1c-45aefd77ea91.png)

### Reproducer

https://codesandbox.io/s/funny-mountain-ylz0s0?file=/src/demo/TreeSelectDemo.js

### PrimeReact version

8.7.3

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

All

### Steps to reproduce the behavior

1. Open the TreeFIlter menu
2. Search for a child node by using the filter
3. Clear up the filter menu
4. Expand the tree and verify the tree selection

### Expected behavior

To have only one option fully selected (the actually selected one, not all the parents up the tree).

**Comment by melloware** [comment] 2022-12-08 19:23
Related to: https://github.com/primefaces/primereact/issues/3131

**Comment by gkolev-blubito** [comment] 2022-12-11 12:58
Hey @melloware, may I ask what the current average bug fixing time for similar issues is?

I see that there're some bug issues that are opened 1-2 years ago, but have never been closed, so just want to know if this one is something that PrimeReact plan to rework soon or the users may have a look for an alternative component from different library?
For me, the company I work for and the projects we work on, the TreeSelect (and also bunch of other PrimeReact components) are part of the core UI for most of the web apps. When using a huge tree with the TreeSelect the filter feature is a time saver. Recently we moved away from **the react-dropdown-tree-select** and I hope we can stick to the PrimeReact library and keep the consistency.

I'm available if you need some more information about the issue.

I would really appreciate any kind of an answer.

Wish you all the best and happy holidays!

**Comment by melloware** [comment] 2022-12-11 13:05
@gkolev-blubito I don't work for PrimeTek I am just an open source volunteer.  So a lot of the things I fix is because I have the problem myself or need it for one of my clients.    PR's are of course welcome by the community and will be reviewed by the team!

If you really need something fixed by PrimeTek you can financially support it with PRO support: https://primefaces.org/primereact/support/

If you want to help me maybe you and I can analyze this one together and maybe find a fix.    I didn't dive into this one yet but let me see if I can debug where the issue is first.

**Comment by gkolev-blubito** [comment] 2022-12-11 13:08
I will give it a try also and will let the community here know, if I have some news about this exact issue.
Thanks for the fast reply! 
Cu around.

**Comment by melloware** [comment] 2022-12-11 16:37
I took a quick look, this one is quite tricky.

**Comment by thejus557** [comment] 2023-07-31 08:23
@melloware  will you take a look at the above fix please.

**Closed** 2023-07-31 20:12 UTC
Labels: Type: Bug
