### ISSUE TITLE
Menu rerenders components in 6.3.1

### ISSUE THREAD

**Issue by master117** [primefaces/primereact#1998] opened 2021-04-30 09:58 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
6.3.1 (Buggy) https://codesandbox.io/s/primereact-test-forked-ed5g4?file=/src/index.js

6.0.1 (Works) https://codesandbox.io/s/primereact-test-forked-vw1up?file=/src/index.js

**Current behavior**
Whenever changes happen, for example when selecting or clicking something. Components in a Menu are recreated. Which means their state is lost.

**Expected behavior**
Components should persevere as in 6.0.1

**Minimal reproduction of the problem with instructions**
Step 1. Click Show
Step 2. Click Link
Step 3. Click on the dialog text for example

6.0.1 => Dialog stays, no issues.
6.3.1 => Dialog disappears as Confirmlink component is recreated and showConfirm useState is lost. => BUG

* **PrimeReact version:**
6.3.1
6.0.1

**Comment by mertsincan** [comment] 2021-05-01 13:54
Hi @master117,

Could you please try appendTo="self" on dialog? Also, I think you can use confirmDialog component for a confirmation message.

Default behavior; When you click on a menuitem, the panel of Menu will close. But, since you are using the template option, you can control this behavior. However the panel is listening to some events connected to the document to close itself. For example the click event. As you know, now all overlay and modal components append to the body by default. When you click dialog, the panel closes due to a click event in the document. Then, the close event of Dialog is called. Therefore, this is expected behavior. You can observe the behavior of the menu in both codesandbox examples. 

Also, my suggestion; you can move Dialog into App and call props.options.onClick(event) in onClick of ConfirmLink component.
```

interface MenuItemOptions {
    onClick(event: React.SyntheticEvent): void;
    className: string;
    labelClassName: string;
    iconClassName: string;
    element: React.ReactNode;
    props: any;
    [key: string]: any;
}

type MenuItemTemplateType = React.ReactNode | ((item: MenuItem, options: MenuItemOptions) => React.ReactNode);

export interface MenuItem {
    ...
    template?: MenuItemTemplateType;
}
```

Best Regards,

**Closed by mertsincan** 2021-05-01 13:54 UTC
