### ISSUE TITLE
OverlayPanel: AppendTo not functioning

### ISSUE THREAD

**Issue by jnoren1** [primefaces/primereact#4922] opened 2023-09-16 05:15 UTC
### Describe the bug

The OverlayPanel is always appending to the document.body regardless of the appendTo value.

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-x8t4fl?file=/src/App.js

### PrimeReact version

9.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Steps to reproduce the behavior

1. any value placed in the appendTo field appears to be ignored.

### Expected behavior

I would expect the OverlayPanel to be a child or neighbor of the specified appendTo HTML element.  Honestly I am not sure which is intended, but it is not doing either.

**Comment by melloware** [comment] 2023-09-16 11:51
This is weird I am testing locally with the showcase your exact code and its working I can see the dialog appended into your `<div>`.  But in your code sandbox I can see it is definitely not.  Now a different is CRA vs Next but from looking at the code I don't see any differences.

**Comment by melloware** [comment] 2023-09-16 11:54
I have marked this for myself to re-test when 10.0.0 is released as this may be "accidentally" already fixed.

**Comment by ubau** [comment] 2023-09-18 07:54
As a workaround you can add some fake className to target div (e.g. `<div className="my-div-123" ref={test} />`) then OverlayPanel will be appended correctly.

**Comment by ubau** [comment] 2023-09-18 08:11
As a workaround you can add some id or  className to the target `div` :
```jsx
<div id="my-id" ref={test} />
```
or
```jsx
<div className="my-div-123" ref={test} />
```
then OverlayPanel will be appended correctly.

**Comment by jnoren1** [comment] 2023-09-18 13:05
That does work. Thank you. It would never have occurred to me to add an "id". I can work with that.  Note: In my test, I could not get the className version of your workaround to work.  Id version worked with no issue.

[ClassName Workaround](https://codesandbox.io/s/primereact-demo-forked-h43lwf)

**Comment by ubau** [comment] 2023-09-18 13:56
Hmm, looks like some codesandbox quirks, in my local server it works even without `id` or `className`.

**Comment by j-Nimble** [comment] 2023-09-19 00:30
That is very odd. On my local, it ONLY worked with ID. Regular classNames did not work but honestly I did not try with the dashes in the class name when I discovered that working in the sandbox as that seems like bizarre nonsense.

**Comment by jnoren1** [comment] 2023-09-19 00:38
That is very odd. On my local, it ONLY worked with ID. Regular classNames did not work but honestly I did not try with the dashes in the class name when I discovered that working in the sandbox as that seems like bizarre nonsense.

(My apologies for the double post, i didn't realize my phone was logged into an old account.)

**Comment by melloware** [comment] 2023-09-19 10:31
No problem I want to check this in the sandbox after 10.0.0 is released.

**Comment by melloware** [comment] 2023-09-28 19:56
Iam going to close I think this is Sandbox weirdness as I can't reproduce it anywhere but the sandbox. Will re-open if you find you can reproduce it reliably!

**Closed by melloware** 2023-09-28 19:56 UTC
Labels: Type: Bug, Status: In Progress
