### ISSUE TITLE
Incorrect year display in Calendar after navigating to next year

### ISSUE THREAD

**Issue by vnedevaa** [primefaces/primereact#5533] opened 2023-12-06 07:39 UTC
### Describe the bug

I am using PrimeReact version 10.1.1 and have implemented the Calendar component. I have configured the calendar to open at the current date. However, the current behaviour differs from the default PrimeReact behaviour, which typically renders the state it was in before.

Steps to Reproduce:

1. Open the calendar.
2. Navigate through the months and go to the next year.
3. Close the calendar.
4. Open the calendar again.

Expected Behaviour:
Upon reopening the calendar, I expect to see the current month and the current year.

Actual Behavior:
However, what I observe is that the calendar displays the previous year, but with the correct dates for the current month of the current year.

<img width="383" alt="Screenshot 2023-12-05 at 16 54 53" src="https://github.com/primefaces/primereact/assets/107926538/9e2184e0-265e-4e20-9d7b-ceab4529554c">
<img width="336" alt="Screenshot 2023-12-05 at 16 55 09" src="https://github.com/primefaces/primereact/assets/107926538/78756c7d-8157-4185-a89d-5e3d52027a55">

### Reproducer

https://codesandbox.io/p/sandbox/primereact-demo-forked-ygt9ly?file=%2Fsrc%2FApp.js

### PrimeReact version

10.1.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Open the calendar.
2. Navigate through the months and go to the next year.
3. Close the calendar.
4. Open the calendar again.

### Expected behavior

Upon reopening the calendar, I expect to see the current month and the current year.

**Comment by melloware** [comment] 2023-12-06 12:52
Fixed your sandbox: https://codesandbox.io/p/sandbox/primereact-demo-forked-44vqcv?file=%2Fsrc%2FApp.js%3A30%2C16

You had too many hooks firing setting `setDate()`.

Duplicate of #4147

**Closed** 2023-12-06 12:59 UTC
Labels: Type: Bug, Resolution: Workaround
