### ISSUE TITLE
Password component width class w-full

### ISSUE THREAD

**Issue by crisscott** [primefaces/primereact#6623] opened 2024-05-14 19:22 UTC
### Describe the bug

I updated primereact from version 10.6.3 to 10.6.5 and in this new version i set the class "w-full" in the password component but is not tacking the changes, in the past version it works 

![image](https://github.com/primefaces/primereact/assets/47538514/34deceab-9c6b-4061-99b6-ea2d9a4972f8)

![image](https://github.com/primefaces/primereact/assets/47538514/11f8513b-e675-4b39-b6ac-7d08d6fbcfc4)

### Reproducer

https://stackblitz.com/edit/blg7hz?file=src%2FApp.jsx

### PrimeReact version

10.6.5

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

**Comment by melloware** [comment] 2024-05-14 19:26
Duplicate of https://github.com/primefaces/primereact/issues/6568

**Comment by melloware** [comment] 2024-05-14 19:27
You have to add w-full to iconField now `pt={{ iconField: { root: { className: 'w-full' } } }}`...

Fixed your stackblitz: https://stackblitz.com/edit/yfukmd-zhtknd?file=src%2FApp.jsx


```xml
<Password
        value={value}
        onChange={(e) => setValue(e.target.value)}
        inputClassName="w-full"
        className="bg-red-100 w-full"
        toggleMask
        pt={{ iconField: { root: { className: 'w-full' } } }}
      />
```

**Closed** 2024-05-14 19:27 UTC
Labels: Resolution: Duplicate

**Comment by Code-With-Anthony** [comment] 2024-10-03 13:08
> You have to add w-full to iconField now `pt={{ iconField: { root: { className: 'w-full' } } }}`...
> 
> Fixed your stackblitz: https://stackblitz.com/edit/yfukmd-zhtknd?file=src%2FApp.jsx
> 
> ```
> <Password
>         value={value}
>         onChange={(e) => setValue(e.target.value)}
>         inputClassName="w-full"
>         className="bg-red-100 w-full"
>         toggleMask
>         pt={{ iconField: { root: { className: 'w-full' } } }}
>       />
> ```

Thanks it worked for me as well. and seeing your suggestion i tried in my below code and it worked, and i keeping my code for all the persons coming for reference.

<div className="form-group">
            <label htmlFor="password">Password</label>
            <Password
              id="password"
              name="password"
              value={formData.password}
              onChange={handleChange}
              header={header}
              footer={footer}
              required
              toggleMask
              feedback={true}
              pt={{ iconField: { root: { className: "w-full" } } }}
              inputClassName="w-full"
              className="w-full"
            />
 </div>
