### ISSUE TITLE
ContextMenu: MenuItem template doesn't work

### ISSUE THREAD

**Issue by eugene-f02** [primefaces/primereact#4831] opened 2023-08-26 06:49 UTC
### Describe the bug

`template` method of MenuItems inside a ContextMenu doesn't work

### PrimeReact version

9.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

All

### Steps to reproduce the behavior

Open https://codesandbox.io/s/yhgx2m

replace
`    const items = [
        { label: 'View', icon: 'pi pi-fw pi-search' },
        { label: 'Delete', icon: 'pi pi-fw pi-trash' }
    ];
`
with 

`
    const items = [
        { label: 'View', icon: 'pi pi-fw pi-search' },
        {
          template:  (item, options) => (
                        <span>Hello There</span>
          )
        },
    ];
`

Observe that second item is not rendered

### Expected behavior

`template` should work MenuItems in ContextMenu

**Comment by melloware** [comment] 2023-08-26 11:29
Duplicate of https://github.com/primefaces/primereact/issues/4608 which will be fixed in next release.

**Closed by melloware** 2023-08-26 11:29 UTC
Labels: Status: Needs Triage
