### ISSUE TITLE
Carousel: Carousel elements do not recalculate after changing screen orientation

### ISSUE THREAD

**Issue by prakhar217** [primefaces/primereact#5805] opened 2024-01-19 11:20 UTC
### Describe the bug

When changing the screen Orientation when we have different number of visible  for the two orientation , the width doesnt re calculate 
For eg for a landscape screen size if we have lets say 3 elements visible but for a portrait mode the count is 2 , but when we again use the landscape , the button remains active according the amount of tiimes it was needed to scroll for the portrait mode

`  const responsiveOptions: CarouselResponsiveOption[] = [
    {
      breakpoint: "1366px",
      numVisible: 3,
      numScroll: 3,
    },
    {
      breakpoint: "1200px",
      numVisible: 3,
      numScroll: 3,
    },
    {
      breakpoint: "1180px",
      numVisible: 3,
      numScroll: 3,
    },
    {
      breakpoint: "1024px",
      numVisible: 2,
      numScroll: 2,
    },
    {
      breakpoint: "991px",
      numVisible: 2,
      numScroll: 2,
    },
    {
      breakpoint: "767px",
      numVisible: 2,
      numScroll: 2,
    },
  ];
`

### PrimeReact version

10.1.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Expected behavior

it should change scroll according to item number displayed

**Comment by melloware** [comment] 2024-01-19 14:35
Duplicate of: https://github.com/primefaces/primereact/issues/5166

**Closed by melloware** 2024-01-19 14:35 UTC
Labels: Status: Needs Triage
