### ISSUE TITLE
Multiple groupField issue

### ISSUE THREAD

**Issue by Suribabu-Balam** [primefaces/primereact#2333] opened 2021-09-30 15:15 UTC
Hi Team,

Could you please suggest me how way to implement multiple **groupField**  in row group data table.

![image](https://user-images.githubusercontent.com/81299732/135482367-1d9af754-710f-4a7b-8105-20ba82bcf010.png)

Thanks.

**Comment by master117** [comment] 2021-10-03 22:18
https://primefaces.org/primereact/showcase/#/datatable
https://primefaces.org/primereact/showcase/#/datatable/rowgroup
https://primefaces.org/primereact/showcase/#/datatable/colgroup

You can use the rowSpan field to define multiple rows for one datapoint.

Please note that it is bad manners to tag people to get a faster response.

**Comment by Suribabu-Balam** [comment] 2021-10-04 04:54
Okay, Thank you for your response.

**Comment by Suribabu-Balam** [comment] 2021-10-04 05:03
Hi Team,

  **rowGroupMode="rowspan"
  groupField="Field1,Field2"
  sortMode="multiple"
  sortField="Field1,Field2"
  sortOrder={1}**

We tried the above-mentioned code like that but not working. Please help me with the issue.

Thanks in advance.

**Comment by master117** [comment] 2021-10-04 05:35
Please show a whole sample using the code sandbox link provided when opening a new ticket.

**Comment by Suribabu-Balam** [comment] 2021-10-04 05:53
Hi Team,

**Code sandBox link: https://codesandbox.io/s/charming-cloud-8y2yz**
Please look into the above code sandbox link. We followed that reference code.

How way to set multiple **groupFields** in a single table issue.

Thanks in advance.

**Comment by master117** [comment] 2021-10-06 12:10
Ok, now I understand your problem. Primereact does not offer a way to group by multiple columns. The easiest approach would be to write a grouping algorithm (or import one, like d3.nest) to group your data. And then create rows from this data, with only the first row having all fields.

Like this: https://codesandbox.io/s/cranky-herschel-36ypx?file=/src/demo/DataTableRowGroupDemo.js

**Comment by mertsincan** [comment] 2021-11-04 11:54
Hi,

We added it to our roadmap and we'll implement it in future versions. Thanks a lot for the feature request

Best Regards,

**Comment by Vitalii-Pidoprygora** [comment] 2022-07-27 14:28
I will be very glad than it becomes available. Missing it a lot in my project.

**Comment by melloware** [comment] 2022-11-14 22:05
Duplicate of https://github.com/primefaces/primereact/issues/619

**Closed by melloware** 2022-11-14 22:05 UTC
Labels: Type: New Feature

**Comment by VikasKo-Kore** [comment] 2024-02-26 06:43
How to implement filtering for multiple fields in same column. Suppose in case of a component inside a column containing name, email, phone no, and now we want to filter on the basis of all three things.
