### ISSUE TITLE
Datatable Inability to select text

### ISSUE THREAD

**Issue by resitdemir** [primefaces/primereact#7307] opened 2024-10-04 11:15 UTC
### Describe the bug

When I want to select a text in a cell in a Datatable, the "drag" feature is activated. I cannot select the text.

### System Information

```Shell
"primereact": "^10.8.3",
"react": "^18",
```

### Expected behavior

The text in the cell needs to be selectable.

**Comment by sja-cslab** [comment] 2024-10-04 13:03
Dupe of #7221 fixed in 10.8.4

**Closed** 2024-10-04 13:08 UTC
Labels: Resolution: Duplicate
