### ISSUE TITLE
DataTable: Row dropdown is broken on version 10.6.4

### ISSUE THREAD

**Issue by ilFortu** [primefaces/primereact#6531] opened 2024-05-01 11:09 UTC
### Describe the bug

In version 10.6.4 the row dropdown is not working anymore, and a Javascript error is raised
<img width="1200" alt="image" src="https://github.com/primefaces/primereact/assets/15726869/e88c27a5-e6dd-470d-8e12-9fe9216cd747">

### Reproducer

https://primereact.org/datatable/#paginator

### PrimeReact version

10.6.4

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

Click on the row dropdown in the table footer

### Expected behavior

Should work as in the previous versions

**Comment by melloware** [comment] 2024-05-01 11:58
Duplicate of https://github.com/primefaces/primereact/issues/6518

**Closed** 2024-05-03 13:55 UTC
Labels: Resolution: Duplicate
