### ISSUE TITLE
"'import' and 'export' may only appear at the top level" error after updating, solved by renaming .js file to .mjs

### ISSUE THREAD

**Issue by Zimmerr** [primefaces/primereact#2660] opened 2022-02-24 15:42 UTC
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `primereact@7.2.1` for the project I'm working on.

After upgrading primereact to 7.2.1, i got the following error at the editor.esm.js:
```import' and 'export' may only appear at the top level```
After trying several solutions like using babel, upgrading react, etc, the only solution that worked was to rename the file into a .mjs extension.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/primereact/editor/editor.esm.js b/node_modules/primereact/editor/editor.esm.mjs
similarity index 100%
rename from node_modules/primereact/editor/editor.esm.js
rename to node_modules/primereact/editor/editor.esm.mjs
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by melloware** [comment] 2022-02-24 16:19
Can you explain more about this error and track it down?  

I wonder if the issue is this:

```ts
 componentDidMount() {
        import('quill').then((module) => {
```

It lazily imports QuillJS in the componentDidMount but its been doing that for a long time so I don't know why 7.2.1 would be different than your previous versions unless you chnaged some other ESLint rule or something your have?

**Comment by Zimmerr** [comment] 2022-02-24 17:36
Yeah, sorry for not providing a lot of info. Error happens on line 134 (its a very similar one to this one you provided, it just have a var _this declaration before).
Reason it was not happening before its because i had v3.1.7 installed (yes, very old, its from an old project that we are "reviving" at work, weird circumstances involved). On this version expandable rows on DataTable were not working and there are no docs avaliable, so we decided to upgrade and fix any possible incompatibility

We tested all versions that have a docs listed on primereact website, and 5.0.2 and older ones works just fine, but 6.6.0 and beyond gave us that error on import.

We didnt changed nothing besides primereact in our package.json

**Comment by melloware** [comment] 2022-02-24 17:37
Intresting ok i will see what @mertsincan says but just a warning Charts components do the exact same thing as above with ChartsJS it lazily imports then and I think a couple of other components as well.

**Comment by Zimmerr** [comment] 2022-02-24 17:46
We have ChartJS v2.7.3 installed but no problem until now, we are not currently using it but i will keep an eye on it if we need to upgrade it, thanks for the heads up. If you need any further look into the code just call me up here!

**Comment by melloware** [comment] 2022-02-24 18:08
Yep the PrimeReact Charts uses ChartsJS just like Editor uses QuillJS.

**Comment by melloware** [comment] 2022-02-24 23:50
Can you post your package.json.  I am not having any issues and I use Create React App.  Need more information about your build or tools so your package.json will help.

**Comment by Zimmerr** [comment] 2022-03-02 19:46
Sorry for taking too long to answer, here is my package.json:

`{
    "name": "COAD",
    "version": "0.2.1",
    "homepage": "http://gaaton.educacao.intranet/",
    "private": false,
    "license": "MIT",
    "type": "module",
    "dependencies": {
        "@fullcalendar/core": "4.0.2",
        "@fullcalendar/daygrid": "4.0.1",
        "@fullcalendar/interaction": "4.0.2",
        "@fullcalendar/timegrid": "4.0.1",
        "antd": "^3.24.2",
        "axios": "^0.19.0",
        "bootstrap": "^4.3.1",
        "chart.js": "2.7.3",
        "classnames": "^2.2.6",
        "formik": "^2.0.3",
        "formik-reactstrap-widgets": "^0.8.0",
        "http-status-codes": "^1.4.0",
        "jquery": "^3.4.1",
        "jwt-decode": "^2.2.0",
        "moment": "^2.24.0",
        "moment-timezone": "^0.5.27",
        "node-sass": "^4.12.0",
        "patch-package": "^6.4.7",
        "primeflex": "1.0.0-rc.1",
        "primeicons": "5.0.0",
        "primereact": "^7.2.1",
        "quill": "^1.3.7",
        "ramda": "^0.27.0",
        "react": "^17.0.2",
        "react-app-polyfill": "^1.0.1",
        "react-currency-input": "^1.3.6",
        "react-dom": "^17.0.2",
        "react-dropzone": "^10.1.10",
        "react-dropzone-uploader": "^2.11.0",
        "react-formik-ui": "^3.1.4",
        "react-hook-form": "^5.7.2",
        "react-icons": "^3.7.0",
        "react-moment": "^0.9.6",
        "react-redux": "^7.1.1",
        "react-router-dom": "^4.3.1",
        "react-scripts": "3.0.1",
        "react-stepzilla": "^6.0.2",
        "react-transition-group": "^4.4.1",
        "reactstrap": "^8.1.1",
        "redux": "^4.0.4",
        "redux-form": "^8.2.6",
        "redux-multi": "^0.1.12",
        "redux-promise": "^0.6.0",
        "redux-thunk": "^2.3.0",
        "yup": "^0.27.0"
    },
    "scripts": {
        "start": "react-scripts start",
        "build": "react-scripts build",
        "test": "react-scripts test",
        "eject": "react-scripts eject",
        "postinstall": "patch-package"
    },
    "eslintConfig": {
        "extends": "react-app"
    },
    "browserslist": [
        ">0.2%",
        "not dead",
        "not ie <= 11",
        "not op_mini all"
    ],
    "devDependencies": {
        "enzyme": "^3.10.0",
        "enzyme-adapter-react-16": "^1.15.1",
        "jest-environment-enzyme": "^7.1.2",
        "jest-enzyme": "^7.1.2"
    }
}
`

**Comment by melloware** [comment] 2022-03-02 20:41
OK it looks like you are using Create React App?  So am I with no issues?

**Comment by Zimmerr** [comment] 2022-03-04 17:01
Yeah i am, its an old react project from 2 years ago, idk exactly why this is happening as the syntax doesn't seem wrong, but somehow renaming the file worked out for me. my node version is 12.13.0 if thats any relevant

**Comment by melloware** [comment] 2022-04-10 12:10
@Zimmerr i think it is your Node version.

Mine
```
Node: v16.13.0
NPM: 8.1.3
```

**Comment by melloware** [comment] 2022-04-15 14:57
Since I can't reproduce this issue and no one else seems to be reporting it I am going to close this for now.  Will re-open if others report it.

**Closed by melloware** 2022-04-15 14:57 UTC
Labels: pending-review
