### ISSUE TITLE
Prop tabIndex not used?

### ISSUE THREAD

**Issue by pedro-tome** [primefaces/primereact#2223] opened 2021-07-29 09:18 UTC
https://github.com/primefaces/primereact/blob/b528943ae9ab65ec23338b97ee1bc4604d1512cc/src/components/calendar/Calendar.js#L34

I'm using the Calendar and trying to add a tabIndex to it but it seams not possible since the Prop is not used at all.

**Comment by mertsincan** [comment] 2021-11-03 07:40
Duplicate of #2260

**Closed by mertsincan** 2021-11-03 07:40 UTC
