### ISSUE TITLE
Calendar: React Hook Form Demo

### ISSUE THREAD

**Issue by andreluisos** [primefaces/primereact#3145] opened 2022-08-08 08:56 UTC
### Describe the bug

When controlling the component with useForm (react-hook-form), if default value is set to empty string, instead of null, and showOnFocus is off, the field won't input data properly.

### Reproducer

https://codesandbox.io/s/practical-bhaskara-dgq2g1

### PrimeReact version

8.3.0

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Component must be under control of react-use-form (not sure if the same would happen with another librabry).
2. Set the field's default value to empty string ('').
3. set showOnFocus={false}.

### Expected behavior

Proper data input.

**Comment by melloware** [comment] 2022-08-08 11:28
@andreluisos did you really mean to close this?

**Comment by melloware** [comment] 2022-08-08 13:16
It works for me see my demo: https://codesandbox.io/s/angry-shadow-ru4ix2?file=/src/demo/ReactHookFormDemo.js

I updated your Sandbox and had to add `rules={{ required: "Birthday is required." }}` ??

**Comment by andreluisos** [comment] 2022-08-08 13:20
Apparently, `mask` is also required to trigger the issue.

**Comment by andreluisos** [comment] 2022-08-08 13:20
> It works for me see my demo: https://codesandbox.io/s/angry-shadow-ru4ix2?file=/src/demo/ReactHookFormDemo.js
> 
> I updated your Sandbox and had to add `rules={{ required: "Birthday is required." }}` ??
> 
> It works with `date=""` or `date=null`

Apparently, mask is also required to trigger the issue.

add `mask="99/99/9999"` to your sandbox.

**Comment by melloware** [comment] 2022-08-08 13:22
Yep duplicate of https://github.com/primefaces/primereact/issues/2927 subscribe to that issue

**Closed by melloware** 2022-08-08 13:22 UTC
Labels: defect, :bangbang: needs-triage
