### ISSUE TITLE
TreeTable: scrollHeight='flex' doesn't work

### ISSUE THREAD

**Issue by FAMSTM** [primefaces/primereact#5488] opened 2023-12-01 15:05 UTC
### Describe the bug

scrollHeight='flex' doesn't work in TreeTable (it works in DataTable).

### Reproducer

https://codesandbox.io/p/sandbox/primereact-demo-forked-zprg8k

### PrimeReact version

10.1.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 119

### Expected behavior

scrollHeight='flex' works in TreeTable

**Comment by melloware** [comment] 2023-12-01 16:01
If you compare DT to TT and figure it out please submit a PR.

**Comment by melloware** [comment] 2023-12-04 13:18
Duplicate of https://github.com/primefaces/primereact/issues/2882

**Closed by melloware** 2023-12-04 13:18 UTC
Labels: Type: Bug
