### ISSUE TITLE
Editor: Listing as bullet display as numbered

### ISSUE THREAD

**Issue by swotiendang** [primefaces/primereact#6993] opened 2024-08-06 08:38 UTC
### Describe the bug

https://primereact.org/editor/
Listing items as bullet but display numbered.

![image](https://github.com/user-attachments/assets/1d334698-f13b-46c3-a467-3b603d17f51b)

### System Information

Chrome: v127 latest
    "primeflex": "^3.3.1",
    "primeicons": "^7.0.0",
    "primereact": "^10.8.2",

### Expected behavior

Display bullet for Editor when hitting Unordered list

**Comment by melloware** [comment] 2024-08-06 11:38
Duplicate of https://github.com/primefaces/primereact/issues/6914

its a bug in QuillJS: https://github.com/slab/quill/issues/4124 Please track that issue.

**Comment by swotiendang** [comment] 2024-08-07 11:07
Hi @melloware , this is my finding, I believe in primereact Editor implementation ignore core.css of Quills, there is many changes in quills@1.3.7 vs quills@2.0.2 

![image](https://github.com/user-attachments/assets/a215b65c-034b-4058-af86-1251f8d2c073)


This is my suggestion, do import quill.snow.css or quill.core.css to primereact Editor v10.8.2, I don't see much import in current latest version.

**Comment by swotiendang** [comment] 2024-08-07 11:20
Correct me if I'm wrong, we are using quill v1.3.7 css in usage of quill@2.0.0

**Comment by melloware** [comment] 2024-08-07 11:36
PrimeReact after 10.6.4 requires Quill 2.0 see: https://github.com/primefaces/primereact/issues/5960

Previous to that it was 1.3.7

**Closed** 2024-08-07 14:58 UTC
Labels: Type: Bug

**Comment by swotiendang** [comment] 2024-08-26 04:49
Hi @melloware , I need to bring this change to my project for version @10.8.2, my side do not allow more delay for the release. 
I'm trying to build the primereact and copy the build src to my project using npm patch package, but I cannot build it.

![image](https://github.com/user-attachments/assets/3659b59a-b86b-4c08-9d34-62a343f46a05)

Command I use: build:package
Environment: Window 11 Pro

I suggest to create a section in the documentation to show how to build and bundle the project.
