### ISSUE TITLE
DataTable Filter: row filter type error with React18 (while in React.StrictMode)

### ISSUE THREAD

**Issue by dani-ras** [primefaces/primereact#2947] opened 2022-05-30 16:41 UTC
### Describe the bug

While using React.StrictMode, typing in filter row input throws type error: 
`datatable.esm.js:2842 Uncaught TypeError: Cannot set properties of undefined (setting 'value')`

If typing into global filter first, it then allows to type into the row filter inputs eventually.

### Reproducer

https://codesandbox.io/s/primereact-test-forked-7dqvg5?file=/src/DatatableFilterTest.js

### PrimeReact version

8.1.x

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

Go to sandbox link provided, type into row input (while in `StrictMode`, given) see error.
Type into global filter, then try row inputs - works.
comment out `<React.StrictMode>`, row inputs work.
![TableFilters](https://user-images.githubusercontent.com/77384873/171033464-abefcabc-5101-4c7c-bf0f-54e053f8e940.gif)

**Comment by melloware** [comment] 2022-05-30 17:18
Duplicate of #2777

**Closed** 2022-05-30 17:18 UTC
Labels: duplicate
