### ISSUE TITLE
DataTable: re-order + resizable fails

### ISSUE THREAD

**Issue by Holgrabus** [primefaces/primereact#6599] opened 2024-05-08 21:28 UTC
### Describe the bug

When we have resizableColumns + reorderableColumns options activated, the column re-order is failing.

It duplicates the first column 2 times and set the moved column at the end.

Example:
**Before**
NAME | COUNTRY | AGENT | DATE | BALANCE | STATUS | ACTIVITY

I tried to move AGENT before COUNTRY
**After**

NAME | NAME | COUNTRY | DATE | BALANCE | STATUS | ACTIVITY | NAME | AGENT

I forked an example from your doc and only added these 2 options.

### Reproducer

https://stackblitz.com/edit/qhavtj?file=src%2FApp.jsx

### PrimeReact version

10.6.5

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 124

### Steps to reproduce the behavior

It's very easy, just drag and drop a column (any column) and you will see a duplicate of the first one.

### Expected behavior

Reorder columns, not create duplicates.

**Comment by Rekl0w** [comment] 2024-05-09 06:04
Duplicate of #6558.

**Comment by Holgrabus** [comment] 2024-05-14 18:28
Sorry but the one you are mentioning is not exactly the same and is "closed". The bug here is real, and there is no workaround.

**Closed** 2024-05-14 19:27 UTC
Labels: Resolution: Duplicate
