### ISSUE TITLE
Issue detaching Dropdown Menu when scrolling in dialog

### ISSUE THREAD

**Issue by belopot** [primefaces/primereact#4123] opened 2023-03-02 18:43 UTC
### Describe the bug

I have one dialog in a page. When scrolling in the dialog, dropdown menu is detaching to it.
https://user-images.githubusercontent.com/46432435/222522431-969f6e3d-49e8-4d18-b007-0a2ff83249b5.mp4

Even though I tried to do it with "appendTo", it didn't work properly. You can see the issue through below video
![image](https://user-images.githubusercontent.com/46432435/222521305-f8205697-c9a2-405c-8fcc-2ed459249c16.png)
https://user-images.githubusercontent.com/46432435/222521713-675d9148-de62-4371-99f8-857e7760449a.mp4

### PrimeReact version

8.3.0

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 110

**Comment by melloware** [comment] 2023-03-02 21:10
Duplicate of #2683 

I have submitted a PR for this but it has not been accepted yet: https://github.com/primefaces/primereact/pull/2757

**Closed by melloware** 2023-03-02 21:10 UTC
Labels: Status: Needs Triage
