### ISSUE TITLE
DataTable: On click at dropdown option in a cell editor doesn't set the value for the datatable cell - Keypress works 

### ISSUE THREAD

**Issue by hu9000** [primefaces/primereact#5122] opened 2023-10-19 23:55 UTC
### Describe the bug

Using the mouse to select an option from the dropdown doesn't set the value in the "Country" column of the datatable. But, using the keyboard ("tab" ,"enter" ), said value is updated at the datatable with cell editor.

### Reproducer

https://codesandbox.io/s/elastic-yalow-hdlfzx?file=/src/App.tsx

### PrimeReact version

10.0.5

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Go to Country cell and click it
2. Click on the dropdown
3. Select any country option
4. Value at the datatable cell is not updated. 
[Screen sample](https://ibb.co/LrDGWH6) of the behavior

### Expected behavior

Country cell must be updated to the country selected on the dropdown. Like press the DOWN key then TAB is working.

**Comment by melloware** [comment] 2023-10-20 00:16
Duplicate of #2666 see that ticket for the solution. 

Let me know if that doesn't work.

**Closed** 2023-10-20 00:17 UTC
Labels: Resolution: Duplicate

**Comment by hu9000** [comment] 2023-10-20 20:53
Thank you for your response.
After adding the code `appendTo={"self"}` to the dropdown you can now select the clicked option. But now when I navigate through the list of options with the keyboard, when I get to the last visible option, the list closes automatically.

**Comment by melloware** [comment] 2023-10-20 23:48
@hu9000 see https://github.com/primefaces/primereact/issues/4482
