### ISSUE TITLE
Cannot set full widht of Password compoent when toggleMask is enabled

### ISSUE THREAD

**Issue by lekhnath** [primefaces/primereact#6690] opened 2024-05-28 05:51 UTC
### Describe the bug

**Password component without toggleMask enabled can set full width**

```
<Password className="w-full" inputClassName="w-full" />
```

**Password component with toggleMask enabled CANNOT set full width**

```
<Password className="w-full" inputClassName="w-full" toggleMask />
```

### PrimeReact version

10.6.6

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by melloware** [comment] 2024-05-28 11:32
Duplicate of https://github.com/primefaces/primereact/issues/6623#issuecomment-2110991635  

You have to add w-full to iconField now `pt={{ iconField: { root: { className: 'w-full' } } }}`...

Fixed your stackblitz: https://stackblitz.com/edit/yfukmd-zhtknd?file=src%2FApp.jsx


```xml
<Password
        value={value}
        onChange={(e) => setValue(e.target.value)}
        inputClassName="w-full"
        className="bg-red-100 w-full"
        toggleMask
        pt={{ iconField: { root: { className: 'w-full' } } }}
      />
```

**Closed by melloware** 2024-05-28 11:32 UTC
Labels: Status: Needs Triage

**Comment by lekhnath** [comment] 2024-05-29 06:14
@melloware I was unaware that I could nest component passthroughs in such a way. Thank you very much.
