### ISSUE TITLE
[Feature request]: add Select all checkbox to Listbox component

### ISSUE THREAD

**Issue by sergeykimaia** [primefaces/primereact#2203] opened 2021-07-20 11:17 UTC
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see 

PrimeNG already has such thing: https://www.primefaces.org/primeng/showcase/#/listbox

**PrimeNG:** 
![Screen Shot 2021-07-20 at 14 11 47](https://user-images.githubusercontent.com/58387319/126314614-d8ac3df7-8410-481a-bd53-e95d0e398647.png)

**PrimeReact:** 
![Screen Shot 2021-07-20 at 14 12 01](https://user-images.githubusercontent.com/58387319/126314640-91342ffb-ee68-4669-a28a-91d47c7a1429.png)

**Comment by melloware** [comment] 2023-01-04 00:23
Duplicate of #2261

**Closed** 2023-01-04 00:24 UTC
Labels: Resolution: Duplicate
