### ISSUE TITLE
Calendar: showOnFocus = false no keyboard support for calendar overlay

### ISSUE THREAD

**Issue by nico-richter** [primefaces/primereact#3674] opened 2022-11-18 14:48 UTC
### Describe the bug

If using Calendar with showOnFocus = false there is no way to open the Calendar overlay with just using keyboard.

Same issue happens if using showOnFocus=true and hiding Overlay using Esc and like to reopen Overlay.

### PrimeReact version

8.7.2

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 107

### Steps to reproduce the behavior

1. Focus <Calendar showOnFocus={false} />
2. press Enter or ArrowDown

### Expected behavior

Calendar overlay is shown

**Comment by melloware** [comment] 2022-11-18 14:53
Duplicate of https://github.com/primefaces/primereact/issues/1830

It will work like PrimeVue when complete: https://www.primefaces.org/primevue/calendar

**Closed by melloware** 2022-11-18 14:53 UTC
Labels: Resolution: Duplicate
