### ISSUE TITLE
Calendar:  The issue of the calendar layout being broken.

### ISSUE THREAD

**Issue by minsgy** [primefaces/primereact#4664] opened 2023-07-18 09:27 UTC
### Describe the bug

Hello. While using PrimeReact components, I've encountered a bug and would like to report it.

When I click on the Calendar component to open the Dropdown, then switch to Month view and close the Popup, selecting a day in the Day view causes the display to become broken.

However, reopening the Popup seems to resolve the issue. Please take a look at this issue.

I am attaching a related GIF for your reference. Thanks

![2023-07-18 18 25 52](https://github.com/primefaces/primereact/assets/60251579/428a7e21-85aa-4a79-aa3c-e06d817bec93)

### PrimeReact version

9.6.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 90

### Steps to reproduce the behavior

1. Click on the Calendar component to open the Dropdown.
2. Switch to Month view.
3. Close the Popup.
4. Click on a specific day in the Month view.
5. The display becomes broken.

**Comment by melloware** [comment] 2023-07-18 11:39
Duplicate of https://github.com/primefaces/primereact/issues/4578 already fixed for next release.

**Closed by melloware** 2023-07-18 11:39 UTC
Labels: Resolution: Duplicate
