### ISSUE TITLE
DataTable: Data are not displayed when "Column" has no "field" attributes

### ISSUE THREAD

**Issue by ghostd** [primefaces/primereact#4248] opened 2023-04-15 16:16 UTC
### Describe the bug

I use DataTable with the callback "body" (without the "field" attribute); no data are displayed in this case (that workend with Prime 8.7.3).

Here is a test to reproduce the case (in addition to the CodeSandbox):
```
import '@testing-library/jest-dom';
import { render } from "@testing-library/react";
import * as React from "react";
import { Column } from '../column/Column';
import { DataTable } from './DataTable';

describe('DataTable', () => {
    test('should display data with Column without field', () => {
        // Arrange
        const { container } = render(<DataTable dataKey={"key"} value={[{ key: 0 }, { key: 2 }]}>
            <Column
                header="Column 1"
                body={(row) => <div>This is column 1 for item {row.key}</div>}
            />
            <Column
                header="Column 2"
                body={(row) => <div>This is column 2 for item {row.key}</div>}
            />
        </DataTable>
        );

        // Assert
        expect(container).toHaveTextContent('This is column 1 for item 0');
        expect(container).toMatchSnapshot();
    });
});

```

### Reproducer

https://codesandbox.io/s/primereact-test-forked-btleh6

### PrimeReact version

9.2.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment] 2023-04-16 11:56
Definitely a bug..great reproducer.

**Comment by melloware** [comment] 2023-04-16 12:12
Interesting trying to reproduce it in the Showcase which is NextJS it seems to be working.

![image](https://user-images.githubusercontent.com/4399574/232309046-7e59f065-1873-47c5-a69a-6a66d9ca1daa.png)

Still investigating.

**Comment by melloware** [comment] 2023-04-16 12:14
Weird it works in Vite on StackBlitz also: https://stackblitz.com/edit/react-rhjloz?file=src%2FApp.js

**Comment by melloware** [comment] 2023-04-24 17:49
OK good we have seen other Strict Mode issues in the past as well.  I marked it as "React 18" label and that will help us look for the issue.

**Comment by ghostd** [comment] 2023-04-24 17:52
The Strict mode seems to involve a second rendering phase, which makes the code work. It could be a bug with badly initialised state?

**Comment by ghostd** [comment] 2023-04-24 18:10
I think it's related to the `d_filtersState` state... still investigating.

**Comment by melloware** [comment] 2023-04-24 18:18
OK can you try my fix.

**Comment by melloware** [comment] 2023-04-24 18:19
Sorry just posted: https://github.com/primefaces/primereact/pull/4280

Can you try that and let me know. Locally it seems to be working in Strict Mode and non Strict Mode

**Comment by melloware** [comment] 2023-04-24 18:27
the `useMount` effect is usually the culprit in React Strict Mode 18 issues.

**Comment by ghostd** [comment] 2023-04-25 06:29
It works for me, thanks.

**Closed** 2023-04-25 10:20 UTC
Labels: Type: Bug, React 18
