### ISSUE TITLE
DataTable: scroll forced to top when inside "flex-column" container with virtual scrolling enabled

### ISSUE THREAD

**Issue by inad9300** [primefaces/primereact#6364] opened 2024-04-09 21:29 UTC
### Describe the bug

At least under these specific conditions, the `DataTable` prevents you from scrolling to lower rows:
```jsx
<div className="h-full flex flex-column">
  <div className="flex-1">
    <DataTable
      value={DATA}
      dataKey="id"
      scrollable
      scrollHeight="flex"
      size="small"
      virtualScrollerOptions={{ itemSize: 41, numToleratedItems: 25 }}>
      <Column field="id" header="ID" />
    </DataTable>
  </div>
</div>
```

### Reproducer

https://stackblitz.com/edit/vitejs-vite-y75yma?file=src%2FApp.tsx

### PrimeReact version

10.6.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Attempt to scroll down.
2. Observe how, after row 45 or so becomes visible, the scroll automatically jumps back to the top of the table.

**Comment by sja-cslab** [comment] 2024-04-16 10:32
Your seconds div.flex-1 is redundant and causes this.
Remove that and your Scroll will work

**Comment by melloware** [comment] 2024-04-16 11:36
@sja-cslab thank you!  Will close this as "workaround provided" as you are right this is more to do with the structure of this HTML.

**Closed by melloware** 2024-04-16 11:36 UTC
Labels: Resolution: Workaround

**Comment by melloware** [comment] 2024-04-16 12:19
@inad9300 what he is saying is your HTML + CSS broke the table styling.  So like anything else in HTML/CSS you would have to respect the structure of the DOM of the generated component.

**Comment by inad9300** [comment] 2024-04-16 12:20
If "without flex [I] just broke the width/height calculation within the Virtual Scroller", it follows that there _is_ a requirement to "use HTML and CSS that does not break the width/height calculation within the Virtual Scroller", and it would be good to know what the Virtual Scroller requires.

The reproducer I provided differs from my original code, which I iteratively simplified until I couldn't reproduce the problem anymore. In order to apply the solution to my real case, I would like to have a somewhat solid understanding of the constraints imposed by Virtual Scroller over the layout and styling.

Lastly, but importantly, after closer inspection of your proposed solution (other than removing the div, which I don't yet see any good reason to), it omits a crucial point from the original solution: `flex-column`. If you add it back, the scroll will remain broken; propagating "flex" is not the solution.

My suspicion is that the aforementioned calculations by Virtual Scroller just fail in one or a few corner cases that need to be taken into account (or documented).

**Comment by inad9300** [comment] 2024-04-16 14:15
(I agree keeping things simple is a good reason to remove the div, it just is a reason unrelated to the problem at hand.)

**Comment by ayonix** [comment] 2024-12-19 09:39
I don't know if this is related, but the outcome seems to be similar:
We have a datatable inside of a flexbox. If the table is scrolled to the right and you sort the columns for example, the table scrolls back to the left.
Is this also a combination of css that isn't supposed to work or should this work?
Reproducer: https://stackblitz.com/edit/jg7acft4-mfmis79x?file=src%2FApp.jsx 
The problem seems to be lessened if you give the div containig the table a max-width.

**Comment by sja-cslab** [comment] 2024-12-19 10:48
@ayonix i looked intp you reproducer however if i scroll right and then sort a column, it's working as expected, no jumping around for me.

**Comment by ayonix** [comment] 2024-12-20 07:36
Oh yes, sorry. I copied it with the max-width set in that version. Here is the version without it: https://stackblitz.com/edit/jg7acft4-1vc4xsw1?file=src%2FApp.jsx

**Comment by sja-cslab** [comment] 2024-12-20 10:31
@ayonix you should, if you want to work with flexbox in table combination, try to use flex as much as possible,
I've forked your stack and made a few little changes - rendering isn't perfect for now and cell-text overlaps but you will see, that reordering wont jump anymore

https://stackblitz.com/edit/jg7acft4-hxpm2vuz?file=src%2FApp.jsx

**Comment by ayonix** [comment] 2025-02-11 15:25
@sja-cslab Should I open a new issue for the problem of my reproducer?

**Comment by sja-cslab** [comment] 2025-02-12 06:40
@ayonix do you have the same issue in 10.9.2?

**Comment by inad9300** [comment] 2025-05-23 09:35
I'm hitting this problem again, which seems exactly the same in @ayonix' case. It feels extremely easy to break the table scrolling in one or another way, to be honest: depending on how exactly I set up the DOM hierarchy (in all cases it looks good to me, there really is nothing special), I've seen the scroll inadvertently jump to the top the first time you scroll to the bottom, then every time you scroll to the bottom, then every time but jumping only a few pixels instead of all the way.

@sja-cslab Starting with the basics, what's the simplest setup required for a table that fits its container? In trying to prepare a new reproducer, I find myself surprised that the following doesn't work: https://stackblitz.com/edit/hcx7esey?file=src%2FApp.jsx.

```html
<body class="h-screen m-0">
  <div id="root" class="h-full"></div>
  <script type="module" src="/src/main.jsx"></script>
</body>
```

```jsx
let id = 1;

const DATA = Array(100)
  .fill(null)
  .map(() => ({ id: id++ }));

const VIRTUAL_SCROLLER_OPTIONS = { itemSize: 53 };

export default function App() {
  return (
    <DataTable
      value={DATA}
      dataKey="id"
      scrollable
      scrollHeight="flex"
      virtualScrollerOptions={VIRTUAL_SCROLLER_OPTIONS}
    >
      <Column field="id" header="ID" />
    </DataTable>
  );
}
```

What am I missing in this basic example?

**Comment by inad9300** [comment] 2025-05-23 10:45
I managed to advance by adding `.p-virtualscroller { flex: 1 }`. It feels like a missing style in PrimeReact, but I would like to know if you see any other way to make the previous example work. (BTW, I tried using `pt={{ className: 'flex-auto' }}`, but it was ignored.)

With this new style added, I tried wrapping the table in a `<div>`, which, you will concede, is a fairly common and useful thing to do in a variety of scenarios. Doing that reproduces a version of the problem – this time, the scrollbar jumps _almost_ to the top, and without having to take it to the bottom.

About this version, too, I would like to know why it isn't working, as I see nothing wrong with the DOM structure: https://stackblitz.com/edit/hcx7esey-rahipkab?file=index.html,src%2FApp.jsx.

**Comment by sja-cslab** [comment] 2025-05-23 12:00
use this in your stackblitz:

```js
export default function App() {
  return (
    <div style={{
      height: "100%",
      minHeight: "100%",
      display: "flex",
      overflow: "hidden"
    }}>
      <div className="flex flex-auto border-none overflow-hidden">
        <DataTable
        className="flex-auto overflow-hidden"
          value={DATA}
          dataKey="id"
          scrollable
          stripedRows
          scrollHeight="flex"
          virtualScrollerOptions={{ itemSize: 46, className: "flex flex-auto align-items-start" }}
          pt={PASS_THROUGH_OPTIONS}
          tableStyle={{ tableLayout: 'fixed', flex: '1 1 auto' }}
        >
          <Column field="id" header="ID" />
        </DataTable>
      </div>
    </div>
  );
}
```

**Comment by inad9300** [comment] 2025-05-23 16:09
> if you want to use flexbox correctly, you've to keep flexbox from a starting point the whole way down to the last child

Not so. Flexbox establishes a relationship between a parent and its children. Neither the parent's parent nor the children's children need to use any flexbox properties. Also, the children's children's children can totally use flexbox again even if there has been a break in the chain.

You insist on removing `flex-column` without even mentioning it, but this part is essential both to my use case and to the problem I'm trying my best to report. The latest modifications to https://stackblitz.com/edit/hcx7esey-rahipkab should make it clear what I'm after:

```tsx
export default function App() {
  return (
    <div className="h-full flex flex-column">
      <h1>Page's Title</h1>

      <div className="flex-auto flex flex-column">
        <h2>Table's Title</h2>
        <DataTable
          value={DATA}
          dataKey="id"
          scrollable
          scrollHeight="flex"
          className="flex-auto"
          virtualScrollerOptions={{ itemSize: 53, className: 'flex flex-auto' }}
        >
          <Column field="id" header="ID" />
        </DataTable>
      </div>
    </div>
  );
}
```

I would like to get an answer about https://stackblitz.com/edit/hcx7esey too.

**Comment by sja-cslab** [comment] 2025-05-23 20:26
You explained exactly what I was trying to say.
I'm on my phone atm and wont have access to my PC till monday i guess.

Would you okay if we continue that conversion in discord? Just open a thread within primereact and i'll answer as soon as possible.
