### ISSUE TITLE
DataTable: Column resizing in fit mode does not work

### ISSUE THREAD

**Issue by PasBazz** [primefaces/primereact#4667] opened 2023-07-18 12:14 UTC
### Describe the bug

If the bundle is built in production mode, resizing the columns does not work.

Working [example ](https://codesandbox.io/s/12tzey?file=/src/App.js)built in the development mode.

### Reproducer

https://primereact.org/datatable/#resize_fitmode

### PrimeReact version

9.5.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Open reproducer
2. Try resizing any column

### Expected behavior

The column should resize

**Comment by melloware** [comment] 2023-07-18 12:28
Duplicate of https://github.com/primefaces/primereact/issues/4471 fixed already for next release

**Closed by melloware** 2023-07-18 12:28 UTC
Labels: Status: Needs Triage
