### ISSUE TITLE
Carousel responsive options only works when compressing

### ISSUE THREAD

**Issue by RodrigoNovais** [primefaces/primereact#5298] opened 2023-11-13 06:59 UTC
### Describe the bug

Setting the responsive options can make the number of itens reduce while compressing the window but they doesn't reappear when resizing the window to the original size

No need for a sandbox since it can be tested in the docs page

### Reproducer

https://primereact.org/carousel/#responsive

### PrimeReact version

10.0.9

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment] 2023-11-13 12:46
Duplicate of https://github.com/primefaces/primereact/issues/5166

**Closed by melloware** 2023-11-13 12:46 UTC
Labels: Status: Needs Triage
