### ISSUE TITLE
Primereact Calendar component always convert the date to browser's timezone

### ISSUE THREAD

**Issue by Vikas175Prasad** [primefaces/primereact#4937] opened 2023-09-20 16:27 UTC
### Describe the bug

Primereact Calendar component always convert the date of any fixed timezone to browser's timezone. It should show the date in the original timezone only and should not convert it to browser's timezone when we are assigning a fixed value to the component.

### Reproducer

https://stackblitz.com/edit/stackblitz-starters-8uoj3f?file=src%2FApp.tsx

### PrimeReact version

9.6.2

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Create Calendar component 
2. Assign date string of any fixed timezone (for e.g., Europe/London) to value property of the component.

### Expected behavior

The calendar should display the date in original timezone and should not automatically convert it to browser's/client timezone.

**Comment by melloware** [comment] 2023-09-20 19:16
Duplicate of https://github.com/primefaces/primereact/issues/4128

**Closed by melloware** 2023-09-20 19:16 UTC
Labels: Status: Needs Triage
