### ISSUE TITLE
Dropdown: page scroll behaviour

### ISSUE THREAD

**Issue by kusyka911** [primefaces/primereact#3217] opened 2022-08-31 17:28 UTC
### Describe the bug

Dropdown panel may be displayed over the other elements on the page after page scroll.

### Reproducer

https://codesandbox.io/s/primereact-dropdown-bug-demo-2-ime4fm

### PrimeReact version

8.4.0

### React version

17.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome latest

### Steps to reproduce the behavior

Conditions:
page has fixed element with `z-index: 1` (or higher but less then dropdown panel)
page can be scrolled in a proper way (see Reproducer demo)
1. Open dropdown
2. Scroll the page
3. Pay attention to the result.

### Expected behavior

Dropdown is closed after scroll event occur. Or this behaviour can be enabled with prop `closeOnScroll` set to `true`.

**Comment by melloware** [comment] 2022-08-31 17:35
Duplicate of: https://github.com/primefaces/primereact/pull/2757

**Closed by melloware** 2022-08-31 17:35 UTC
Labels: Status: Needs Triage
