### ISSUE TITLE
Dropdown: visual glitch

### ISSUE THREAD

**Issue by potatosalad94** [primefaces/primereact#6783] opened 2024-06-21 12:58 UTC
### Describe the bug

I'm experiencing a visual glitch when refreshing the page with a dropdown component 

I've attached a reproduction link with the same issue

https://github.com/primefaces/primereact/assets/44224578/d8786ffd-4a4f-4dfb-b4da-a413f98f898a

### Reproducer

https://stackblitz.com/edit/nextjs-btjxrx?file=app%2Fpage.tsx,app%2Flayout.tsx,app%2Fglobals.css

### PrimeReact version

10.6.6

### React version

18.x

### Language

ALL

### Build / Runtime

Next.js

**Comment by gcko** [comment] 2024-09-11 06:18
@potatosalad94 I forked and updated your Stackblitz to make the issue clear: https://stackblitz.com/~/github.com/gcko/nextjs-knnkfy?file=app/page.tsx

Example of the issue:
<img width="1059" alt="Screenshot 2024-09-11 at 14 17 30" src="https://github.com/user-attachments/assets/d594a1f9-f6e5-4bd9-9e0f-c76d97ef8dfb">

@melloware the issue is due to a Flash of Unstyled Content (FoUC). The following styles are not being loaded until after the content is loaded:

```html
<style type="text/css" data-primereact-style-id="base">...</style>
<style type="text/css" data-primereact-style-id="global">...</style>
<style type="text/css" data-primereact-style-id="common">...</style>
<style type="text/css" data-primereact-style-id="dropdown">...</style>
```

The main issue is that `base` includes styling to hide `input`, `select`, and `chackbox` fields, however because it does not get loaded right away, they "flash" before they are actually hidden

**Comment by melloware** [comment] 2024-09-11 11:31
Yep we have an FOUC ticket: https://github.com/primefaces/primereact/issues/5188

**Comment by gcko** [comment] 2024-09-25 03:21
@melloware should this one be marked as a duplicate of #5188 since it is an a permutation of the same issue (FoUC)?

Also @potatosalad94 , Melloware provided a *temporary* solution to this on that ticket via taking the css, creating a file, and importing it in your root react file -> https://github.com/primefaces/primereact/issues/5188#issuecomment-1792428716

**Closed** 2024-09-25 11:52 UTC
Labels: Component: Tailwind
