### ISSUE TITLE
MegaMenu : does not hide on outside click

### ISSUE THREAD

**Issue by ivankulaha** [primefaces/primereact#4727] opened 2023-08-02 16:47 UTC
### Describe the bug

_MegaMenu_ component does not close on click outside or on clicking on empty space in menu panel

### PrimeReact version

9.6.0

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Create any _MegaMenu_ component with several items in menu. For instance https://codesandbox.io/s/jyygey
2. Click outside of the component

### Expected behavior

_MegaMenu_ popup should be hidden

**Comment by melloware** [comment] 2023-08-02 20:39
Duplicate of https://github.com/primefaces/primereact/issues/4614

**Closed by melloware** 2023-08-02 20:39 UTC
Labels: Status: Needs Triage
