### ISSUE TITLE
PanelMenu: pt (passthrough) prop stopped working in 9.6.2

### ISSUE THREAD

**Issue by Noorman999** [primefaces/primereact#4828] opened 2023-08-25 14:53 UTC
### Describe the bug

I bumped the version of primereact from 9.5.0 to 9.6.2 and the PanelMenu passthrough prop stopped working. I created an example in which it works in version 9.5.0 but not in 9.6.2. (In the example it must paint the background of the header label)

9.5.0 (version that works)
![image](https://github.com/primefaces/primereact/assets/33288453/e63f49f7-48ac-440f-9f20-1223ad107763)

9.6.2 (version that does not works)
![image](https://github.com/primefaces/primereact/assets/33288453/11860f58-d20e-4398-a82c-f0127f2b3598)

### Reproducer

https://codesandbox.io/s/primereact-test-forked-s856tz?file=/src/index.js

### PrimeReact version

9.6.2

### React version

18.x

### Language

ALL

### Build / Runtime

Next.js

### Steps to reproduce the behavior

Just change the version of primereact to compare boths panelmenu behavior

### Expected behavior

PanelMenu must paint blue the headerLabel

**Comment by melloware** [comment] 2023-08-25 14:58
1. I fixed your app with a workaround: https://codesandbox.io/s/primereact-test-forked-p9sypv?file=/src/index.js

2. This is a duplicate of https://github.com/primefaces/primereact/issues/4622

**Closed by melloware** 2023-08-25 14:58 UTC
Labels: Status: Needs Triage
