### ISSUE TITLE
SplitterPanel: size property doesn't take effect after the drag event fired

### ISSUE THREAD

**Issue by rajkeshwar** [primefaces/primereact#6016] opened 2024-02-20 10:02 UTC
### Describe the bug

I have a requirement of using toggle feature in SplitterPanel to set it expanded and collapsed mode. Let's say when the left SplitterPanel is collapsed it's size is 4 and 35 when expanded. This works fine with useState until I don't use the splitter to drag. After the drag event the toggle mode doesn't work. Though it set's the sizes state correctly. 

### Reproducer

https://stackblitz.com/edit/mb76rz?file=src%2FApp.jsx

### PrimeReact version

^10.1.1

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome, Safari

### Steps to reproduce the behavior

Use this link stackblitz to see the issue 
https://stackblitz.com/edit/mb76rz?file=src%2FApp.jsx

### Expected behavior

The collapse/expand feature should work after drag also

**Comment by melloware** [comment] 2024-02-20 12:38
@rajkeshwar i think this is a duplicate of this one: https://github.com/primefaces/primereact/issues/5922 ??

**Comment by rajkeshwar** [comment] 2024-02-20 13:48
> @rajkeshwar i think this is a duplicate of this one: #5922 ??

I'm eager to understand what's causing the inability to set the size when dragging through the gutter. Despite examining the code, I couldn't pinpoint where the size props are being set and what halts the dragging process.

As a temporary solution, I've implemented a condition that triggers a re-render of the Splitter onResizeEnd. However, this workaround is quite resource-intensive. It essentially destroys and initializes the Splitter, resulting in flickering. Unfortunately, I haven't found another method to reset the state without completely destroying the component.

I'll keep an eye on the discussions and PRs to see if a solution arises.

Looking forward to resolving this issue together.

**Closed** 2024-02-21 12:46 UTC
Labels: Resolution: Duplicate
