### ISSUE TITLE
AutoComplete: Item selection is wrong when using keyboard with virtual scrolling

### ISSUE THREAD

**Issue by Frdnspnzr** [primefaces/primereact#4936] opened 2023-09-20 14:09 UTC
### Describe the bug

When using keyboard navigation to select a suggestion further down the list the item that gets selected is wrong. This bug can be reproduced [even in the Virtual Scroll example in the documentation](https://primereact.org/autocomplete/#virtualscroll).

![primereact_autocomplete](https://github.com/primefaces/primereact/assets/1454778/f02138d2-7142-414c-a304-a3a1e85ec86d)

### Reproducer

https://codesandbox.io/s/2pv1tp

### PrimeReact version

9.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Browser(s)

Chrome 117, Firefox 117

**Comment by melloware** [comment] 2023-09-20 19:15
Duplicate of https://github.com/primefaces/primereact/issues/4536

**Closed by melloware** 2023-09-20 19:15 UTC
Labels: Resolution: Duplicate
