### ISSUE TITLE
CSS Loading Issue with Prime Version 10.0.3

### ISSUE THREAD

**Issue by meriemMat** [primefaces/primereact#5120] opened 2023-10-19 15:04 UTC
### CSS Loading Issue with Prime Version 10.0.3

i am having this ui shwoing quiqly then the css is correctly set :
![Sans titre](https://github.com/primefaces/community/assets/17379300/0b357363-e7b3-4825-ad75-8cd2ea2bc409)
Any idea about the cause?

**Comment by aholeye** [comment] 2023-10-25 12:47
I hava the same issue with `10.0.5`: 
![image](https://github.com/primefaces/primereact/assets/26758630/e4216729-dd25-47f2-b527-ab0da4efb4eb)

**Comment by melloware** [comment] 2023-10-25 12:50
See this: https://soydiego.notion.site/PrimeReact-How-to-fix-styles-NextJS-Tailwind-92bec3eb91594388a7be67d922460eaf

**Comment by aholeye** [comment] 2023-10-25 13:08
> See this: https://soydiego.notion.site/PrimeReact-How-to-fix-styles-NextJS-Tailwind-92bec3eb91594388a7be67d922460eaf

Only when the page is loading does it appear as shown in the picture, and then it immediately displays correctly.
So, the doc doesn't work for me.

**Comment by melloware** [comment] 2023-10-25 13:13
@SoyDiego  ?

**Comment by SoyDiego** [comment] 2023-10-25 13:22
Share a Stackblitz to see if we can help @aholeye @meriemMat

**Comment by aholeye** [comment] 2023-10-25 14:22
@SoyDiego @melloware Thanks for your reply.
I create a sandbox link, used Next js templeate. And then I installed two dependencies, which are `primeicons` and `primereact`.
I replaced the default code with the Pagination component. Waiting for the server to start completely, and you can reproduce the issue by refreshing the page.
There is the sandbox link: https://codesandbox.io/p/sandbox/agitated-butterfly-td3m97?file=%2Fapp%2Fpage.tsx%3A6%2C33
Thanks again.

**Comment by SoyDiego** [comment] 2023-10-25 17:34
> @SoyDiego @melloware Thanks for your reply. I create a sandbox link, used Next js templeate. And then I installed two dependencies, which are `primeicons` and `primereact`. I replaced the default code with the Pagination component. Waiting for the server to start completely, and you can reproduce the issue by refreshing the page. There is the sandbox link: https://codesandbox.io/p/sandbox/agitated-butterfly-td3m97?file=%2Fapp%2Fpage.tsx%3A6%2C33 Thanks again.

I don't understand the issue. I can see a paginator and with good styles in your StackBlitz. Can you give me more context, please?

![image](https://github.com/primefaces/primereact/assets/19764334/6c5fcbc1-8ec1-4c13-bb8c-a3cfa900c59b)

**Comment by SoyDiego** [comment] 2023-10-25 17:45
> @SoyDiego @melloware Thanks for your reply. I create a sandbox link, used Next js templeate. And then I installed two dependencies, which are `primeicons` and `primereact`. I replaced the default code with the Pagination component. Waiting for the server to start completely, and you can reproduce the issue by refreshing the page. There is the sandbox link: https://codesandbox.io/p/sandbox/agitated-butterfly-td3m97?file=%2Fapp%2Fpage.tsx%3A6%2C33 Thanks again.

Sorry I don't know the solution :(

**Comment by melloware** [comment] 2023-10-26 18:33
@aholeye it doesn't look like you followed the Tailwind instructions?  https://primereact.org/tailwind/

**Comment by gucal** [comment] 2023-11-10 12:42
Hi there,

Before proceeding, it's highly recommended that you visit primereact.org/tailwind and carefully review the available documentation.

You can use this repo (https://github.com/primefaces/primereact-examples/tree/main/nextjs-styled-tailwind) as a base for the correct setup.

If your problem continues to persist, please don't hesitate to inform us.

Thank you.

**Comment by melloware** [comment] 2023-11-10 12:55
@aholeye your issue is FOUC: https://github.com/primefaces/primereact/issues/5188

**Comment by melloware** [comment] 2023-11-10 12:55
I will close this for now as its basically a duplicate of #5188

**Closed by melloware** 2023-11-10 12:55 UTC
Labels: Status: Needs Reproducer, Component: Tailwind
