### ISSUE TITLE
DataTable: row selection checkbox not getting checked

### ISSUE THREAD

**Issue by mtsh1000** [primefaces/primereact#6208] opened 2024-03-21 16:25 UTC
### Describe the bug

DataTable: row selection checkbox not getting checked

### Reproducer

https://primereact.org/datatable/#checkbox_row_selection

### PrimeReact version

10.5.3

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment] 2024-03-21 18:42
PR submitted

**Comment by Alonsormm** [comment] 2024-03-27 15:43
Is there any news about this bug? I saw that they published a PR, but they closed it. The problem is even in the official documentation.

https://primereact.org/datatable/#checkbox_row_selection

**Comment by melloware** [comment] 2024-03-27 16:37
yep Primetek is aware of the issue and closed my PR i think they are going to fix it the correct way.

**Comment by melloware** [comment] 2024-03-29 22:05
Fixed in 10.6.2 try it again please: https://primereact.org/datatable/#checkbox_row_selection

**Closed by melloware** 2024-03-29 22:05 UTC
Labels: Type: Bug
