### ISSUE TITLE
PanelMenu

### ISSUE THREAD

**Issue by primperfum** [primefaces/primereact#2436] opened 2021-11-15 13:44 UTC
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ X ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
PanelMenu collapsing everytime I click on an item and function is called.

**Expected behavior**
Add a prop to PanelMenu so it doesnt collapse everytime the item is clicked, there should be an option to keep items open after function. 

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:**

17.0.1

* **PrimeReact version:**

7.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by melloware** [comment] 2022-04-16 15:24
Duplicate of: https://github.com/primefaces/primereact/issues/1159

**Closed** 2022-04-16 15:24 UTC
Labels: duplicate
