### ISSUE TITLE
Dropdown: null and empty string value

### ISSUE THREAD

**Issue by mtsh1000** [primefaces/primereact#7081] opened 2024-08-24 08:54 UTC
### Describe the bug

Dropdown select returns whole item object when value is null or empty string. Strangely it behaves correctly when val === false or 0

### Reproducer

https://stackblitz.com/edit/4db3vn?file=src%2FApp.jsx

### System Information

primereact 10.8.2

**Comment by melloware** [comment] 2024-08-24 11:06
Duplicate of https://github.com/primefaces/primereact/issues/7064

**Closed** 2024-08-24 11:35 UTC
Labels: Type: Bug
