### ISSUE TITLE
Datatable: Resize column fit mode not working

### ISSUE THREAD

**Issue by petrosD93** [primefaces/primereact#4731] opened 2023-08-03 12:20 UTC
### Describe the bug

When trying to resize the datatable columns with resize mode fit, no change is observed. Resize is not working.
This can be also reproduced on your showcase page https://primereact.org/datatable/

### PrimeReact version

9.6.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment] 2023-08-03 12:38
Duplicate of https://github.com/primefaces/primereact/issues/4471 fixed for 10.0.0

**Closed by melloware** 2023-08-03 12:38 UTC
Labels: Resolution: Duplicate

**Comment by melloware** [comment] 2023-08-03 12:52
I don't work for PrimeTek but I do know the only way you can force something to be backported to 9 is through a PRO account. See: https://primereact.org/support/
