### ISSUE TITLE
Charts: re-renders when props are passed from parent component

### ISSUE THREAD

**Issue by sank09** [primefaces/primereact#2623] opened 2022-02-01 07:39 UTC
I'm submitting a ... (check one with "x")
```
PrimeReact chart re-renders unnecessarily when props are passed from parent component
```

**Codesandbox Case (Bug Reports)**
Please check the below link for comparison with react-chartjs-2

https://codesandbox.io/s/quirky-tharp-rdz3z?file=/src/App.js

**Steps for reproduction on codesandbox**

- Click on the ```Add Data``` button to update the chart component with new data props from parent component.
- The chart should get updated with new data

**Current behavior**
PrimeReact Chart re renders when props are passed from parent component .
The same behaviour with react-chartjs-2 library is working fine.

**Expected behavior**
The chart imported from PrimeReact should not be re-render but when the data is set from props in case the chart should be updated not re rendered.

***React version:**
17.0.2

***PrimeReact version:**
7.2

**Comment by ashinde-rocket** [comment] 2022-02-01 07:50
@cagataycivici Can you please check and let us know?

- Amol Shinde (Rocket Software)

**Comment by melloware** [comment] 2022-02-01 14:16
@ashinde-rocket not a bug See my sandbox...

https://codesandbox.io/s/blissful-mclaren-3w8x9

By default React CHarts has `animation` disabled I enabled it with...

```xml
<Line options={optionsA} data={basicData} animation={true} />
```

And now the two charts are identical.   So if you want animation off in PrimeReact simply pass it in in your JSON options.

**Comment by ashinde-rocket** [comment] 2022-02-02 02:26
Thank you @melloware , We will update our code accordingly.

**Comment by melloware** [comment] 2022-02-02 03:59
You can close this ticket

**Comment by sank09** [comment] 2022-02-02 09:36
@melloware The Prime React destroys the chart on every render and creates a new one whereas we just need to update the add for Example Adding the data to Existing data.
You can check when the Add data button is clicked the react-chartjs-2 gets updated whereas the primeReact chart destroys and creates a new one.

**Comment by melloware** [comment] 2022-02-02 10:03
Ok let me look did you update your code sandbox?

**Comment by sank09** [comment] 2022-02-02 10:40
> Ok let me look did you update your code sandbox?
I did not made any changes in the sandbox .

**Comment by melloware** [comment] 2022-02-02 12:31
OK I am looking at your example and clicking Add Data and it looks like both charts are doing the same thing?  How can you tell one is doing a destroy and the other one is not?

**Comment by melloware** [comment] 2022-02-02 12:33
I cloned your reproducer and made the animation the same and I can't see any difference.

See: https://codesandbox.io/s/wandering-dawn-zzfgs

**Comment by sank09** [comment] 2022-02-18 06:02
I have added another example that shows when the props are passed from parent to child component which has the PrimeReact chart gets re rendered.

Please check the below sandbox link for reference 
https://codesandbox.io/s/great-chebyshev-s8rvz2?file=/src/ChartComponent.js

Steps for reproduction:-
- Click on the  `Change Title` Button to modify the title only.


**Expected Results:-**
The Title gets changed and the Prime React chart does not get re rendered.

**Actual Results:-**
The Title gets changed and the Prime React chart gets re rendered while the other one does not get re rendered which is correct

**Comment by melloware** [comment] 2022-02-18 14:00
Excellent this is a much better reproducer!

**Comment by melloware** [comment] 2022-04-22 16:53
@sank09 got to the bottom of your problem.

Fixed reproducer: https://codesandbox.io/s/priceless-leavitt-n16ohj

The issue is you needed to put the `options` in `useState` as well as PrimeReact chart uses `memoization` to check for changes in the incoming properties and only re-render then.   Because its a JSON object and deeply nested the memoization of your constant was always reporting different.  However when its stored in `useState` React can optimize and know whether the options have changed or not!

**Closed** 2022-04-22 16:54 UTC
Labels: workaround
