### ISSUE TITLE
InputTextarea in 8.5.0 doesn't work with typescript

### ISSUE THREAD

**Issue by Strandedpirate** [primefaces/primereact#3283] opened 2022-09-10 17:35 UTC
### Describe the bug

The `InputTextarea` is getting flagged by typescript on the `rows` property. CRA with plain-old-javascript doesn't have this problem, but CRA w/Typescript does.

Fresh react-create-app with the typescript template:
![image](https://user-images.githubusercontent.com/1452996/189495021-0ab7b9c1-9f80-4b0b-8a18-ab79687877e5.png)

yarn dev
![image](https://user-images.githubusercontent.com/1452996/189495027-aff921ad-d339-41fd-b9ec-dbd847dbca83.png)

### PrimeReact version

8.5.0

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Browser(s)

ALL

### Steps to reproduce the behavior

1.  `npx create-react-app primereact-test-typescript --template typescript`
2. `cd primereact-test-typescript`
3. `yarn add primereact`
```
import { InputTextarea } from 'primereact/inputtextarea'
import { useState } from 'react'
...

  const [note, setNote] = useState('hello');
...
  <InputTextarea
    style={{ height: '100%' }}
    rows={5}
    cols={60}
    value={note}
    onChange={(e) => setNote(e.target.value)}
          />
```

### Expected behavior

No error during build or runtime

**Comment by melloware** [comment] 2022-09-10 23:00
Duplicate of #3252 already fixed

**Closed** 2022-09-10 23:01 UTC
Labels: Resolution: Duplicate
