### ISSUE TITLE
Responsive Carousel Item's Disapearing when using more than 2 items.

### ISSUE THREAD

**Issue by brandozer1** [primefaces/primereact#5643] opened 2023-12-24 18:50 UTC
### Describe the bug

When using more than 2 items there is a flicker when scrolling and items disappear when the viewport size changes. 

### PrimeReact version

9.5.0

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Create a carousel with fundamental responsive options. 2. give the bare minimum elements as items. 3. create a breakpoint with at least 3 items. 4. change viewport/scroll. 

You will notice the items can very easily become glitchy, disappear, and sometimes don't render at all.

### Expected behavior

1. Create a carousel with fundamental responsive options. 2. give the bare minimum elements as items. 3. create a breakpoint with at least 3 items. 4. change viewport/scroll. 

Items scroll without glitching, flickering, squishing, or hesitation when rendering.

**Comment by melloware** [comment] 2023-12-24 21:21
Duplicate of https://github.com/primefaces/primereact/issues/5166 ??

**Closed** 2023-12-25 13:32 UTC
Labels: Status: Needs Triage
