### ISSUE TITLE
AutoComplete: can't remove item

### ISSUE THREAD

**Issue by TheArcherST** [primefaces/primereact#4848] opened 2023-08-30 17:14 UTC
### Describe the bug

Can't remove item from AutoComplete component, added due external event, if this action was performed two times.

Context: I want to implement automatically undo of actions during filling a data table. Table uses this component as body for some columns. After canceling of the last action (cancel element removing), I can't remove it again by mouse click.

### Reproducer

https://codesandbox.io/s/primereact-test-forked-dvsf96?file=/src/index.js

### PrimeReact version

9.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Press on `Add item` button.
2. Remove item from autocomplete
3. Press to button `Add item` again
4. Try to remove item.

### Expected behavior

I can remove item.

**Comment by melloware** [comment] 2023-08-30 17:25
Good reproducer. Definitely looks like a bug.

**Comment by akshayantony55** [comment] 2023-08-31 19:36
I will work on this @melloware

**Comment by melloware** [comment] 2023-08-31 19:44
Assigned to you!

**Closed** 2023-09-01 13:26 UTC
Labels: Type: Bug
