### ISSUE TITLE
Datatable: using rowsPerPageOptions produces error when clicked

### ISSUE THREAD

**Issue by ashens1** [primefaces/primereact#6553] opened 2024-05-03 01:53 UTC
### Describe the bug

When using the Datatable rowsPerPageOptions, the dropdown errors out when clicked:
`
Objects are not valid as a React child (found: object with keys {label, value}). If you meant to render a collection of children, use an array instead.`

This is even on the main website! When clicking on the "choose" dropdown it errors

![image](https://github.com/primefaces/primereact/assets/127710395/373cbeae-4e25-4f33-b4a1-9f2c30f00471)

![image](https://github.com/primefaces/primereact/assets/127710395/7e634891-b701-4291-8513-f00edaa20097)

### PrimeReact version

10.6.4

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by Rekl0w** [comment] 2024-05-03 06:03
Duplicate of #6531. It will be fixed on 10.7

**Closed** 2024-05-03 13:55 UTC
Labels: Resolution: Duplicate

**Comment by melloware** [comment] 2024-05-03 13:59
Please try 10.6.5
