### ISSUE TITLE
Datatable : Cell Edit Issue

### ISSUE THREAD

**Issue by anatoliaDev** [primefaces/primereact#4969] opened 2023-09-26 08:24 UTC
### Describe the bug

This is the link for issue explanation . [https://stackoverflow.com/questions/77177398/cell-edit-issue-with-prime-react](https://stackoverflow.com/questions/77177398/cell-edit-issue-with-prime-react)

With latest version of PrimeReact ( 9.6.2 ) edit cells are only saving it with enter in keyboard. If I didn't enter in keyboard and select outside of the cell the data which I wanted to add is removing itself. Because of that with " onCellEditComplete " method I am getting empty value after data has been changed. Normally I was using 9.2.3 and I could able to save data to table even if I selected to outside of the cell. Right now users have to enter for each cell to save data. And I think this is not user friendly. The sandbox generated from your team. You can see what I mean if you don't enter in the cell and click other cells or anywhere the data won't be saved.

### Reproducer

https://codesandbox.io/s/cdemf3

### PrimeReact version

9.6.2

### React version

18.x

### Language

ALL

### Build / Runtime

Next.js

### Steps to reproduce the behavior

Click To table cell. Change anything in cell and don't hit enter in keyboard. Select to other cells or click to any empty space on screen. The data which you entered would be gone by that.

### Expected behavior

The data should be saved even if I entered or clicked other cells or other empty spaces on screen.

**Comment by melloware** [comment] 2023-09-26 12:10
I am pretty sure this is a duplicate of https://github.com/primefaces/primereact/issues/4648 which is fixed for 10.0.0

**Closed** 2023-09-26 12:10 UTC
Labels: Resolution: Duplicate

**Comment by anatoliaDev** [comment] 2023-09-26 12:13
> I am pretty sure this is a duplicate of #4648 which is fixed for 10.0.0


@melloware  It's not duplicate. It's not about clicking other row. When you click to empty space on screen after set data you would see that It's not saving it.
