### ISSUE TITLE
Dropdown: Opened panel doesn't update it's position when used in the Bootstrap modal

### ISSUE THREAD

**Issue by domino2** [primefaces/primereact#3656] opened 2022-11-16 10:14 UTC
### Describe the bug

When dropdown used in the Bootstrap modal window and it's panel is shown, the scrolling in the modal window causes reposition of the dom elements, but the panel is in fixed position.

### Reproducer

https://codesandbox.io/s/happy-albattani-ngqnfc

### PrimeReact version

8.7.2

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. In the CodeSanbox example, click on "Show Modal" button
2. Click on dropdown to see the option list
3. Move the mouse pointer to not appear upon the panel (to scroll down the page, not the list)
4. Scroll the page and the panel is in fixed position, on the other hand the dropdown element is moving

### Expected behavior

The panel should to be rendered on same position as it's parent dropdown input.

**Comment by melloware** [comment] 2022-11-16 12:42
Duplicate of https://github.com/primefaces/primereact/issues/2683 please go upvote that issue

**Closed by melloware** 2022-11-16 12:42 UTC
Labels: Status: Needs Triage
