### ISSUE TITLE
RadioButton: e.value in onChange method return boolean instead of object type in "value" field

### ISSUE THREAD

**Issue by GuillaumeC** [primefaces/primereact#5034] opened 2023-10-04 13:33 UTC
### Describe the bug

Using a Dynamic RadioButton.
Insert array of object.
In onChange methode, call e.value will return boolean Type instead of object type.

Open https://primereact.org/radiobutton/#dynamic sample in sandbox, and the bug is present and visible.

### Reproducer

https://codesandbox.io/s/tjprw4

### PrimeReact version

10.0.2

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Firefox 118.0.1

### Steps to reproduce the behavior

Using a Dynamic RadioButton and call in onChange Method e.value

### Expected behavior

e.value return the selected object with his own type

**Comment by melloware** [comment] 2023-10-04 13:46
Duplicate of https://github.com/primefaces/primereact/issues/4983

**Closed by melloware** 2023-10-04 13:46 UTC
Labels: Resolution: Duplicate
