### ISSUE TITLE
DataTable grouping rows with similar names, more than one field at a time

### ISSUE THREAD

**Issue by rjcefalo** [primefaces/primereact#1039] opened 2019-10-09 13:04 UTC
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**
In the DataTable component when grouping rows with the same name allows so group just one field

**Expected behavior**
Been able to sort more than one field

**Minimal reproduction of the problem with instructions**
Please check image to illustrate current and expected behavior

Current
![Field 1](https://user-images.githubusercontent.com/19534909/66483635-c65d0880-eaa5-11e9-9254-c10ffb6cf75c.png)
---------------------------------------------------------
![Field 2](https://user-images.githubusercontent.com/19534909/66483649-cbba5300-eaa5-11e9-9425-7a4758c2217d.png)

Expected
![Field 1+2](https://user-images.githubusercontent.com/19534909/66483655-ceb54380-eaa5-11e9-973c-3f9eaa403add.png)

* **React version:**
16.9.0

* **PrimeReact version:**
3.1.8

* **Browser:**
All
 
* **Language:**
ES6/7

**Comment by mertsincan** [comment] 2019-10-14 08:34
Hi,
Thanks a lot for the screenshots, could you please attach a codesandbox link for us to replicate? You can use the following link;
https://codesandbox.io/s/qjx332qq4

**Comment by rjcefalo** [comment] 2019-10-14 09:30
Here is an example of the current behaviour:
[https://codesandbox.io/embed/primereact-test-53eqz](url)

At lines 39 and 53 in the index.js file it specifies a single field that can be merged by columns.
The desired behaviour would be been able to merge more than one field at the time in the same table

**Comment by RaquelAlgoNew** [comment] 2019-11-28 11:21
Is it fixed yet? I need something similar

**Comment by kunal52** [comment] 2020-01-10 12:16
Did you find any solution?

**Comment by tom-son** [comment] 2020-04-23 00:19
Would also be interested.

**Comment by Vitalii-Pidoprygora** [comment] 2022-07-27 14:32
Lack of this feature is kind off showstopper for my project. Would be glad to see it in upcoming release.

**Comment by melloware** [comment] 2022-11-14 21:57
Duplicate of https://github.com/primefaces/primereact/issues/619

**Closed by melloware** 2022-11-14 21:57 UTC
Labels: Type: New Feature
