### ISSUE TITLE
TreeSelect: Clear Icon Misplacement

### ISSUE THREAD

**Issue by chiefdeals** [primefaces/primereact#5020] opened 2023-10-03 16:42 UTC
### Describe the bug

Misalignment on 'clear icon' for TreeSelect component - on LTR aligns to the far left with no padding. Expected, align right, padding/margin right

Seen in documentation

Safari, Firefox, Chrome - versions irrelevant as they're all identical

### Reproducer

https://primereact.org/treeselect/

### PrimeReact version

current

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Browser(s)

 Safari, Firefox, Chrome - versions irrelevant as they're all identical

### Steps to reproduce the behavior

go to https://primereact.org/treeselect/

go to clear icon

derp

### Expected behavior

Misalignment on 'clear icon' for TreeSelect component - on LTR aligns to the far left with no padding. Expected, align right, padding/margin right

**Comment by melloware** [comment] 2023-10-03 16:45
Duplicate of https://github.com/primefaces/primereact/issues/5012

Which is waiting on this fix: https://github.com/primefaces/primereact-sass-theme/pull/32

**Comment by chiefdeals** [comment] 2023-10-03 16:51
Apologies for duplicate, kinda new to this world.

**Closed** 2023-10-14 10:41 UTC
Labels: Component: Theme
