### ISSUE TITLE
Dropdown: No longer shows options with simple primitive values

### ISSUE THREAD

**Issue by wrightdean** [primefaces/primereact#6591] opened 2024-05-08 12:48 UTC
### Describe the bug

The Dropdown should be able to be supplied with a simple array of strings, and those strings be populated in the options list. This no longer works but was working in 10.6.3.

### Reproducer

https://stackblitz.com/edit/71dwgk?file=src%2FApp.tsx

### PrimeReact version

10.6.5

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Steps to reproduce the behavior

Click on Dropdown element. See that the list has been populated with the correct number of entries, but they are empty.

### Expected behavior

The options list should list the options given in the simple string[].

**Comment by melloware** [comment] 2024-05-08 13:01
Duplicate of https://github.com/primefaces/primereact/issues/6578 fixed for next release.

**Closed** 2024-07-04 11:37 UTC
Labels: Resolution: Duplicate
