### ISSUE TITLE
 Z-index is incorrectly set

### ISSUE THREAD

**Issue by RomanSamohwal** [primefaces/primereact#2322] opened 2021-09-24 10:55 UTC
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/intelligent-haibt-xgbrn?file=/src/App.js

**Current behavior**

The Dropdown component is drawn behind the "Header2" Dialog component. The z-index is not calculated correctly 
 ![{C5B32E54-5DA6-4E20-836C-5B71F16A8F9B} png](https://user-images.githubusercontent.com/61876483/134659940-810116dc-9cfa-4b9f-9236-b8b42ab9b25e.jpg)
This is linked by a Tooltip in a Button component that has a z-index. If you remove Tooltip then everything works correctly
![{CAFBF328-08C9-4BEE-99CF-C040C25022DF} png](https://user-images.githubusercontent.com/61876483/134661596-05123d33-9b4a-43a7-a131-63590728a9c7.jpg)

**Expected behavior**

    
![Expected behavior](https://user-images.githubusercontent.com/61876483/134660427-634be760-c9b1-4e0e-bc3d-2990cf85ab91.jpg)

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:**

React version:
17.0.2
* **PrimeReact version:**

PrimeReact version:
6.5.1
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by vpsgvitor** [comment] 2021-09-24 11:40
https://github.com/primefaces/primereact/issues/2266

**Comment by mertsincan** [comment] 2021-11-03 07:01
Duplicate of #2266

**Closed by mertsincan** 2021-11-03 07:01 UTC
