### ISSUE TITLE
Dialog and calendar are missing type=button

### ISSUE THREAD

**Issue by RikSlendebroek** [primefaces/primereact#1139] opened 2020-01-08 09:25 UTC
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/dialog-with-form-ddb51?fontsize=14&hidenavigation=1&theme=dark

**Current behavior**

We have forms around dialogs so we can use the submit function for the buttons in the footer. 
The dialog closes on pressing enter within an input field without calling the submit of the form when you add a clossable={true} and an onHide. This is because there is no type added so the close button is registered as submit. This problem of not calling the submit function also occurs when you have a callendar within your form

(you wll probally face the same problem if you have a maximizable)

**Expected behavior**

Pressing enter on the input fields would call the submit function and not the onHide.

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

* **React version:**

* **PrimeReact version:**

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by mertsincan** [comment] 2020-01-17 08:27
Duplicate of #1155

**Closed by mertsincan** 2020-01-17 08:27 UTC
