### ISSUE TITLE
Calendar: Selecting a date needs 2 clicks

### ISSUE THREAD

**Issue by RosteckMarius** [primefaces/primereact#4757] opened 2023-08-09 14:26 UTC
### Describe the bug

When selecting a date in the calendar, only the second click sets a new date as value.

### Reproducer

https://codesandbox.io/s/romantic-cherry-t7jydj

### PrimeReact version

9.6.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Click on the calendar input field
2. Click on a date (nothing should happen)
3. Click on a date again (now the date gets selected)

### Expected behavior

The date should be selected on the first click.

**Comment by melloware** [comment] 2023-08-09 14:44
Duplicate of https://github.com/primefaces/primereact/issues/4568 already fixed for 10.0.0

**Closed** 2023-08-09 14:44 UTC
Labels: Resolution: Duplicate
