### ISSUE TITLE
DataTable with VirtualScroller: virtual scroller viewport does not get larger than its initial size

### ISSUE THREAD

**Issue by dmit4git** [primefaces/primereact#5130] opened 2023-10-21 04:30 UTC
### Describe the bug

Changing size of DataTable's VirtualScroller by setting `scrollHeight` doesn't work if you make it greater than initial value. 

![Screencast from 10-21-2023 01_04_26 AM](https://github.com/primefaces/primereact/assets/48034657/4344bf61-99ed-4070-af21-f878286e50c3)

Looks like virtual scroller has a check against value of a reference variable on this [line](https://github.com/primefaces/primereact/blob/0aca1e9ed09ee75ba0a13127a6968185e09a6de5/components/lib/virtualscroller/VirtualScroller.js#L243).

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-y5yh7t

### PrimeReact version

10.0.5

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome, Firefox

### Steps to reproduce the behavior

1. Click the "scrollHeight + 200px" button
2. See that `scrollHeight` state used to set `scrollHeight` property of the datatable has increased, but viewport of the datatable hasn't

### Expected behavior

Size of viewport of the datatable corresponds to the value of `scrollHeight` property, even if it's greater that its initial value.

**Comment by dmit4git** [comment] 2023-10-21 20:43
This issue looks very similar to #4413, may be the same bug.

**Comment by melloware** [comment] 2023-10-22 11:59
Duplicate of #4413 thanks for finding that.  It definitely looks the same so I would subscribe to that ticket.  Thanks for the report.

**Closed by melloware** 2023-10-22 11:59 UTC
Labels: Type: Bug
