### ISSUE TITLE
TreeTable: Plenty of warnings in codesandbox demos

### ISSUE THREAD

**Issue by patryk0493** [primefaces/primereact#5542] opened 2023-12-07 08:14 UTC
### Describe the bug

I have tried the TreeTable component in my project, but it throws a lot of console warnings. Then I tried to reproduce it in a sandbox environment, the demos on https://primereact.org/treetable/ I have the same issue.

<img width="1712" alt="image" src="https://github.com/primefaces/primereact/assets/6117551/3f7dfc67-bd03-4da5-984a-b47ea7b74f55">

Is that behavior common?

### Reproducer

https://codesandbox.io/p/sandbox/primereact-demo-89kd8z?file=%2Fsrc%2FApp.js%3A87%2C31

### PrimeReact version

latest

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

All

### Steps to reproduce the behavior

1. Open the link: https://codesandbox.io/p/sandbox/primereact-demo-89kd8z?file=%2Fsrc%2FApp.js%3A82%2C42 
2. Open demo page console

### Expected behavior

No warning in a console is present

**Comment by melloware** [comment] 2023-12-07 12:10
Its already fixed in main.

**Comment by melloware** [comment] 2023-12-07 12:11
Duplicate of https://github.com/primefaces/primereact/issues/5427

**Closed as completed by melloware** 2023-12-07 12:10 UTC
Labels: Type: Bug
