### ISSUE TITLE
RadioButton: the inner dot is not centered for the scaled screen

### ISSUE THREAD

**Issue by mikejav** [primefaces/primereact#3182] opened 2022-08-24 13:42 UTC
### Describe the bug

When you are using the browser zoom feature - for some zoom factors the inner dot is not centered.
![image](https://user-images.githubusercontent.com/25515470/186432944-7ba63b43-1408-4c64-9449-e6396423308b.png)

125%:
![image](https://user-images.githubusercontent.com/25515470/186433201-0e4033a6-53ca-4f85-afb6-9aee74ac34cf.png)

90%:
![image](https://user-images.githubusercontent.com/25515470/186433341-166ee320-3914-49fa-a770-0775c988c1ca.png)

### Reproducer

https://codesandbox.io/s/primereact-test-forked-ky91xc?file=/src/index.js

### PrimeReact version

7.2.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Any

### Browser(s)

Chrome 104

### Expected behavior

The inner dot is centered.

**Comment by melloware** [comment] 2022-08-24 14:35
Duplicate of: https://github.com/primefaces/primereact/issues/2863

**Closed by melloware** 2022-08-24 14:35 UTC
Labels: Status: Needs Triage
