### ISSUE TITLE
Dropdown Item list responsive issue

### ISSUE THREAD

**Issue by Bilal-Bangash** [primefaces/primereact#2574] opened 2022-01-12 10:25 UTC
![image](https://user-images.githubusercontent.com/53056567/149122625-82b05f3b-ed3a-41fe-9d5c-38c0eeeb7bda.png)
list items for larger text is not responsive. Above screenshot from Autocomplete Dropdown but it's in other Dropdown component too

**Comment by melloware** [comment] 2022-01-12 12:53
Just set it with `panelStyle` or `panelStyleClass` you can change the width to whatever you want.  I don't understand what the issue is?

**Comment by Bilal-Bangash** [comment] 2022-01-12 13:00
> Just set it with `panelStyle` or `panelStyleClass` you can change the width to whatever you want. I don't understand what the issue is?

if you check the width of item list 
![image](https://user-images.githubusercontent.com/53056567/149144906-bd850f20-ec85-4a57-be1c-c26090111151.png)
which is larger then input field this need to be fixed

**Comment by melloware** [comment] 2022-01-12 13:03
Yes what I am saying is why not just set it with `panelStyle` or `panelStyleClass`  by default it is the width of the LARGEST item in the list which is good default behavior.  

![image](https://user-images.githubusercontent.com/4399574/149145356-676c884c-cb40-4108-9b38-a6fbb155ee90.png)


That is the correct default behavior if you want different behavior then set it with the `panel` CSS properties provided.

**Comment by pierrefabarius** [comment] 2022-09-28 13:09
I think @Bilal-Bangash is right. 
Using the multiselect component (same data) the width is fine by default.

![image](https://user-images.githubusercontent.com/29637548/192786452-9ce1ead6-22f3-494f-a6af-b57f41975f6d.png)
(top dropdown, bottom multiselect)

**Comment by melloware** [comment] 2022-09-28 13:14
@pierrefabarius your screenshot is showing the closed Dropdown or Multiselect.  What the ticket is  the user wants the dropdown Panel to be the same width as the dropdown.

**Comment by melloware** [comment] 2022-12-07 16:37
Going to close this as I am still confused what the issue is and panel and panelStyle handle the sizing if you want to override defaults.

**Closed by melloware** 2022-12-07 16:37 UTC
Labels: Type: Enhancement, Status: Discussion

**Comment by raDiesle** [comment] 2023-02-08 09:27
this is mentioned in 9.0.0-beta.1 to be fixed. Was there a code change and what is the change about?

Dropdown Item list responsive issue https://github.com/primefaces/primereact/issues/2574

**Comment by melloware** [comment] 2023-02-08 09:56
I removed it from those release notes. There was no fix simply set PanelStyle.

**Comment by noahfaro** [comment] 2024-08-06 20:14
What you are saying is true in that we can set the panel width via PanelStyle, but it is not useful for dynamic widths of the autocomplete component. 

Setting the width to 100% for the Autocomplete's root for example does properly size it to the width of its parent, however setting the width to 100% of the panel does not do that as the panel is appended to the DOM - resulting in the 100% being the width of the viewport, not the width of the Autocomplete parent container.

Thus, the only way to actually set the width of the panel is to give it a pixel width, which should not be the case. This is the error that I believe the others are also having.
