### ISSUE TITLE
Improve PanelMenu implementation

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primereact#1847] opened 2021-03-05 10:38 UTC
Change it according to Mutable or Immutable value.

**Comment by lzoostaoo** [comment] 2021-06-02 09:08
@mertsincan 
PanelMenu has internal state. I think that it should be managed externally also via props.
This is done in several place like in Panel or in Accordion it would be nice if it was also the case in PanelMenu ! 
This library is really great! keep it up ! 👍

**Comment by melloware** [comment] 2022-04-16 15:23
Duplicate of: https://github.com/primefaces/primereact/issues/1159

**Closed** 2022-04-16 15:24 UTC
Labels: duplicate
