### ISSUE TITLE
Dropdown does not respect optionValue property (since 10.7.0)

### ISSUE THREAD

**Issue by rafalwojdowski** [primefaces/primereact#6827] opened 2024-07-04 06:30 UTC
### Describe the bug

Dropdown stopped respecting optionValue property since PrimeReact 10.7.0. Even if the optionValue property is set, the entire object is returned.

### PrimeReact version

10.7.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by Rekl0w** [comment] 2024-07-04 09:29
Duplicate of #6822.

**Closed** 2024-07-04 11:37 UTC
Labels: Resolution: Duplicate
