### ISSUE TITLE
DropDown (Advanced with Templating, Filtering and Clear Icon)

### ISSUE THREAD

**Issue by Hamza-malikx** [primefaces/primereact#3466] opened 2022-10-11 12:27 UTC
### Describe the bug

Hey, guys for this awesome package. I am actually new to react prime and kinda facing an issue while use "Advanced with Templating, Filtering and Clear Icon" Dropdown.
![image](https://user-images.githubusercontent.com/83468742/195089327-0a91a7ae-0a94-4ebd-b0f1-9b9920fb78dc.png)
Any help would be appreciated.

### PrimeReact version

8.6.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by ulasturann** [comment] 2022-10-11 13:26
Hi @Hamza-malikx ,
Thanks for your report. Could you please send a reproducer via codesandbox or derivatives, please?
It's looking like the issue is related to the types of the Dropdown component.

Also, you can check the JSX element which is assigned to valueTemplate to be sure that it is wrapped with a container element(JSX.Element is not assignable...).

**Comment by melloware** [comment] 2022-10-11 13:37
I use Dropdown in TypeScript without issue in all my projects so yes a Code Sandbox reproducer would be nice.

**Comment by melloware** [comment] 2022-10-11 13:54
it looks like its an issue with your `valueTemplate`

**Comment by Hamza-malikx** [comment] 2022-10-12 05:39
@melloware @ulasturann solved. Thanks guys

**Closed** 2022-10-12 06:19 UTC
Labels: Resolution: Needs More Information
