### ISSUE TITLE
Tailwind CSS issue

### ISSUE THREAD

**Issue by C0ZEN** [primefaces/primereact#4987] opened 2023-09-29 13:23 UTC
### Describe the bug

In v9, to style Prime I only need to add these into a `.scss` file.

```scss
@import 'primereact/resources/themes/lara-light-blue/theme.css';
@import 'primereact/resources/primereact.min.css';
```

In v10.0.2, this is like the app is set to `unstyled: true`, since no CSS is loaded, at all!
Though, I'm still able to see that the Prime classes are added into the DOM.

### PrimeReact version

10.0.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Expected behavior

The styles are loaded.

**Comment by melloware** [comment] 2023-09-29 14:48
I can't reproduce?  https://stackblitz.com/edit/react-bjcylz?file=src%2FApp.js,src%2Findex.js

Can you edit my stackblitz to show the issue?

**Comment by C0ZEN** [comment] 2023-09-29 14:51
I can try, though it may not be that easily reproducible since I'm working on a Nx+Vite project.

**Comment by melloware** [comment] 2023-09-29 15:05
ok I think PrimeTek is going to provide guidance on using TailWind with the new `unstyled` mode.

**Comment by melloware** [comment] 2023-09-29 15:06
Actually instructions here: https://primereact.org/tailwind/

**Comment by C0ZEN** [comment] 2023-09-29 15:21
I don't get how come my app is broken just because I'm already using Tailwind.

My point is: tailwind was and should still be working WITH a theme, and the docs actually refer to using tailwind as unstyled.
This is not what I wish 🤔

**Comment by melloware** [comment] 2023-09-29 15:35
OK then provide a reproducer like I did...

**Comment by melloware** [comment] 2023-09-29 15:36
Without a reproducer developers can't really debug.

**Comment by C0ZEN** [comment] 2023-10-02 08:32
@melloware here is a reproduction https://codesandbox.io/p/sandbox/prime-10-tailwind-broken-kg22lr

**Comment by melloware** [comment] 2023-10-02 11:43
Yep it is because PrimeReact has reduced its specificity by adding `@layer PrimeReact`: https://github.com/primefaces/primereact/issues/4959

So you can see your TailWind styles are now "winning" over the PrimeReact Theme:
![image](https://github.com/primefaces/primereact/assets/4399574/85d577a6-b3c9-4cfe-a1b6-f32ce1b9a087)

![image](https://github.com/primefaces/primereact/assets/4399574/c4a93c6f-dd62-413f-bcef-3227c5246736)

**Comment by yrios-cdd** [comment] 2023-10-04 22:26
> over the PrimeReact Theme

@melloware I have the same issue. I use primereact in an app that also uses Bootstrap, when upgrading to version 10.0.2 the styles are breaking because Bootstrap styles are "winning" over the PrimeReact Theme. In previous versions of Primereact this did not happen, Primereact styles had priority over bootstrap styles.

**Comment by melloware** [comment] 2023-10-04 22:56
Ok I assigned to PrimeTek to investigate.

**Comment by melloware** [comment] 2023-10-05 21:48
Also it looks like PrimeVue has a more up to date doc on how to properly use Layers with TailWind: https://primevue.org/theming/#tailwind

**Comment by areski** [comment] 2023-10-11 12:12
Same issue, using already Tailwind, as mentioned by @C0ZEN commenting tailwind/base will bring the style back of primereact but it will then break my application.
Thanks in advance for the help

**Comment by mrstexx** [comment] 2023-10-19 14:50
Are there any news on this issue? I have the same problem that tailwind layer overrides the primereact theme layer.

Changing the order of layers in tailwind.css doesn't solve the problem:
`@layer tailwind-base, primereact, tailwind-utilities;

@layer tailwind-base {
  @tailwind base;
}

@layer tailwind-utilities {
  @tailwind components;
  @tailwind utilities;
}`

**Comment by melloware** [comment] 2023-10-19 14:55
I pinged PrimeTek directly asking them to look at this.

**Comment by oscarviq** [comment] 2023-10-19 15:04
+1 was trying out primeReact today but it's honestly a little wonky.

**Comment by habubey** [comment] 2023-10-19 15:16
> +1 was trying out primeReact today but it's honestly a little wonky.

https://github.com/primefaces/primereact-examples/tree/main/nextjs-unstyled

For me it works fine.

**Comment by melloware** [comment] 2023-10-19 15:18
No worries yeah now that you have it working I think its OK to report individual issues and you can use that StackBlitz to reproduce and add in the tickets.  This is such a new feature there are going to be a few kinks. 😄

**Comment by kabalan-datapostie** [comment] 2023-10-19 20:16
> @melloware I have the same issue. I use primereact in an app that also uses Bootstrap, when upgrading to version 10.0.2 the styles are breaking because Bootstrap styles are "winning" over the PrimeReact Theme. In previous versions of Primereact this did not happen, Primereact styles had priority over bootstrap styles.

I'm having the exact same issue.

An elegant way to solve this would be to add a layer around Bootstrap and prioritise the primereact layer over bootstrap, but this is proving to be a struggle.

For back-portability, it would be great to have a way to disable the primereact @layer. Is there a way to achieve something like that with `import { PrimeReactProvider } from "primereact/api";` and Bootstrap?

**Comment by SoyDiego** [comment] 2023-10-24 12:16
I will share the same message that I wrote in discussions:

Hi, It's my first time using PrimeReact with NextJS and Tailwind and I have problem in my styles and I don't understand why.
Here you can see a **Stackblitz** with the problem: https://stackblitz.com/edit/stackblitz-starters-7lccbl?file=app%2Fpage.tsx

## Problem 1 (Opening **Stackblitz**)

If I open in Chrome (left side) works perfectly. But If I open in Firefox (right side) it's broken. (**Button** "Volver atrás", **calendar input**, **dividers**, and **button at the bottom)**

![image](https://github.com/primefaces/community/assets/19764334/e8694d91-dc4e-43bb-b68e-00c4b2ac46d4)

## Problem 2 (Opening **Netlify**)

I uploaded almost the same code to Netlify to check it and in Chrome and Firefox it's broken.
This is the link: https://lighthearted-genie-243620.netlify.app/pages/salvaments.

## Problem 3 (Opening **VERCEL**)
Here you can see the problem too: https://estadisticas-guardavidas.vercel.app/pages/salvaments

![image](https://github.com/primefaces/community/assets/19764334/43dde848-8c13-4258-b652-76a9be2fa5a2)


Hope someone knows If i'm doing something wrong or it's a bug.

Thanks!

**Comment by SoyDiego** [comment] 2023-10-25 12:18
I found this possible solution
https://soydiego.notion.site/PrimeReact-How-to-fix-styles-NextJS-Tailwind-92bec3eb91594388a7be67d922460eaf

**Comment by melloware** [comment] 2023-10-26 15:23
PrimeReact 10.0.7 is out with updated TailWind instructions for styled and unstyled mode: https://primereact.org/tailwind/

**Comment by C0ZEN** [comment] 2023-10-27 10:15
It's not fixing the issue, sadly.
For example, the button's CSS is still overridden by Tailwind as a higher priority than PrimeReact, creating countless CSS issues.

**Comment by melloware** [comment] 2023-10-27 10:54
Ok let me ping PrimeTek again.

**Comment by mertsincan** [comment] 2023-10-27 11:20
I'll check and get back to you asap. Thanks a lot for your reports!

**Comment by gucal** [comment] 2023-11-01 11:13
Hi,

This is a layer problem. Need to implement the layer structure correctly. 
Reproducer tools like stackblitz, codesandbox etc. make layers complex. This makes the correct code look wrong. 

When used correctly, you will find the stackblitz examples work successfully in your local applications.
You should follow this document for proper use. https://primereact.org/tailwind

This repo works as it should. https://github.com/primefaces/primereact-examples/tree/main/nextjs-styled-tailwind

Thanks for your feedbacks.

**Comment by rohitdhas** [comment] 2023-11-06 08:34
So, I just tried importing `prime-react` resource files at the end and it worked! 🎉

<img width="688" alt="Screenshot 2023-11-06 at 2 03 31 PM" src="https://github.com/primefaces/primereact/assets/53969450/fcb4427d-d164-4b03-be03-784fad251965">

**Comment by gucal** [comment] 2023-11-10 12:58
> Hi,
> 
> This is a layer problem. Need to implement the layer structure correctly. Reproducer tools like stackblitz, codesandbox etc. make layers complex. This makes the correct code look wrong.
> 
> When used correctly, you will find the stackblitz examples work successfully in your local applications. You should follow this document for proper use. https://primereact.org/tailwind
> 
> This repo works as it should. https://github.com/primefaces/primereact-examples/tree/main/nextjs-styled-tailwind
> 
> Thanks for your feedbacks.

I don't think you will have any problems with the layer using this method.

If your problem continues to persist, please don't hesitate to inform us.

I am closing this issue now. If you see an error, you can open it again.

Thank you.

**Closed by gucal** 2023-11-10 12:58 UTC
Labels: Status: Pending Review, Component: Tailwind

**Comment by C0ZEN** [comment] 2023-11-10 14:42
Hi, I gave it a try and had the same issue again.
I found out why, though; it's because I import the CSS files within my .scss file.
Somehow, it's not the same output.

In your examples, the CSS files are imported within a .css file.

**Comment by melloware** [comment] 2023-11-13 22:09
@C0ZEN you have it all working with Vite and Primereact + Styled Tailwind?  Other users are asking and I think I should add an example using Vite here: https://github.com/primefaces/primereact-examples

**Comment by melloware** [comment] 2023-11-13 22:41
Nevermind I figured it out and added a Vite + PrimeReact + Styled + TailwindCSS example: https://github.com/primefaces/primereact-examples/tree/main/vite-styled-tailwind

**Comment by jerlam06** [comment] 2023-11-16 15:04
v10 not working on my side. I am using tailwind cli to build tailwind on file change to only extract necessary classnames used in my app. I have tried a few things mentioned above as well as Vite + PrimeReact + Styled + TailwindCSS example. Nothing works for me. Tbh I have never used css layers, and I have no time to dig into it right now. I will stick to v9 until v10 is more stable css-wise, it is a pity because v10 is fixing a few bugs I have.

**Comment by melloware** [comment] 2023-11-16 15:45
@jerlam06 my Vite example above works fine?  Can you compare mine to yours and what is broken?

**Comment by nikolapalibrk** [comment] 2023-11-19 19:09
For me it works well when theme is imported in App.js since there I can control the order of imports, and I place the theme at the bottom. But the problem is when I want to implement theme switching ( https://primereact.org/theming/#switchthemes ) where css is loaded by placing link tag in index.html. In that case style from tailwind is loaded later and therefore overrides style from primereact theme.

**Comment by ArsenicBismuth** [comment] 2023-12-23 23:28
> So, I tried importing `prime-react` resource files at the end and it worked! 🎉
> 
> 

Thanks a lot for this! Basic theme classes like `p-button` was overridden by Tailwind, but reordering the CSS (theme.css last) fixed it.

**Comment by webxzy** [comment] 2023-12-30 14:27
> 没关系，我想通了并添加了一个 Vite + PrimeReact + Styled + TailwindCSS 示例：https://github.com/primefaces/primereact-examples/tree/main/vite-styled-tailwind

good，I'm Ok

**Comment by chhmanel** [comment] 2024-03-22 04:37
> So, I tried importing `prime-react` resource files at the end and it worked! 🎉
> 
> <img alt="Screenshot 2023-11-06 at 2 03 31 PM" width="688" src="https://private-user-images.githubusercontent.com/53969450/280640750-fcb4427d-d164-4b03-be03-784fad251965.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwODI0NDksIm5iZiI6MTcxMTA4MjE0OSwicGF0aCI6Ii81Mzk2OTQ1MC8yODA2NDA3NTAtZmNiNDQyN2QtZDE2NC00YjAzLWJlMDMtNzg0ZmFkMjUxOTY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA0MzU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3OTA3ZWVhYTg2NjA4OGM5YmE4N2UwNzE0MTU5Zjc1NjA1ODlkNDRmZjY0N2ZjMGZkZTcwODgxMmM0MTZhZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MnW6oylsDEfvhW4fYnH-_YnHz386G8eoUK-uGDuPWO8">

This is working for me, thank you so much!

**Comment by Vini-Dev-Py** [comment] 2024-11-21 13:09
Hi guys I'm having trouble getting tailwind css to work with my react prime custom styles, could someone help me? Do you have an example of how to do it?

my more detailed problem is as follows
I have 2 themes a light and a dark where they are alternated by the “changeTheme” function of PrimeReactContext, but a few days ago tailwind was added to the project and at the moment we would like to continue with the styles via scss from primereact, but tailwind overwrote some styles, both of the light and dark theme

I even tried the examples mentioned here, but none of them show the change of themes, I can't do this part...

If I add the import of the light or dark theme in the main.css along with the layers it works, but only with the imported theme, I need a way to switch to both themes.

Translated with DeepL.com (free version)

@melloware

**Comment by karthikMNK** [comment] 2025-02-16 09:18
is prime react going to use all tailwind css instead of p- classes.It will be good.

**Comment by oleksii-kotvytskyi** [comment] 2025-02-27 14:53
For those who looking for solutions for change theme (PrimeReactContext), primereact + tailwind. 

**input.css**
@layer base, theme, components, utilities, primereact;

@import "tailwindcss/theme.css" layer(theme);
@import "tailwindcss/preflight.css" layer(primereact);
@import "tailwindcss/utilities.css" layer(utilities);

@theme {
  --color-primary-color: var(--primary-color);
  --color-primary-color-text: var(--primary-color-text);
...
}

@custom-variant dark (&:where(.dark, .dark *));

**function to change theme**
...
  const _changeTheme = (theme: string, colorScheme: string) => {
    document.documentElement.classList.remove(
      colorScheme === "dark" ? "light" : "dark"
    );
    document.documentElement.classList.add(colorScheme);
    // layoutConfig.theme - is current theme

    changeTheme?.(layoutConfig.theme, theme, "theme-css", () => {
      setLayoutConfig((prevState: any) => ({
        ...prevState,
        theme,
        colorScheme,
      }));
    });
  };

usage 
<button onClick={() => _changeTheme("lara-light-purple", "light")}>lara-light-purple</button>
...

**tailiwind.confg.js**
...
module.exports = {
  darkMode: "class",
...
};
...

**index.html**
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <link
      id="theme-css"
      href="/themes/lara-light-blue/theme.css"
      rel="stylesheet"
    />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>FPV Nest</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>

**Comment by melloware** [comment] 2025-03-06 12:57
I have upgraded all example to Tailwind4 : https://github.com/primefaces/primereact-examples
