### ISSUE TITLE
Table: conditional render multiple Columns

### ISSUE THREAD

**Issue by maitrungduc1410** [primefaces/primereact#4495] opened 2023-06-10 03:13 UTC
### Describe the bug

When I try to render multiple columns under 1 condition, it doesn't work
```tsx
{someCondition && (
  <>
    <Column
      rowEditor
      headerStyle={{ width: "10%", minWidth: "8rem" }}
      bodyStyle={{ textAlign: "center" }}
    ></Column>
    <Column
      rowEditor
      headerStyle={{ width: "10%", minWidth: "8rem" }}
      bodyStyle={{ textAlign: "center" }}
    ></Column>
  </>
)}
```
To overcome this I have to put each column in separate condition block, it's duplicated

### PrimeReact version

9.3.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Browser(s)

Chrome

### Expected behavior

it should be able to render multiple columns under single condition

**Comment by melloware** [comment] 2023-06-10 11:34
I don't think this is an issue that will be fixed.  So what is happening is the Datatable to get its columns gets all the React Children under the dattable.

```js
const columns = React.Children.toArray(props.children);
```

In a normal DT it looks like this...

```xml
<DataTable value={products} tableStyle={{ minWidth: '50rem' }}>
    <Column field="code" header="Code"></Column>
    <Column field="name" header="Name"></Column>
    <Column field="category" header="Category"></Column>
    <Column field="quantity" header="Quantity"></Column>
</DataTable>
```

So the Children are the 4 `<Column>` components.

In your case your table look like this...

```xml
<DataTable value={products} tableStyle={{ minWidth: '50rem' }}>
    <Column field="code" header="Code"></Column>
    <Column field="name" header="Name"></Column>
    <>
       <Column field="category" header="Category"></Column>
       <Column field="quantity" header="Quantity"></Column>
    </>
</DataTable>
```

So the children in your case are 2 columns and then the `React.Fragment` which is NOT a column.  

Here is a reproducer showing you the issue: https://stackblitz.com/edit/react-8hlwmr?file=src%2FApp.js

**Closed** 2023-06-10 12:21 UTC
Labels: Resolution: By Design

**Comment by 20nick06** [comment] 2024-06-30 17:29
So what's the workaround for this?

**Comment by melloware** [comment] 2024-06-30 20:25
@20nick06 the solution is to use dynamic columns: https://primereact.org/datatable/#dynamic_columns
