### ISSUE TITLE
MultiSelect: selectionLimit does not limit selections

### ISSUE THREAD

**Issue by XYIAN** [primefaces/primereact#6391] opened 2024-04-12 22:56 UTC
### Describe the bug

When using MultiSelect with a selectionLimit (for example a selection limit of 2) the component still allows me to select an unlimited amount of options. 

### Reproducer

https://stackblitz.com/edit/vitejs-vite-qu7tmj?file=src%2FApp.tsx

### PrimeReact version

10.5.1

### React version

18.x

### Language

TypeScript

### Browser(s)

ALL

### Steps to reproduce the behavior

1. use multi select
2.  give 3+ options 
3.  add selectionLimit of 2 and select more than two options 

### Expected behavior

This should only allow you to select whatever the limit is set to, but it does not

**Comment by melloware** [comment] 2024-04-13 02:04
Duplicate of #6121 ?

**Closed** 2024-04-13 12:18 UTC
Labels: Resolution: Duplicate
