### ISSUE TITLE
DataTable Custom Filter and Inequalities

### ISSUE THREAD

**Issue by mengjade** [primefaces/primereact#640] opened 2018-11-13 21:28 UTC
Hi, could you provide an example for "custom" filter?
https://www.primefaces.org/primereact/#/datatable/filter

Are inequalities like lt, lte, gt, gte supported in primereact?

**Comment by slothdude** [comment] 2019-05-01 14:46
An example for global Filter Function would be great too https://github.com/jepsar/primefaces/commit/23b87a2e9aea4587d10d92b127a104e0dc9791fd

**Comment by mertsincan** [comment] 2021-02-09 20:58
Hi,

We'll add new features related to DataTable filter as in PrimeNg;
https://primefaces.org/primeng/showcase/#/table/filter

We plan to do this in 6.1.0 or the next version.
Best Regards,

**Comment by lohani-harsha** [comment] 2022-03-28 09:36
Is there any bug for custom filters for DataTable? Please confirm.
If not please provide a working example or working sandbox code link.

**Comment by melloware** [comment] 2022-03-28 11:59
This ticket can now be closed as the new 7.X datatable has all the features mentioned above including Global Filtering.

```js
export const FilterMatchMode = Object.freeze({
    STARTS_WITH: 'startsWith',
    CONTAINS: 'contains',
    NOT_CONTAINS: 'notContains',
    ENDS_WITH: 'endsWith',
    EQUALS: 'equals',
    NOT_EQUALS: 'notEquals',
    IN: 'in',
    LESS_THAN: 'lt',
    LESS_THAN_OR_EQUAL_TO: 'lte',
    GREATER_THAN: 'gt',
    GREATER_THAN_OR_EQUAL_TO: 'gte',
    BETWEEN: 'between',
    DATE_IS: 'dateIs',
    DATE_IS_NOT: 'dateIsNot',
    DATE_BEFORE: 'dateBefore',
    DATE_AFTER: 'dateAfter',
    CUSTOM: 'custom'
});
```

**Comment by lohani-harsha** [comment] 2022-03-28 12:43
I tried creating a custom filter for balance column for customer Table. Plz find sandbox code link below.

https://codesandbox.io/s/musing-fog-tlp73v?file=/src/demo/DataTableDemo.js:13317-13325

I am getting filterConstraint is not a function could you plz suggest why I am getting this error.

**Comment by melloware** [comment] 2022-03-28 12:48
From lookin at the source code...

```js
executeLocalFilter(field, rowData, filterMeta, index) {
        let filterValue = filterMeta.value;
        let filterMatchMode = filterMeta.matchMode === 'custom' ? `custom_${field}` : filterMeta.matchMode || FilterMatchMode.STARTS_WITH;
        let dataFieldValue = ObjectUtils.resolveFieldData(rowData, field);
        let filterConstraint = FilterService.filters[filterMatchMode];

        return filterConstraint(dataFieldValue, filterValue, this.props.filterLocale, index);
    }
```

It looks like when type is custom its expecting you to have a registered function ``custom_${field}` ` but it looks like that is not implemented in `FilterService` so it looks like that is why this ticket is still open and marked for 8.0

**Comment by melloware** [comment] 2022-09-15 16:21
Duplicate of https://github.com/primefaces/primereact/issues/3325 closing for that issue

**Closed by melloware** 2022-09-15 16:21 UTC
Labels: Component: Documentation
