### ISSUE TITLE
DataTable: Bug with virtual scroll

### ISSUE THREAD

**Issue by wolnynick** [primefaces/primereact#2955] opened 2022-06-02 14:02 UTC
### Describe the bug

Data in my table can reach over 1000 rows so I decided to use virtual scroll property to show some mercy to the browser, but I discovered that using it with filters and sorts (must be both) is breaking columns in table when there is no place to contain all columns visible (I'm using horizontal scroll).

And useEffect to calculate height of scrollHeight is necessary.

### Reproducer

https://codesandbox.io/s/mystifying-taussig-n817yh?file=/src/App.js

### PrimeReact version

8.1.1

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Browser(s)

Edge Version 101.0.1210.53 (Official build) (64-bit)

### Steps to reproduce the behavior

1. Go to: https://codesandbox.io/s/mystifying-taussig-n817yh?file=/src/App.js
2. Set application page width below 580px: (You can check Root width information in application above the table):

![image](https://user-images.githubusercontent.com/40297940/171645703-02a69ae4-110d-45e8-baa9-075d090af828.png)

![image](https://user-images.githubusercontent.com/40297940/171646095-6bc2d94b-f86e-4271-bcf5-518e5ff479b7.png)

### Expected behavior

Column headers should be aligned with columns below.

**Comment by Dav3rs** [comment] 2022-07-20 22:26
This bug occurs just by adding the scrollable property. It can be even the most simple table, not necessarily related to filters and sorts or virtual lists.

The example can get worse if cell values are very different each others:
![image](https://user-images.githubusercontent.com/50024128/180091402-33732d3b-871c-4123-bd11-2b1bd4f1286c.png)

Just by removing the "scrollable" property:
![image](https://user-images.githubusercontent.com/50024128/180091922-afb913a8-f3ce-4416-9b08-51d3c9a78d5c.png)

This at the moment make scrollable datatable unusable on mobile devices, or even on desktop for horizontally long tables.

**Comment by melloware** [comment] 2022-07-21 12:02
I updated the code sandbox example to PR 8.3.0 and it seems to be working.

https://codesandbox.io/s/priceless-firefly-67lx8v

Can you check it out?

**Comment by melloware** [comment] 2022-07-21 12:04
@Dav3rs  I am going to close this ticket as completed in 8.3.0 since the original reproducer is now fixed.  If you have other issues please open a new ticket with a reproducer.

**Closed by melloware** 2022-07-21 12:04 UTC
Labels: defect

**Comment by Dav3rs** [comment] 2022-07-21 12:33
@melloware Please look at this simplified example
https://codesandbox.io/embed/great-monad-pzyj6p?fontsize=14&hidenavigation=1&theme=dark

![image](https://user-images.githubusercontent.com/50024128/180214240-827dfddf-b1cf-417b-b409-450acbd66e69.png)

**Comment by melloware** [comment] 2022-07-21 12:54
OK @Dav3rs open a new ticket as this is different than the above reported issue which was the columns go out of whack as you got below 568px browser size.
