### ISSUE TITLE
Splitter: TypeError "index" is read-only

### ISSUE THREAD

**Issue by peace317** [primefaces/primereact#3539] opened 2022-10-31 23:37 UTC
### Describe the bug

It seems like the Splitter does not work in any constellations. The Splitter is moveable until releasing, with that the app crashes.  The Codebox-example is from the primereact [documentation](https://www.primefaces.org/primereact/splitter/) itself and only 8.7.0 has the error.

> Uncaught TypeError: "index" is read-only
    at _readOnlyError (splitter.esm.js:73)
    at splitter.esm.js:268
    at basicStateReducer (react-dom.development.js:15195)
    at updateReducer (react-dom.development.js:15318)
    at updateState (react-dom.development.js:15641)
    at Object.useState (react-dom.development.js:16442)
    at Object.useState (react.development.js:1508)
    at splitter.esm.js:137
    at renderWithHooks (react-dom.development.js:14985)
    at updateForwardRef (react-dom.development.js:17044)

### Reproducer

https://codesandbox.io/s/hbjqci

### PrimeReact version

8.7.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Next.js

### Steps to reproduce the behavior

1. Wait for rendered App 2. Move the splitter; the error occurs when releasing

### Expected behavior

No error and expected behavior of the splitter component

**Comment by melloware** [comment] 2022-10-31 23:44
Duplicate of #3527

**Closed** 2022-10-31 23:45 UTC
Labels: Resolution: Duplicate
