### ISSUE TITLE
Tooltip event="both" does not work if element get focus state by clicking on it 

### ISSUE THREAD

**Issue by Luko248** [primefaces/primereact#7260] opened 2024-09-27 09:10 UTC
### Describe the bug

If I se "tab" case, it perfectly fowks for hover or focus, but if I try click on element, tooltip will dissapier, when i leave trigger element with cursor viz picture.

### System Information

```Shell
System: Windows 10, Browsers: all npmPackages: primereact

primereact: 10.8.3
react: 18.2.0
```

### Steps to reproduce the behavior

![tooltip](https://github.com/user-attachments/assets/d7d3662a-4d64-4407-ab27-1b07fefa4ced)

### Expected behavior

When user set event="both", it must show tooltip on hover and when user  focus input, it must be still visible, if user leave input / whatever with curssor.

**Comment by sja-cslab** [comment] 2024-09-27 09:13
@melloware my guess is, that hover-out will trigger the hide event

**Comment by Luko248** [comment] 2024-09-27 11:15
@melloware Yes, I think so. Is it possible to fix it in next release?

**Comment by sja-cslab** [comment] 2024-09-27 11:29
@Luko248 you're more than welcome to open a PR

**Comment by melloware** [comment] 2024-09-27 12:29
@Luko248 is this a duplicate of #5727 ?

**Comment by sja-cslab** [comment] 2024-09-27 12:31
@melloware no its similar but not a dupe. However fixing the one COULD fix the other one too.

The difference is, that on #5727 we're talking about tooltips on two inputs with hover/focus, this issue here is about a single input that has both events set

**Comment by melloware** [comment] 2024-09-27 12:40
Understood i will mark this as a bug.

**Closed** 2024-10-01 20:17 UTC
Labels: Type: Bug
