### ISSUE TITLE
Calendar: Error thrown when set value for Date Range programmatically

### ISSUE THREAD

**Issue by maitrungduc1410** [primefaces/primereact#3587] opened 2022-11-06 17:28 UTC
### Describe the bug

when setting value for Date range programmatically, app crashed.

Code:
```tsx
import { Calendar } from "primereact/calendar";

export default function MyApp {
  const [datesFilter, setDatesFilter] = useState<Date[]>();

  const setDateManually= () => {
    const fromDate = new Date()
    const toDate = new Date()
    setDatesFilter([fromDate, toDate]) // ------>>>>>>> App crashed from here
  }
  return (
    <>
    <Calendar
      value={datesFilter}
      onChange={(e) => setDatesFilter(e.value)}
      selectionMode="range"
      readOnlyInput
      showIcon
      placeholder="Select dates..."
    />
    <button onClick={() => setDateManually()}>Set Date</button>
    </>
  )
}

```

### PrimeReact version

^8.7.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Browser(s)

Chrome 107

### Steps to reproduce the behavior

1. Select a range from Calendar -> works fine
2. Click button to set date range manually -> app crashed

Root cause: debugging Calendar source code (screenshot below), I found the reason, it turns out, if the calendar is not opening, then the below code assumes value for the calendar is a single Date value (type: `Date`), meanwhile, in the case of date range, it should be array (type `Date[]`)
.

<img width="741" alt="Screenshot 2022-11-07 at 12 26 52 AM" src="https://user-images.githubusercontent.com/16630193/200185569-bbcc00f6-f73a-43c4-9616-6a2eb98b8a16.png">

**Comment by melloware** [comment] 2022-11-06 18:09
Duplicate of #3545

**Closed** 2022-11-06 18:09 UTC
Labels: Resolution: Duplicate
