### ISSUE TITLE
findDOMNode is deprecated in StrictMode error on components

### ISSUE THREAD

**Issue by abhaykeerthy12** [primefaces/primereact#1663] opened 2020-11-06 18:58 UTC
**Current behavior**
Using any component that uses react transition group gives findDOMNode is deprecated in StrictMode error.

**Expected behavior**
Should not give error when using components with react transition group dependency

**Minimal reproduction of the problem with instructions**
Just use any component with react transition group, like toast, overlay etc

* **React version:**
17.0.1

* **PrimeReact version:**
5.0.1
 
* **Language:** TypeScript 4.0.5

**Comment by edw19** [comment] 2020-11-09 22:04
I have the same issue 
if remove us the strictMode ?

**Comment by heybechill** [comment] 2021-01-22 02:34
Create React App has had a React.StrictMode wrapper on the default template since [v3.4.1](https://github.com/facebook/create-react-app/releases/tag/v3.4.1) so any new CRA projects are going to be seeing these warnings. The only solution currently seems to be disabling strict mode by deleting the wrappers in `index.js`.

**Comment by bitlab-code** [comment] 2021-01-23 15:48
same here, with `prisareact` v6

**Comment by dattebayorob** [comment] 2021-01-26 14:11
Hello guys, I Think just removing React.ScritcMode wrapper isnt a valid solution. Is there any plan to update the ref's usage on CssTransition?
https://github.com/reactjs/react-transition-group/releases/tag/v4.4.0

**Comment by abhaykeerthy12** [comment] 2021-01-30 02:23
Removal of React.StrictMode mode in code should not be a solution as it will compromise code quality, its better to re-implement the ref usage

**Comment by mertsincan** [comment] 2021-01-30 02:44
Hi,

Duplicate of https://github.com/primefaces/primereact/issues/1790

**Closed by mertsincan** 2021-01-30 02:44 UTC

**Comment by mertsincan** [comment] 2021-01-30 05:04
Fixed in #1790
