### ISSUE TITLE
DataTable: Reordering Columns Causes Duplication in Checkbox Column and Reorder Row Indicator Column

### ISSUE THREAD

**Issue by rizalgunawan** [primefaces/primereact#6590] opened 2024-05-08 09:50 UTC
### Describe the bug

When reordering columns, there's an issue where it results in duplication within the checkbox column and the reorder row indicator column. This behavior needs to be addressed and resolved to ensure proper functionality and consistency in column reordering.

The issue occurs when there are two additional columns in the DataTable:

1. Reorder Row Column: This column allows users to reorder rows within the DataTable.
2. Multi-Selection Column (Checkbox): This column provides checkboxes for multi-selection functionality.

**Original state**
<img width="814" alt="image" src="https://github.com/primefaces/primereact/assets/47345705/466e1fe4-c8b8-4b20-bfef-a3bc8ff33433">

**After Reorder**
<img width="824" alt="image" src="https://github.com/primefaces/primereact/assets/47345705/e3ffde45-f139-464d-bfd5-531603522932">

Code Example
```

<div className="card">
      <DataTable
        value={products}
        reorderableColumns
        reorderableRows
        onRowReorder={(e) => setProducts(e.value)}
        tableStyle={{ minWidth: '50rem' }}
      >
        <Column reorderable={false} rowReorder style={{ width: '3rem' }} />
        <Column
          selectionMode="multiple"
          headerStyle={{ width: '3rem' }}
        ></Column>
        {dynamicColumns}
      </DataTable>
    </div>

```

### Reproducer

https://stackblitz.com/edit/aufpff

### PrimeReact version

latest

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Implement the DataTable component with column configurations that allow reordering.
2. Add two additional columns for row reordering and multi-selection (checkbox).
3. Drag and drop columns other than the two mentioned above to any position.

You can follow these steps to observe the duplication issue in the Reorder Row Column and the Multi-Selection Column when columns are reordered.

**Comment by sja-cslab** [comment] 2024-05-08 09:58
In case you did not notice, even the [Docs](https://primereact.org/datatable/#reorder) currently not really working with reordering. If you start dragging, with mouse on the icon, you won't be able to drag/drop. If you can get 1px beside the icon, it works. So something seems to be weird here.

Thats just extra information for any contributor.

**Comment by Rekl0w** [comment] 2024-05-08 10:17
Duplicate of #6558.

**Closed** 2024-05-08 11:22 UTC
Labels: Status: Needs Triage
