### ISSUE TITLE
InputNumber: Change value only using keyboard is difficult

### ISSUE THREAD

**Issue by nico-richter** [primefaces/primereact#3673] opened 2022-11-18 14:23 UTC
### Describe the bug

When entering InputNumber with currency flag with a given value via keyboard and navigating through characters using arrowKeys is not possible.

### PrimeReact version

8.7.2

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 107

### Steps to reproduce the behavior

1. Click/Focus element before InputNumber
2. Press Tab on keyboard
=> full value is selected
3. press LeftArrow/RightArrow to move cursor
=> nothing happens on leading currency like $ or cursor get stucked after currency character

### Expected behavior

Cursor is moved to first position (LeftArrow) or last position (Right Arrow) of the number

**Comment by melloware** [comment] 2022-11-18 14:26
Duplicate of https://github.com/primefaces/primereact/issues/1866 which is already fixed for 8.7.3

**Closed by melloware** 2022-11-18 14:26 UTC
Labels: Resolution: Duplicate
