### ISSUE TITLE
DataTable: VirtualScroller with rowGroupMode

### ISSUE THREAD

**Issue by xAl3xFx** [primefaces/primereact#5036] opened 2023-10-05 10:12 UTC
### Describe the bug

When using the DataTable with `virtualScroll` and `rowGroupMode="subheader"`, the datatable gets really messed up.

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-s37t56?file=/src/App.js:2432-2444

### PrimeReact version

10.0.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Go to https://primereact.org/datatable/#row_group
2. Click "Edit in CodeSandbox" option.
3. Add `virtualScrollerOptions={{ itemSize: 46 }}` prop to the DataTable component.
4. Scroll the table.

**Comment by username9585854** [comment] 2023-12-18 15:57
I believe this is a duplicate of #4577.
The issue with the flashing scrolling, and inability to scroll to the bottom happens with/without the grouping.
https://github.com/primefaces/primereact/issues/4577

**Comment by melloware** [comment] 2023-12-18 16:02
Thanks marked as duplicate

**Closed** 2023-12-18 16:02 UTC
Labels: Resolution: Duplicate

**Comment by yilinevelyn** [comment] 2023-12-27 07:15
Sorry, I also have this problem. Is it resolve?

**Comment by melloware** [comment] 2023-12-27 13:02
@yilinevelyn please subscribe to #4577 it is still open
