### ISSUE TITLE
DataTable: Doubleclick edit

### ISSUE THREAD

**Issue by rpspall** [primefaces/primereact#4335] opened 2023-05-02 21:42 UTC
### Describe the feature you would like to see added

Would like option to trigger Cell editing with a double click instead of a single click

**Comment by melloware** [comment] 2023-05-03 13:35
Do you mean DataTable not Grid?

**Comment by rpspall** [comment] 2023-05-03 15:10
Yes... thanks for changing the title

https://primereact.org/datatable/#cell_edit

Single click works well, but would like to see a double-click to edit option

Not sure if it is a separate feature request, but would be also be nice to selectively prevent edit on a cell. Tried event.preventDefault() in onCellEditInit and onBeforeCellEditShow Column event callbacks but didn't work - may be similar bug to event.preventDefault() not working in onCellEditComplete?

**Comment by melloware** [comment] 2023-05-03 15:18
@rpspall can you open a new ticket for that I can fix that too.

**Comment by melloware** [comment] 2023-05-10 21:21
Duplicate of https://github.com/primefaces/primereact/issues/4187

**Closed by melloware** 2023-05-10 21:21 UTC
Labels: Type: New Feature, Status: Discussion, Status: Needs Triage
