### ISSUE TITLE
DataTable: ContextMenu with multiple selectionMode

### ISSUE THREAD

**Issue by mtsh1000** [primefaces/primereact#5432] opened 2023-11-28 13:11 UTC
### Describe the bug

When using context menu with multi select the onContextMenu should always provide only the single target row that was clicked. Currently if there is selection present the e.data contains array with selected rows but not the actual row that was clicked if it was not within the selection.

### PrimeReact version

10..2.1

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment] 2023-11-28 13:33
Duplicate of https://github.com/primefaces/primereact/issues/5146

**Closed by melloware** 2023-11-28 13:33 UTC
Labels: Resolution: Duplicate
