### ISSUE TITLE
 Virtual Scrolling with row expandable flickering issue

### ISSUE THREAD

**Issue by tewabet** [primefaces/primereact#4711] opened 2023-08-01 01:14 UTC
### Describe the bug

when expanding the last row, the data is hidden below the visible area. To view the expandable area, one needs to scroll down to bring in to view. The user must use the scroll wheel or vertical scrollbar to view the text. When manually scrolling to see the text, then the entire grid starts flickering.

### PrimeReact version

9.6.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment] 2023-08-01 01:35
Duplicate of #2854

**Closed** 2023-08-01 11:32 UTC
Labels: Resolution: Duplicate
