### ISSUE TITLE
Dialog: grabbing and moving stops at non-existent boundaries

### ISSUE THREAD

**Issue by inad9300** [primefaces/primereact#5907] opened 2024-02-06 08:33 UTC
### Describe the bug

Try grabbing a dialog and moving it to the edge of the window. The fastest you attempt to do this, the furthest from your goal you will get. It is only when you move very slowly that you can get the dialog in the position you want.

### Reproducer

https://primereact.org/dialog

### PrimeReact version

10.4.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment] 2024-02-08 13:24
Duplicate of: https://github.com/primefaces/primereact/issues/2042

**Closed by melloware** 2024-02-08 13:24 UTC
Labels: Status: Needs Triage
