### ISSUE TITLE
CSS Breaks only in Production (Next.js App Router + Tailwind)

### ISSUE THREAD

**Issue by ahmedwadod** [primefaces/primereact#5684] opened 2024-01-04 18:03 UTC
### Describe the bug

I've imported Primereact into my Next.js 14 app router application according to this example [nextjs-styled-tailwind](https://github.com/primefaces/primereact-examples/tree/main/nextjs-styled-tailwind) and it's working great with the development server `npm run dev` but when running in production with `npm run build` then `npm run start` the CSS stops working despite everthing else (JS, Icons) working properly.

### Reproducer

https://github.com/ahmedwadod/next14-tw-pr-demo

### PrimeReact version

10.2.1

### React version

18.x

### Language

ES5

### Build / Runtime

Next.js

### Browser(s)

Chrome 119.0.6045.123

### Steps to reproduce the behavior

1. run `npm run build`
2. run `npm run start`

### Expected behavior

On Dev (Expected):
![ntwpr-dev](https://github.com/primefaces/primereact/assets/32812444/87493dd9-5950-49d5-bb56-7c42ea9a43ee)

On Prod (Not working):
![ntwpr-prod](https://github.com/primefaces/primereact/assets/32812444/90dd9fbe-1c20-4baa-bfa6-fcefece290e2)

**Comment by melloware** [comment] 2024-01-04 18:11
Duplicate of https://github.com/primefaces/primereact/issues/5187

**Closed by melloware** 2024-01-04 18:11 UTC
Labels: Status: Needs Triage
