### ISSUE TITLE
Datatable filter re-render causing performance issue

### ISSUE THREAD

**Issue by fullstackomar** [primefaces/primereact#6392] opened 2024-04-13 14:01 UTC
### Describe the bug

in datatable filter there is a performance issue where the datatable keeps re-render other filters to be able to add a the text causing other filters to re-render in that example it shows that dropdown keeps re-rendering when you add any text into name field causing a performance issue

### Reproducer

https://stackblitz.com/edit/vitejs-vite-p9q1kh?file=src%2FApp.tsx,dropdown.tsx

### PrimeReact version

10.6.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Browser(s)

chrome,firefox

### Steps to reproduce the behavior

this is just a small example but what it happens if i used any filter it keeps re-renders the other filters each time i type anything for example into this example I have only 2 columns it re-render 2 times but in real project I have 30 columns this causes to re-render 30 times causing performance issues , inside the console when you check I added a console called re-rendered when I use any filter in datatable it keeps re-render other filters which cause the page to be so slow.

### Expected behavior

expected to use a filter without re-render other filters to be able to improve my page performance and fix the filter delays that happens when the user type anything inside inputtext.

**Comment by melloware** [comment] 2024-04-13 14:24
Duplicate of https://github.com/primefaces/primereact/issues/5017 ??

**Comment by fullstackomar** [comment] 2024-04-13 14:34
yes its similar to this case, when can we expect to see this fix since its open since Oct 2023 , or how can I access the node code so I can try to fix this issue and post the solution

**Comment by melloware** [comment] 2024-04-13 15:06
@fullstackomar if you need immediate support I suggest PrimeReact PRO: https://primereact.org/support/

Else there is no timeline unless a community member provides a fix.

**Closed by melloware** 2024-04-13 15:06 UTC
Labels: Resolution: Duplicate

**Comment by fullstackomar** [comment] 2024-04-16 12:29
@melloware I can try to debug and fix but can you please tell me which files should I check in your opinion I can try to fix in weekend to find a solution, also what is the difference between primereact and the pro version and can I use it into all of my projects or just 1 project ?

**Comment by melloware** [comment] 2024-04-16 12:34
there is no PRO version.  PRO just gives you professional support so if you want someting like this addressed or fixed it gives you a direct line to PrimeTek to financially sponsor fixing it.

AS for fixing this bug the Datatable is quite complex but I would start with the ColumnFilter code and see why as you type its changing the whole table.
