### ISSUE TITLE
Calendar: Double Click When There is input mask

### ISSUE THREAD

**Issue by myisamkernel** [primefaces/primereact#6042] opened 2024-02-26 04:51 UTC
### Describe the bug

In previous version around 9.6.4 it doesn't need to double click to change value when mask is present

### Reproducer

https://stackblitz.com/edit/5jjucc-ht9gfe?file=src%2FApp.jsx

### PrimeReact version

10.5.1

### React version

18.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1.If Init Value in Calendar is empty select it
2.If Value inside Calendar is not null try change the value

### Expected behavior

it doesn't need to double click to change value when mask is present

**Comment by frle10** [comment] 2024-04-16 10:07
In version 10.3.2 this still works normally and the bug appears in all versions after 10.3.2.

**Comment by maxkuzmin** [comment] 2024-05-23 04:02
@myisamkernel I think we still need the fix, could you re-open it?

**Comment by melloware** [comment] 2024-05-23 11:43
I reopened.

**Comment by F4ssi** [comment] 2024-08-01 11:38
Is this the same or related to the issue in #4568?

**Comment by frle10** [comment] 2024-08-01 11:42
> Is this the same or related to the issue in #4568?

After looking through it, I'd say it's definitely related.

**Comment by melloware** [comment] 2024-08-01 11:53
Duplicate of #4568

**Comment by melloware** [comment] 2024-08-01 11:54
Thanks I closed as duplicate

**Closed by melloware** 2024-08-01 11:54 UTC
Labels: Type: Bug
