### ISSUE TITLE
Column Component: set Column order programately

### ISSUE THREAD

**Issue by meriemMat** [primefaces/primereact#5191] opened 2023-10-30 11:19 UTC
### Describe the bug

Hesslo Evryone;
this problem is similar to [#5107](url) i have external paginator where i show and hide columns,
i am strugling with a scenario where i hide a column then make reoder manipulation manually ,then when i show the column again its shown at the end not at its original place .
 to note that i give a coherent selectedColumns varibale (with right order ) but the databale doesnt respcet what am sending to draw columns:
`  return selectedColumns?.map((col) => {
        if (col) {
            let width =
                col.width !== undefined
                    ? col.width + 'px'
                    : col?.Editor?.SizeMode === 'Squeeze'
                    ? '30px'
                    : '100px';
            let colStyle = {
                width: width,
                fontSize: '12px',
                maxWidth: width,
                minWidth: '20px',
                backgroundColor: col?.CellBackColor
                    ? col?.CellBackColor
                    : '',
            };
          
            return (
                <Column
                  
                    headerStyle={colStyle}
                    bodyStyle={colStyle}
                    resizeable
                    sortable={
                        col?.Sortable?.toLowerCase() === 'false'
                            ? false
                            : col?.Editor
                            ? col?.Editor?.SizeMode !== 'Squeeze'
                            : true
                    }
                    style={colStyle}
                    className={'overflow-hidden text-overflow-ellipsis pr-1'
                        .concat(col?.className || '')
                        .concat(
                            col?.FormatType?.toLowerCase() === 'numeric' ||
                                col?.Editor?.MaskType?.toLowerCase() ===
                                    'numeric'
                                ? ' justify-content-end'
                                : ''
                        )}
                    body={(item) => RowBody(item, col)}
                    key={col.ID}
                    //id={col.ID}
                    field={col.field}
                    header={colHeader(col)}
                    filter={
                        col?.Sortable?.toLowerCase() !== 'false' && filter
                    }
                    headerTooltip={
                        col.ShowCaption === 'false'
                            ? customTranslator(col.ID)
                            : undefined
                    }
                    headerTooltipOptions={{
                        event: 'both',
                        hideDelay: 300,
                        position: 'bottom',
                        autoHide: true,
                        className:
                            'customTableTooltip flex align-items-center justify-content-center',
                    }}
                    filterElement={
                        col?.Sortable?.toLowerCase() !== 'false' &&
                        filter &&
                        getFilterElement(
                            col,
                            filters,
                            setFilters,
                            entityId,
                            checkboxTable
                        )
                    }
              
                />``
i tried to upgrade to version 9 and 10 but we encountred auther issues (styling ,contextmenu not showing at version 9.6....)
Any help please?

### PrimeReact version

8.7.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

chrome

**Comment by melloware** [comment] 2023-10-30 13:12
Duplicate of https://github.com/primefaces/primereact/issues/4835

**Closed by melloware** 2023-10-30 13:12 UTC
Labels: Status: Needs Reproducer
