### ISSUE TITLE
Global esc key listener error in Calendar timepicker

### ISSUE THREAD

**Issue by mrpsiho** [primefaces/primereact#7286] opened 2024-10-01 10:19 UTC
### Describe the bug

I am using `primereact` version `10.8.3` and experiencing the error `Uncaught Error: Unexpected: global esc key listener with priority [600, 0] already exists.`. It can be reproduced also in your demo.

### System Information

```Shell
primereact: 10.8.3
```

### Steps to reproduce the behavior

1. Go to https://primereact.org/calendar/#time
2. Open "Time Only" picker and change **hour** to any other value. Just click up or down to change it. Or change minutes.
3. Click on the sibling datepicker/timepicker. The application crashes.
When clicking `Esc` or non-datepicker element - it works though.

### Expected behavior

No error.

**Comment by melloware** [comment] 2024-10-01 20:44
Duplicate of https://github.com/primefaces/primereact/issues/7220

**Closed** 2024-10-01 20:45 UTC
Labels: Resolution: Duplicate
