### ISSUE TITLE
Slider: The event.value within the onSlideEnd method does not reflect the updated value.

### ISSUE THREAD

**Issue by LeandroMarcondes** [primefaces/primereact#4752] opened 2023-08-09 05:26 UTC
### Describe the bug

When utilizing the Slider component along with the onSlideEnd event, it's observed that the event.value does not represent the updated value. Instead, it retains the previous value.

### Reproducer

https://codesandbox.io/s/primereact-slider-new-value-bug-sv3gwp

### PrimeReact version

9.6.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Firefox

### Steps to reproduce the behavior

1.     Incorporate the Slider component into your project.
2.     Establish two useState hooks, such as (value, newVal).
3.     Assign the value prop to {value} and onChange={(e) => setValue(e.value)}.
4.     set onSlideEnd={(e) => setNewVal(e.value)}.
5.     Display both useState values on the screen.
6.     Modify the value of the Slider component.

### Expected behavior

Once the Slider modifications are completed and the Slider is released or loses focus, the NewVal state should be equal to the value state.

**Comment by akshayaqburst** [comment] 2023-08-09 10:21
I will work on it

**Comment by akshayantony55** [comment] 2023-08-09 10:40
> I will work on it

Sorry, With the same code in codesandbox and my local environment, its working in my local vs not working in sandbox. Not really sure why!!

![image](https://github.com/primefaces/primereact/assets/63507009/3783ea91-114a-4d28-8a7d-5b994bbda1a2)
![image](https://github.com/primefaces/primereact/assets/63507009/add105a3-dc58-4b46-9ca1-c39bf8c8ab9f)

**Comment by melloware** [comment] 2023-08-09 10:50
I think I already fixed this.  Check closed tickets

**Comment by melloware** [comment] 2023-08-09 11:17
Duplicate of https://github.com/primefaces/primereact/issues/4680

**Closed by melloware** 2023-08-09 11:17 UTC
Labels: Status: Needs Triage
