### ISSUE TITLE
Datatable: Filters input typing slow when many columns

### ISSUE THREAD

**Issue by Commando-Brando** [primefaces/primereact#6912] opened 2024-07-21 02:13 UTC
### Describe the bug

Whenever I have a lot of columns on a datatable, filter inputs become slow and block input for up to multiple seconds at a time.

### Reproducer

https://stackblitz.com/edit/vitejs-vite-xbgte7?file=src%2FApp.tsx

### PrimeReact version

10.6.6

### React version

17.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome, Edge, Firefox

### Steps to reproduce the behavior

1. Click on filter for any column
2. Try typing in the filter box

### Expected behavior

Expected behavior is that the filter input does not block typing at all

**Comment by melloware** [comment] 2024-07-21 12:03
Duplicate of: https://github.com/primefaces/primereact/issues/5017

Duplicate of: https://github.com/primefaces/primereact/issues/6811

**Closed by melloware** 2024-07-21 12:03 UTC
Labels: Resolution: Duplicate
