### ISSUE TITLE
Chips component: add 'readOnly' property

### ISSUE THREAD

**Issue by giovannispd** [primefaces/primereact#2334] opened 2021-10-01 13:14 UTC
```
[ X ] feature request
```
Add 'readOnly' property in Chips component fo using it only for display values (eg. summary for search filter setted in dialog)

**Comment by melloware** [comment] 2021-10-16 20:09
Duplicate of https://github.com/primefaces/primereact/issues/2228

**Closed** 2021-11-04 11:52 UTC
Labels: new feature
