### ISSUE TITLE
Headless Confirm dialog shows no styles.

### ISSUE THREAD

**Issue by core2drew** [primefaces/primereact#5945] opened 2024-02-12 23:27 UTC
### Describe the bug

I followed the documentation on how to implement the Headless Confirm dialog and it doesn't seem to work as expected.

Here I just copy and paste it from the site.

![image](https://github.com/primefaces/primereact/assets/9361946/d4bdcefa-887c-48d7-9600-1c453499d8a3)

And here is how I called it is also a copy paste code fom the site (you might notice that I remove the "group" and "mahmut" cause it has error on my side for some reason).

![image](https://github.com/primefaces/primereact/assets/9361946/7e64e6d4-bfc5-4d6a-ab58-ae83229dd0cb)

Here is what it looks like on my side when I called it.
![image](https://github.com/primefaces/primereact/assets/9361946/55731b12-ea04-4b55-847f-0dad67bbce5e)

 I also notice that it has error message in the console about:
 Invalid value for prop `content` on <div> tag.
 

![image](https://github.com/primefaces/primereact/assets/9361946/c80d5daf-2c8f-43b2-8300-b48c1458a57a)

### PrimeReact version

10.5.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome, Firefox

### Steps to reproduce the behavior

Follow the implementation for headless confirm dialog in the prime react site (latest version - 10.5.0)

**Comment by melloware** [comment] 2024-02-12 23:41
So if you are using styled mode make sure you include a PrimeReact Theme   

If you are using unstyled mode it is a duplicate of this https://github.com/primefaces/primereact/issues/5837

**Closed** 2024-02-12 23:41 UTC
Labels: Resolution: Duplicate

**Comment by core2drew** [comment] 2024-02-12 23:49
Sorry, I didnt include the imports, but yes I included the PrimeReact theme.

![image](https://github.com/primefaces/primereact/assets/9361946/bb92a33c-9021-43a8-b8a4-cbeb955adf45)

**Comment by melloware** [comment] 2024-02-12 23:53
Can you create a reproducer it works fine for me and has for years using Pr themes.

**Comment by core2drew** [comment] 2024-02-12 23:55
I think I got the answer, I need to use PrimeFlex for this to work.. 

Thanks for the support :)
