### ISSUE TITLE
MegaMenu: On intial load image is loading incorrectly

### ISSUE THREAD

**Issue by bonisebi** [primefaces/primereact#7299] opened 2024-10-02 14:12 UTC
### Describe the bug

In the profile  icon I have added a image and  on initial load for a split second, the image is viewed as a whole enlarged size and then css hits and settle down. Not sure if its one of the issue with the integration part.

### System Information

```Shell
System:
    OS: Windows 11 10.0.22621
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 643.77 MB / 15.73 GB
  Binaries:
    Node: 22.9.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
```

**Comment by melloware** [comment] 2024-10-02 15:21
Duplicate of #6956

**Closed** 2024-10-02 15:21 UTC
Labels: Resolution: Duplicate
