### ISSUE TITLE
DropDown problem

### ISSUE THREAD

**Issue by ctamiozzo** [primefaces/primereact#6923] opened 2024-07-25 09:46 UTC
### Describe the bug

In version 10.7.0 the optionValue property of the DropDown component doesn't work. (in version 10.6.6 is ok)
The problem is in the funcion
    var getOptionValue = function getOptionValue(option) {
      var optionValue = props.OptionValue ? utils.ObjectUtils.resolveFieldData(option, props.optionValue) : utils.ObjectUtils.resolveFieldData(option, 'value');
      return utils.ObjectUtils.isNotEmpty(optionValue) ? optionValue : option;
    };
As you can see in the first line of the funciton there is a props.OptionValue with a capital O.
This lead to the fact that the component ignores the optionValue property.

### PrimeReact version

10.7.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment] 2024-07-25 11:18
Duplicate of https://github.com/primefaces/primereact/issues/6822 already fixed for next release

**Closed** 2024-07-29 12:20 UTC
Labels: Resolution: Duplicate
