### ISSUE TITLE
Dialog: Dismissible spelled incorrectly

### ISSUE THREAD

**Issue by zeachco** [primefaces/primereact#4312] opened 2023-04-29 17:06 UTC
### Describe the bug

`dismissableMask` is not proper english, the correct term is `dismissibleMask`

### Reproducer

```jsx
    <Dialog
      dismissableMask
      dismissibleMask
    >
```

### PrimeReact version

9.3.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

This will not add a dismissible mask. On a project without Typescript, that could result in frustration.

```jsx
    <Dialog
      dismissibleMask
      {...otherProps}
    >
```

### Expected behavior

`dismissibleMask` would be the default attribute and `dismissableMask` an alias (maybe deprecated)
Documentation being updated to the proper term (with a note for retro compatibility about `dismissableMask` if the team wishes to be retro compatible)

**Comment by melloware** [comment] 2023-04-29 18:25
Duplicate of https://github.com/primefaces/primereact/pull/2565 which was decided by PrimeTek and closed

**Closed** 2023-04-29 18:46 UTC
Labels: Resolution: Duplicate
