### ISSUE TITLE
DropDown: DropDown panel gets stuck at fixed height when has virtualScroller enabled and no items

### ISSUE THREAD

**Issue by GilbertoFreitasJunior** [primefaces/primereact#4112] opened 2023-03-01 18:47 UTC
### Describe the bug

The dropdown component, when isn't showing enough items to fill its panel, still shows a fixed height

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-4npgvu?file=/src/demo.js

### PrimeReact version

9.2.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Expected behavior

expected panel to display only height to keep its items, not excess height

**Comment by melloware** [comment] 2023-06-05 12:41
I think this might be a duplicate of this: https://github.com/primefaces/primereact/issues/4252

**Closed** 2023-11-26 22:46 UTC
Labels: Resolution: Duplicate
