### ISSUE TITLE
Group bug with scrollable property

### ISSUE THREAD

**Issue by yavuzcetin34** [primefaces/primereact#3121] opened 2022-07-31 15:20 UTC
### Describe the bug

Hİ.

Grid layout is broken when turning on scrollable property

![bug_report](https://user-images.githubusercontent.com/9559951/182033296-a8050a7a-09ca-4d36-9582-38839be59f2f.gif)

### PrimeReact version

8.0.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Preact

**Comment by melloware** [comment] 2022-07-31 17:43
Duplicate of: https://github.com/primefaces/primereact/issues/3091

Please see that ticket for more information and subscribe to it!

**Closed by melloware** 2022-07-31 17:43 UTC
Labels: defect, :bangbang: needs-triage
