### ISSUE TITLE
FileUpload: ref property does not show all the props

### ISSUE THREAD

**Issue by Ritik2411** [primefaces/primereact#3045] opened 2022-07-08 06:26 UTC
### Describe the bug

I am getting not getting all the properties from the ref of the FileUpload its  only showing these three props **{upload: ƒ upload(), clear: ƒ clear(), formatSize: ƒ formatSize()}**. 

While on v7 and before I was getting all the properties **FileUpload {props: Object, context: Object, refs: Object, updater: Object, state: Object…}** 

Because of this I am not able to get all the information about file being uploaded. 
Can u help me in this?

### Reproducer

https://codesandbox.io/s/sleepy-wood-t3qxd5?file=/src/demo/FileUploadDemo.js

### PrimeReact version

8.1.0

### React version

17.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Expected behavior

I want to get all props from ref like this: **FileUpload {props: Object, context: Object, refs: Object, updater: Object, state: Object…}**

**Comment by melloware** [comment] 2022-07-08 11:31
Duplicate of https://github.com/primefaces/primereact/issues/2893

**Closed** 2022-07-08 11:32 UTC
Labels: defect
